import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const parallelStructureReplacementQuestions = [
  createExpansionQuestion({
    id: "repl3-parallel-01",
    passage: "The device is compact, durable, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it can be transported easily", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("with easy transportation", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("transporting it is easy", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("easy to transport", "The three items should all be adjective phrases describing the device."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-02",
    passage: "The archive project involved sorting letters, scanning photographs, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("to catalog maps", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the catalog of maps", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("cataloging maps", "The series uses parallel gerund phrases."),
      choice("maps were cataloged", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-03",
    passage: "The critic praises the novel for its vivid setting, its complex characters, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the style being restrained", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("its restrained style", "The series consists of parallel noun phrases beginning with \u201cits.\u201d"),
      choice("it is stylistically restrained", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("stylistic restraint", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-04",
    passage: "The reform aimed to shorten delays and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("improve transparency", "The coordinated verbs should both be in base form."),
      choice("transparency was improved", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("improving transparency", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("to have more transparency", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-05",
    passage: "The researchers hoped to measure temperature precisely, to record humidity continuously, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("pressure was monitored remotely", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("monitoring pressure remotely", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("remote monitoring of pressure", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("to monitor pressure remotely", "The series uses parallel infinitive phrases."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-06",
    passage: "The platform allows users to compare prices, review shipping times, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("tracking orders", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("to the tracking of orders", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("track orders", "The coordinated verbs should remain in base form."),
      choice("orders can be tracked", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-07",
    passage: "The narrator is observant, skeptical, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("trusting strangers reluctantly", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("reluctant to trust strangers", "The list should contain parallel adjective phrases."),
      choice("she rarely trusts strangers", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("with reluctance toward strangers", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-08",
    passage: "The survey examined how often participants exercised, how long they slept, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("how much stress they reported", "The items should be parallel subordinate clauses beginning with \u201chow.\u201d"),
      choice("their reported stress", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("reporting stress levels", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("how stressful were they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-09",
    passage: "The proposal would reduce energy use, simplify maintenance, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("repairs would become less expensive", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("making repairs less expensive", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("lower repair costs", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("make repairs less expensive", "All three items should be parallel verb phrases."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-10",
    passage: "The critic argues that the play is formally inventive, historically informed, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("with emotional restraint", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("restraining emotion", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("emotionally restrained", "The coordinated descriptions should all be adjective phrases."),
      choice("it restrains emotion", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-11",
    passage: "The law requires agencies to publish contracts promptly, to provide searchable copies, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("explanations of redactions", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("to explain any redactions", "The series uses parallel infinitive phrases."),
      choice("explaining any redactions", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("any redactions must be explained", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-parallel-12",
    passage: "The historian's method involves reading official reports critically, comparing them with diaries, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("identifying gaps between the sources", "The list uses parallel gerund phrases."),
      choice("gaps between the sources are identified", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("to identify gaps between the sources", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the identification of gaps between the sources", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
];