import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const pronounsReplacementQuestions = [
  createExpansionQuestion({
    id: "repl3-pronouns-01",
    passage: "The researchers tested the new sensor, and _____ recorded the results.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("their", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("they", "The plural antecedent \u201cresearchers\u201d requires the subject pronoun \u201cthey.\u201d"),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-02",
    passage: "The museum displayed the restored map because _____ had recently been conserved.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("them", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("their", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("it", "The singular antecedent \u201cmap\u201d is replaced by \u201cit.\u201d"),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-03",
    passage: "The paintings were moved after conservators examined _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("their", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "The plural object \u201cpaintings\u201d requires the object pronoun \u201cthem.\u201d"),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-04",
    passage: "Each participant completed _____ own questionnaire.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("their", "Singular \u201ctheir\u201d correctly refers to the gender-neutral singular antecedent \u201cEach participant.\u201d"),
      choice("its", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-05",
    passage: "When the team compared the two filters, _____ found that one removed more fine particles.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("their", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("it", "The singular collective noun \u201cteam\u201d is treated as a singular unit here."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-06",
    passage: "The agency revised the guidelines before publishing _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("their", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "The plural noun \u201cguidelines\u201d requires the object pronoun \u201cthem.\u201d"),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-07",
    passage: "When Elena spoke with Mara, _____ explained why the letter mattered.",
    prompt: "Which choice most clearly completes the text if Mara is the one who explained?",
    choices: [
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("Mara", "Repeating \u201cMara\u201d avoids an ambiguous pronoun reference."),
      choice("she", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("her", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-08",
    passage: "The company informed the suppliers that _____ would receive revised contracts.",
    prompt: "Which choice most clearly completes the text if the suppliers would receive the contracts?",
    choices: [
      choice("the suppliers", "Repeating the noun removes ambiguity about who would receive the contracts."),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the company", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-09",
    passage: "After the council met with the agency, _____ announced the revised timeline.",
    prompt: "Which choice most clearly completes the text if the agency made the announcement?",
    choices: [
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the council", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the agency", "Repeating the specific noun avoids an ambiguous pronoun reference."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-10",
    passage: "The curator placed the sketch beside the sculpture because _____ revealed an earlier stage of the artist's process.",
    prompt: "Which choice most clearly completes the text if the sketch revealed the earlier stage?",
    choices: [
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the sculpture", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the sketch", "The explicit noun phrase clearly identifies the intended antecedent."),
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-11",
    passage: "The researchers told the technicians that _____ needed to recalibrate the instrument.",
    prompt: "Which choice most clearly completes the text if the technicians needed to recalibrate it?",
    choices: [
      choice("the researchers", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the technicians", "Repeating the noun eliminates ambiguity in the pronoun \u201cthey.\u201d"),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("them", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "repl3-pronouns-12",
    passage: "The sample was compared with the reference material after _____ had been cooled.",
    prompt: "Which choice most clearly completes the text if only the sample had been cooled?",
    choices: [
      choice("the sample", "Repeating \u201cthe sample\u201d prevents ambiguity between the two singular nouns."),
      choice("it", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("they", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
      choice("the reference material", "This choice breaks parallel structure or creates an unclear or incorrect pronoun reference."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-10"],
    walkthrough: [
      "Identify the grammatical form established by the sentence or the exact antecedent of the pronoun.",
      "Choose the option that is structurally parallel and unambiguous.",
    ],
  }),
];