import Link from "next/link";
import type { Course } from "@/content/courses";
import CourseQuestionCard from "@/components/course/CourseQuestionCard";
import FlashcardGrid from "@/components/course/FlashcardGrid";

export default function GrammarCoursePage({ course }: { course: Course }) {
  return <main className="pageShell"><section className="pageHero grammarCourseHero"><div className="container featureHeroGrid"><div><p className="eyebrow">Grammar & Writing · Complete Course</p><h1>{course.title}</h1><p>{course.subtitle}</p><div className="heroActions"><a className="button buttonPrimary" href="#lesson">Start lesson</a><Link className="button buttonGhost" href="/practice/grammar">Grammar Center</Link></div></div><div className="featurePreviewCard"><span className="largeFeatureIcon">20</span><span className="statusPill">Interactive Practice</span><h2>{course.workedExamples.length} examples · {course.questions.length} questions</h2><p>{course.flashcards.length} flashcards · {course.estimatedMinutes} minutes · {course.difficulty}</p></div></div></section><div className="container pageContent coursePage">
  <section className="courseObjectives" id="lesson"><div><p className="sectionKicker">Course overview</p><h2>What you will master</h2><p>{course.description}</p></div><ul>{course.objectives.map((x,i)=><li key={`${course.id}-objective-${i}`}>{x}</li>)}</ul></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Rulebook</p><h2>Build the grammar skill</h2></div><div className="courseSectionGrid">{course.concepts.map((x,i)=><article key={`${course.id}-concept-${i}`}><h3>{x.title}</h3><p>{x.body}</p>{x.bullets?<ul>{x.bullets.map((b,j)=><li key={`${course.id}-concept-${i}-bullet-${j}`}>{b}</li>)}</ul>:null}</article>)}</div></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Five-step editing strategy</p><h2>Use the same process every time</h2></div><div className="strategySteps">{course.strategy.map((x,i)=><div key={`${course.id}-strategy-${i}`}><span>{i+1}</span><strong>{x.title}</strong><p>{x.body}</p></div>)}</div></section>
  <section className="coachNotebook"><p className="sectionKicker">Editor’s Notebook</p><h2>Structure first. Meaning preserved.</h2><div className="coachTipGrid">{course.coachTips.map((x,i)=><blockquote key={`${course.id}-tip-${i}`}>{x}</blockquote>)}</div></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Trap library</p><h2>Recognize tempting wrong answers</h2></div><div className="courseSectionGrid">{course.traps.map((x,i)=><article key={`${course.id}-trap-${i}`}><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Worked examples</p><h2>Watch the editing method in action</h2></div><div className="workedExampleList">{course.workedExamples.map((q,i)=><article className="workedExample" key={q.id}><div className="courseQuestionMeta"><span>Example {i+1}</span><span>{q.difficulty}</span></div><p className="coursePassage">{q.passage}</p><h3>{q.prompt}</h3><ol type="A">{q.choices.map((c,j)=><li className={j===q.answer?"contextCorrectAnswer":""} key={`${q.id}-choice-${j}`}>{c.text}</li>)}</ol><details><summary>Show walkthrough and explanation</summary><ol>{q.walkthrough.map((s,j)=><li key={`${q.id}-step-${j}`}>{s}</li>)}</ol><p><strong>Correct answer:</strong> {String.fromCharCode(65+q.answer)}. {q.choices[q.answer].text}</p><p>{q.choices[q.answer].rationale}</p></details></article>)}</div></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Guided practice</p><h2>20 original SAT-style questions</h2></div><div className="courseQuestionList">{course.questions.map((q,i)=><CourseQuestionCard key={q.id} question={q} number={i+1}/>)}</div></section>
  <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Review deck</p><h2>30 rule flashcards</h2></div><FlashcardGrid cards={course.flashcards}/></section>
  <section className="practiceNextSteps"><div><p className="sectionKicker">Course complete</p><h2>Continue the Grammar learning path</h2><p>Apply the rule only after identifying the sentence structure and intended meaning.</p></div><div className="heroActions">{course.nextCourseId?<Link className="button buttonPrimary" href={`/practice/grammar/${course.nextCourseId}`}>Next course</Link>:null}<Link className="button buttonGhost" href="/tutor">Ask AI Tutor</Link></div></section>
  </div></main>;
}
