import Link from "next/link";
import type { Course } from "@/content/courses";
import CourseQuestionCard from "@/components/course/CourseQuestionCard";
import FlashcardGrid from "@/components/course/FlashcardGrid";

export default function MathCoursePage({ course }: { course: Course }) {
 return <main className="pageShell"><section className="pageHero mathCourseHero"><div className="container featureHeroGrid"><div><p className="eyebrow">Digital SAT Math · {course.domain ?? "Algebra"}</p><h1>{course.title}</h1><p>{course.subtitle}</p><div className="heroActions"><a className="button buttonPrimary" href="#lesson">Start lesson</a><Link className="button buttonGhost" href="/practice/math">Math Center</Link></div></div><div className="featurePreviewCard"><span className="largeFeatureIcon">ƒ</span><span className="statusPill">Interactive Practice</span><h2>{course.workedExamples.length} examples · {course.questions.length} questions</h2><p>{course.flashcards.length} review cards · {course.estimatedMinutes} minutes</p></div></div></section><div className="container pageContent coursePage">
 <section className="courseObjectives" id="lesson"><div><p className="sectionKicker">Course overview</p><h2>What you will master</h2><p>{course.description}</p></div><ul>{course.objectives.map((x,i)=><li key={`${course.id}-objective-${i}`}>{x}</li>)}</ul></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Concept toolkit</p><h2>Build the math skill</h2></div><div className="courseSectionGrid">{course.concepts.map((x,i)=><article key={`${course.id}-concept-${i}`}><h3>{x.title}</h3><p>{x.body}</p>{x.bullets?<ul>{x.bullets.map((b,j)=><li key={`${course.id}-concept-${i}-bullet-${j}`}>{b}</li>)}</ul>:null}</article>)}</div></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Five-step solver</p><h2>Use a repeatable process</h2></div><div className="strategySteps">{course.strategy.map((x,i)=><div key={`${course.id}-strategy-${i}`}><span>{i+1}</span><strong>{x.title}</strong><p>{x.body}</p></div>)}</div></section>
 <section className="coachNotebook"><p className="sectionKicker">Math Coach</p><h2>Model first. Calculate second.</h2><div className="coachTipGrid">{course.coachTips.map((x,i)=><blockquote key={`${course.id}-tip-${i}`}>{x}</blockquote>)}</div></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Trap library</p><h2>Catch predictable mistakes</h2></div><div className="courseSectionGrid">{course.traps.map((x,i)=><article key={`${course.id}-trap-${i}`}><h3>{x.title}</h3><p>{x.body}</p></article>)}</div></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Worked examples</p><h2>See the method in action</h2></div><div className="workedExampleList">{course.workedExamples.map((q,i)=><article className="workedExample" key={q.id}><div className="courseQuestionMeta"><span>Example {i+1}</span><span>{q.difficulty}</span></div><p className="coursePassage">{q.passage}</p><h3>{q.prompt}</h3><ol type="A">{q.choices.map((c,j)=><li className={j===q.answer?"contextCorrectAnswer":""} key={`${q.id}-choice-${j}`}>{c.text}</li>)}</ol><details><summary>Show solution</summary><ol>{q.walkthrough.map((s,j)=><li key={`${q.id}-step-${j}`}>{s}</li>)}</ol><p><strong>Correct answer:</strong> {q.choices[q.answer].text}</p><p>{q.choices[q.answer].rationale}</p></details></article>)}</div></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Guided practice</p><h2>20 original SAT-style questions</h2></div><div className="courseQuestionList">{course.questions.map((q,i)=><CourseQuestionCard key={q.id} question={q} number={i+1}/>)}</div></section>
 <section className="practiceLessonSection"><div className="sectionHeader"><p className="sectionKicker">Review deck</p><h2>30 concept cards</h2></div><FlashcardGrid cards={course.flashcards}/></section>
 <section className="practiceNextSteps"><div><p className="sectionKicker">Course complete</p><h2>Continue the {course.domain ?? "Math"} path</h2><p>Rework missed questions without looking at the previous solution.</p></div><div className="heroActions">{course.nextCourseId?<Link className="button buttonPrimary" href={`/practice/math/${course.nextCourseId}`}>Next course</Link>:<Link className="button buttonPrimary" href="/practice/math">Math Center</Link>}<Link className="button buttonGhost" href="/tutor">Ask AI Tutor</Link></div></section>
 </div></main>;
}
