"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { DesmosCalculator } from "@/components/adaptive/DesmosCalculator";
import { getQuestion } from "@/lib/adaptive/questionBank";
import { useAdaptiveExamStore } from "@/store/adaptiveExamStore";

function DataTable({headers,rows,caption}:{headers:string[];rows:string[][];caption?:string}){
 return <figure className="mathDataFigure">{caption&&<figcaption>{caption}</figcaption>}<table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></figure>;
}
function MiniGraph({points,xLabel,yLabel}:{points:Array<[number,number]>;xLabel?:string;yLabel?:string}){
 const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);
 const sx=(x:number)=>35+(x-minX)/(maxX-minX||1)*290; const sy=(y:number)=>185-(y-minY)/(maxY-minY||1)*145;
 return <figure className="mathGraphFigure"><svg viewBox="0 0 360 220" role="img" aria-label="Coordinate graph"><line x1="35" y1="185" x2="330" y2="185"/><line x1="35" y1="25" x2="35" y2="185"/><polyline points={points.map(([x,y])=>`${sx(x)},${sy(y)}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="3"/>{points.map(([x,y],i)=><circle key={i} cx={sx(x)} cy={sy(y)} r="4" fill="currentColor"/>)}<text x="330" y="205">{xLabel??"x"}</text><text x="14" y="28">{yLabel??"y"}</text></svg></figure>;
}
export default function AdaptiveExamPage(){const store=useAdaptiveExamStore();const [now,setNow]=useState(Date.now());const [calculatorOpen,setCalculatorOpen]=useState(false);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 if(store.status==="idle")return <main className="pageShell"><div className="container pageContent examStart"><p className="eyebrow">Adaptive SAT · Math Engine 2.0</p><h1>Ready for a compact diagnostic?</h1><p>Four timed modules with official-style multiple-choice, student-response, table, graph, and modeling questions.</p><button className="button buttonPrimary" onClick={store.startExam}>Begin simulation</button></div></main>;
 if(store.status==="complete")return <main className="pageShell"><div className="container pageContent examStart"><h1>Simulation complete.</h1><p>Your adaptive route and skill report are ready.</p><Link className="button buttonPrimary" href="/adaptive/results">Open results</Link></div></main>;
 const mod=store.modules[store.moduleIndex];const id=mod?.questionIds[store.questionIndex];const q=id?getQuestion(id):undefined;if(!mod||!q)return null;const ans=store.answers[id];const elapsed=store.moduleStartedAt?Math.floor((now-store.moduleStartedAt)/1000):0;const remain=Math.max(0,mod.timeLimit-elapsed);const mm=String(Math.floor(remain/60)).padStart(2,"0"),ss=String(remain%60).padStart(2,"0");
 const answered=q.questionType==="student-response"?Boolean(ans?.typedAnswer?.trim()):Boolean(ans&&ans.selected>=0);
 const isMath=mod.section==="Math";
 return <main className="examShell"><header className="examTopbar"><div><strong>{mod.title}</strong><span>Question {store.questionIndex+1} of {mod.questionIds.length}</span></div><div className="examTopbarTools">{isMath&&<button type="button" className={`calculatorToggle ${calculatorOpen?"active":""}`} onClick={()=>setCalculatorOpen(v=>!v)} aria-expanded={calculatorOpen}>🧮 Calculator</button>}<div className="examTimer" aria-label="Time remaining">{mm}:{ss}</div></div></header><div className={`examWorkspace ${calculatorOpen&&isMath?"calculatorOpen":""}`}><div className="examLayout"><section className="examQuestionPanel"><div className="courseQuestionMeta"><span>{q.courseTitle}</span><span>{q.difficulty} · {q.skill}{q.mathDomain?` · ${q.mathDomain}`:q.domain?` · ${q.domain}`:""}</span></div>{q.calculatorRecommended&&<p className="calculatorBadge">🧮 Calculator recommended</p>}<p className="coursePassage">{q.passage}</p>{q.tableData&&<DataTable {...q.tableData}/>} {q.graphData&&<MiniGraph {...q.graphData}/>}<h2>{q.prompt}</h2>{q.questionType==="student-response"?<div className="studentResponseBox"><label htmlFor="student-answer">Answer</label><input id="student-answer" inputMode="decimal" placeholder="Integer, decimal, or fraction" value={ans?.typedAnswer??""} onChange={e=>store.answerText(id,e.target.value)}/><small>Equivalent forms such as 3/4 and 0.75 are accepted.</small></div>:<div className="courseChoiceList">{q.choices.map((c,i)=><button key={i} className={`courseChoice ${ans?.selected===i?"examChoiceSelected":""}`} onClick={()=>store.answer(id,i)}><strong>{String.fromCharCode(65+i)}.</strong> {c.text}</button>)}</div>}<div className="examControls"><button className="button buttonGhost" onClick={store.previousQuestion} disabled={store.questionIndex===0}>Previous</button><button className="button buttonGhost" onClick={()=>store.toggleFlag(id)}>{ans?.flagged?"Unmark review":"Mark for review"}</button>{store.questionIndex<mod.questionIds.length-1?<button className="button buttonPrimary" onClick={store.nextQuestion}>Next</button>:<button className="button buttonPrimary" onClick={store.finishModule}>Submit module</button>}</div></section><aside className="examPalette"><h3>Question palette</h3><div>{mod.questionIds.map((qid,i)=>{const a=store.answers[qid],qq=getQuestion(qid);const done=qq?.questionType==="student-response"?Boolean(a?.typedAnswer?.trim()):Boolean(a&&a.selected>=0);return <button key={qid} onClick={()=>store.goToQuestion(i)} className={`${i===store.questionIndex?"active":""} ${done?"answered":""} ${a?.flagged?"flagged":""}`}>{i+1}</button>})}</div><p><span className="paletteKey answered"/> Answered <span className="paletteKey flagged"/> Review</p></aside></div>{isMath&&<DesmosCalculator key={mod.key} moduleKey={mod.key} open={calculatorOpen} onClose={()=>setCalculatorOpen(false)}/>}</div></main>}
