import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const modifiersExpansion6Questions = [
  createExpansionQuestion({
    id: "rexp6-modifiers-01",
    passage: "Covered in a thin layer of ice, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("researchers photographed the frozen surface.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there was a reflection on the lake.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the lake reflected the morning light.", "The noun immediately following the introductory modifier must be the thing covered in ice."),
      choice("the morning light reflected from the lake.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The noun immediately following the introductory modifier must be the thing covered in ice.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-02",
    passage: "After reading the letters, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the letters seemed more important.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the historian revised her interpretation.", "The historian is the person who read the letters."),
      choice("the interpretation was revised by the historian.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("new questions about the period emerged.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The historian is the person who read the letters.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-03",
    passage: "Painted in vivid colors, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the mural attracts attention from across the plaza.", "The mural is what was painted in vivid colors."),
      choice("visitors notice the mural from across the plaza.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the plaza seems brighter to visitors.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("attention is attracted across the plaza.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The mural is what was painted in vivid colors.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-04",
    passage: "While waiting for the bus, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the arrival display was checked.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the bus seemed delayed.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there were updates on the display.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the commuters checked the arrival display.", "The commuters are the ones waiting."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The commuters are the ones waiting.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-05",
    passage: "Using a high-resolution microscope, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the coating showed tiny cracks to the researchers.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there were tiny cracks in the coating.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the researchers observed tiny cracks in the coating.", "The researchers are the users of the microscope."),
      choice("tiny cracks in the coating were observed.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The researchers are the users of the microscope.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-06",
    passage: "Designed to improve access, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("there are searchable records in the portal.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the online portal includes searchable records.", "The portal is what was designed to improve access."),
      choice("residents can search records through the online portal.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("searchable records are included by the online portal.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The portal is what was designed to improve access.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-07",
    passage: "Walking through the abandoned house, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the narrator notices every creak and draft.", "The narrator is the one walking."),
      choice("every creak and draft is noticed by the narrator.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the abandoned rooms seem increasingly strange.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there are creaks and drafts around the narrator.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The narrator is the one walking.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-08",
    passage: "After reviewing the quarterly figures, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the forecast was lowered by the analysts.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("a lower forecast seemed reasonable.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the quarterly figures suggested slower growth.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the analysts lowered their forecast.", "The analysts are the ones who reviewed the figures."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The analysts are the ones who reviewed the figures.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-09",
    passage: "Built before the railway arrived, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("merchants later expanded the warehouse.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there was a warehouse serving river traffic.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the warehouse originally served river traffic.", "The warehouse is what was built before the railway arrived."),
      choice("river traffic originally used the warehouse.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The warehouse is what was built before the railway arrived.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-10",
    passage: "To reduce measurement error, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("measurement error was reduced by calibration.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the team calibrated the instrument twice.", "The team is the actor carrying out the purpose."),
      choice("the instrument was calibrated twice by the team.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("two calibrations were performed.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The team is the actor carrying out the purpose.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-11",
    passage: "Although initially dismissed as unfinished, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the sculpture later became one of the artist's best-known works.", "The sculpture is what was initially dismissed."),
      choice("critics later praised the sculpture as one of the artist's best-known works.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the artist's reputation grew because of the sculpture.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there was later broad praise for the sculpture.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The sculpture is what was initially dismissed.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-12",
    passage: "By comparing samples collected at different depths, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("a clear temperature gradient was identified.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the samples revealed a clear temperature gradient to the researchers.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there appeared to be a clear temperature gradient.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the researchers identified a clear temperature gradient.", "The researchers perform the comparison."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The researchers perform the comparison.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-13",
    passage: "Having selected their own schedules, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the study could not eliminate every source of bias.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there may have been differences among participants.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the participants may have differed in motivation before the study began.", "The participants are the ones who selected their schedules."),
      choice("motivation may have differed before the study began.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The participants are the ones who selected their schedules.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-14",
    passage: "Intended to make records easier to use, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("there is support for full-text search.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the new file format supports full-text search.", "The file format is what was intended to improve usability."),
      choice("residents can use full-text search in the new file format.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the agency introduced full-text search.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The file format is what was intended to improve usability.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-15",
    passage: "Preserved in three separate archives, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the documents provide an unusually complete record.", "The documents are what were preserved."),
      choice("historians can consult the documents in three places.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the archives contain an unusually complete record.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there is an unusually complete documentary record.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The documents are what were preserved.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-modifiers-16",
    passage: "After accounting for differences in humidity, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the temperature effect remained significant to the researchers.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("a significant temperature effect was still found.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("there was still a significant temperature effect.", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the researchers found that the temperature effect remained significant.", "The researchers are the ones who accounted for humidity differences."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The researchers are the ones who accounted for humidity differences.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
];