import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const parallelStructureExpansion6Questions = [
  createExpansionQuestion({
    id: "rexp6-parallel-01",
    passage: "The device is lightweight, durable, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("repairs easily", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("it can be repaired easily", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("with easy repairs", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("easy to repair", "The three items should all be adjective phrases describing the device."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The three items should all be adjective phrases describing the device.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-02",
    passage: "The project involved collecting letters, scanning photographs, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("to catalog maps", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the catalog of maps", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("cataloging maps", "The series uses parallel gerund phrases."),
      choice("maps were cataloged", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series uses parallel gerund phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-03",
    passage: "The mural is admired for its scale, its color, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the patterns are intricate", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("its intricate patterns", "The series consists of parallel noun phrases beginning with \u201cits.\u201d"),
      choice("it has intricate patterns", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("patterning intricately", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series consists of parallel noun phrases beginning with \u201cits.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-04",
    passage: "The policy aimed to lower costs and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("increase access", "The two coordinated verbs should be in parallel base form."),
      choice("access was increased", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("increasing access", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to have greater access", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The two coordinated verbs should be in parallel base form.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-05",
    passage: "The researchers wanted to measure temperature accurately, to record humidity continuously, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("pressure was monitored remotely", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("monitoring pressure remotely", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("remote pressure monitoring", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to monitor pressure remotely", "The series uses parallel infinitive phrases."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series uses parallel infinitive phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-06",
    passage: "The portal allows residents to search records, download files, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("submitting requests", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to submission of requests", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("submit requests", "The coordinated verbs should remain in base form."),
      choice("requests can be submitted", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The coordinated verbs should remain in base form.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-07",
    passage: "The narrator is observant, skeptical, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("trusting others reluctantly", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("reluctant to trust others", "The list should contain parallel adjective phrases."),
      choice("she rarely trusts others", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("with reluctance toward trust", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The list should contain parallel adjective phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-08",
    passage: "The study examined how often participants exercised, how long they slept, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("how much stress they reported", "The items should be parallel \u201chow\u201d clauses."),
      choice("their reported stress", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("reporting stress levels", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("how stressful were they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The items should be parallel \u201chow\u201d clauses.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-09",
    passage: "The archive's goals are preserving fragile documents, improving public access, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("new research is supported", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to support new research", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("support for new research", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("supporting new research", "The series uses parallel gerund phrases."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series uses parallel gerund phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-10",
    passage: "The treatment not only reduced recovery time but also _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("improving mobility", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("an improvement in mobility", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("improved mobility", "The correlative structure requires parallel verb phrases."),
      choice("mobility was improved", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The correlative structure requires parallel verb phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-11",
    passage: "The proposal would reduce administrative costs, simplify the application process, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("greater clarity in eligibility rules", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("make eligibility rules easier to understand", "All three items should be parallel verb phrases."),
      choice("eligibility rules would be easier to understand", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("making eligibility rules easier to understand", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "All three items should be parallel verb phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-12",
    passage: "The critic argues that the novel is formally inventive, historically informed, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("emotionally restrained", "The coordinated descriptions should all be adjective phrases."),
      choice("it restrains emotion", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("with emotional restraint", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("restraining emotion", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The coordinated descriptions should all be adjective phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-13",
    passage: "The law requires agencies to publish contracts promptly, to provide searchable copies, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("explaining any redactions", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("any redactions must be explained", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("explanations of redactions", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to explain any redactions", "The series uses parallel infinitive phrases."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series uses parallel infinitive phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-14",
    passage: "The team compared not only the material's strength under pressure but also _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it was flexible at low temperatures", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("low-temperature flexibility was measured", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("its flexibility at low temperatures", "The noun phrases after \u201cnot only\u201d and \u201cbut also\u201d should be parallel."),
      choice("how flexible was it at low temperatures", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The noun phrases after \u201cnot only\u201d and \u201cbut also\u201d should be parallel.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-15",
    passage: "The survey asked whether residents trusted the agency, whether they understood the policy, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("expecting the reform to help", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("whether they expected the reform to help", "The series requires three parallel subordinate clauses beginning with \u201cwhether.\u201d"),
      choice("their expectations about whether the reform would help", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("did they expect the reform to help", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The series requires three parallel subordinate clauses beginning with \u201cwhether.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-parallel-16",
    passage: "The historian's method involves reading official reports critically, comparing them with personal accounts, and _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("identifying gaps between the sources", "The list uses parallel gerund phrases."),
      choice("gaps between the sources are identified", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("to identify gaps between the sources", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the identification of gaps between the sources", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Parallel Structure",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The list uses parallel gerund phrases.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
];