import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const pronounsExpansion6Questions = [
  createExpansionQuestion({
    id: "rexp6-pronouns-01",
    passage: "The researchers tested the sensor, and _____ recorded the results.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "The plural subject \u201cresearchers\u201d requires the subject pronoun \u201cthey.\u201d"),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The plural subject \u201cresearchers\u201d requires the subject pronoun \u201cthey.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-02",
    passage: "The archive displayed the map because _____ was recently restored.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("it", "The singular noun \u201cmap\u201d is replaced by \u201cit.\u201d"),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The singular noun \u201cmap\u201d is replaced by \u201cit.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-03",
    passage: "The paintings were moved after conservators examined _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "The plural object \u201cpaintings\u201d requires the object pronoun \u201cthem.\u201d"),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The plural object \u201cpaintings\u201d requires the object pronoun \u201cthem.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-04",
    passage: "Each participant completed _____ own survey.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("their", "Singular \u201cthey/their\u201d correctly refers to the gender-neutral singular antecedent \u201cEach participant.\u201d"),
      choice("its", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Singular \u201cthey/their\u201d correctly refers to the gender-neutral singular antecedent \u201cEach participant.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-05",
    passage: "When the team compared the two coatings, _____ found that one resisted heat better.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("it", "The singular collective noun \u201cteam\u201d is treated as a singular unit here."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The singular collective noun \u201cteam\u201d is treated as a singular unit here.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-06",
    passage: "The agency revised the guidelines before publishing _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "The plural noun \u201cguidelines\u201d requires the object pronoun \u201cthem.\u201d"),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The plural noun \u201cguidelines\u201d requires the object pronoun \u201cthem.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-07",
    passage: "When Mara spoke with Elena, _____ explained why the letter mattered.",
    prompt: "Which choice most clearly completes the text if Mara is the one who explained?",
    choices: [
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("Mara", "Repeating \u201cMara\u201d avoids the ambiguity of \u201cshe.\u201d"),
      choice("she", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("her", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Repeating \u201cMara\u201d avoids the ambiguity of \u201cshe.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-08",
    passage: "The company informed the suppliers that _____ would receive revised contracts.",
    prompt: "Which choice most clearly completes the text if the suppliers would receive the contracts?",
    choices: [
      choice("the suppliers", "Repeating the noun removes ambiguity about who receives the contracts."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the company", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Repeating the noun removes ambiguity about who receives the contracts.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-09",
    passage: "The diary and the map were stored together because _____ documented the same journey.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("its", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "The compound antecedent is plural and requires \u201cthey.\u201d"),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The compound antecedent is plural and requires \u201cthey.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-10",
    passage: "Neither instrument produced readings consistent with _____ calibration standard.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("its", "The singular antecedent \u201cNeither instrument\u201d takes the singular possessive pronoun \u201cits.\u201d"),
      choice("their", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The singular antecedent \u201cNeither instrument\u201d takes the singular possessive pronoun \u201cits.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-11",
    passage: "After the council met with the agency, _____ announced the revised timeline.",
    prompt: "Which choice most clearly completes the text if the agency made the announcement?",
    choices: [
      choice("the council", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the agency", "Repeating the specific noun avoids an ambiguous pronoun reference."),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Repeating the specific noun avoids an ambiguous pronoun reference.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-12",
    passage: "The curator placed the sketch beside the sculpture because _____ revealed an earlier stage of the artist's process.",
    prompt: "Which choice most clearly completes the text if the sketch revealed the earlier stage?",
    choices: [
      choice("the sketch", "The noun phrase clearly identifies the intended antecedent."),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the sculpture", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The noun phrase clearly identifies the intended antecedent.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-13",
    passage: "The researchers told the technicians that _____ needed to recalibrate the instrument.",
    prompt: "Which choice most clearly completes the text if the technicians needed to recalibrate it?",
    choices: [
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the researchers", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the technicians", "The explicit noun eliminates ambiguity in \u201cthey.\u201d"),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The explicit noun eliminates ambiguity in \u201cthey.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-14",
    passage: "Every participant submitted _____ response before leaving.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("their", "Singular \u201ctheir\u201d agrees with the gender-neutral singular antecedent \u201cEvery participant.\u201d"),
      choice("its", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Singular \u201ctheir\u201d agrees with the gender-neutral singular antecedent \u201cEvery participant.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-15",
    passage: "The letters differ from the official report because _____ describe several weeks of disruption.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("its", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "The plural antecedent \u201cletters\u201d requires \u201cthey.\u201d"),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("them", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "The plural antecedent \u201cletters\u201d requires \u201cthey.\u201d",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp6-pronouns-16",
    passage: "The sample was compared with the reference material after _____ had been cooled.",
    prompt: "Which choice most clearly completes the text if only the sample had been cooled?",
    choices: [
      choice("the sample", "Repeating \u201cthe sample\u201d prevents ambiguity between the two singular nouns."),
      choice("it", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("they", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
      choice("the material", "This choice creates an unclear modifier, breaks parallel structure, or uses an incorrect or ambiguous pronoun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-6", "standard-english-conventions"],
    walkthrough: [
      "Identify the grammatical relationship tested in the sentence.",
      "Repeating \u201cthe sample\u201d prevents ambiguity between the two singular nouns.",
      "Choose the option that is clear, parallel, and unambiguous.",
    ],
  }),
];