import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const concisionExpansion4Questions = [
  createExpansionQuestion({
    id: "rexp4-concision-01",
    passage: "The newly discovered frog is small in size and measures only three centimeters long.",
    prompt: "Which choice most effectively revises the underlined portion to make the sentence more concise?",
    choices: [
      choice("The newly discovered frog, which is newly discovered, measures only three centimeters long.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The newly discovered small frog is small and measures only three centimeters in its length.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The newly discovered frog measures only three centimeters long.", "The revision removes the redundant phrase \u201csmall in size\u201d while preserving the complete meaning."),
      choice("The newly discovered frog is small in size, and it measures only three centimeters long in length.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The revision removes the redundant phrase \u201csmall in size\u201d while preserving the complete meaning.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-02",
    passage: "The archive contains letters that were written by soldiers during the war.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The archive is a place containing letters written by soldiers who were in the war.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The archive contains letters written by soldiers during the war.", "Removing \u201cthat were\u201d makes the sentence shorter without changing its meaning."),
      choice("The archive contains letters that soldiers had written by themselves during the war.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The archive contains in it letters that were written during the war by soldiers.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "Removing \u201cthat were\u201d makes the sentence shorter without changing its meaning.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-03",
    passage: "The mural is circular in shape and covers the entire wall.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The circular mural covers the entire wall.", "The revision expresses both ideas directly and eliminates redundancy."),
      choice("The mural, which is circular in shape, covers the wall in its entirety.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The mural is a shape that is circular, and it covers the entire wall.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The mural covers the entire whole wall and is circular in shape.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The revision expresses both ideas directly and eliminates redundancy.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-04",
    passage: "The survey was conducted in order to learn how residents use the park.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The survey was conducted for the purpose of learning how residents use the park.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In order for researchers to learn how residents use the park, a survey was conducted.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The survey that was conducted was done in order to learn about park use by residents.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The survey was conducted to learn how residents use the park.", "\u201cTo learn\u201d expresses purpose more concisely than \u201cin order to learn.\u201d"),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cTo learn\u201d expresses purpose more concisely than \u201cin order to learn.\u201d",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-05",
    passage: "Because the device is lightweight in weight, researchers can carry it easily into remote areas.",
    prompt: "Which choice most effectively revises the underlined portion?",
    choices: [
      choice("Due to the fact that the device is lightweight in its overall weight, researchers can carry it easily into remote areas.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The device, being lightweight in weight, is something researchers can carry easily into remote areas.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Because the device is lightweight, researchers can carry it easily into remote areas.", "\u201cLightweight\u201d already describes weight, so the phrase \u201cin weight\u201d is unnecessary."),
      choice("Because the device has a weight that is light in weight, researchers can carry it easily into remote areas.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cLightweight\u201d already describes weight, so the phrase \u201cin weight\u201d is unnecessary.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-06",
    passage: "The company reduced costs by eliminating expenses that were unnecessary and not needed.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Costs were reduced by the company when it eliminated expenses not needed because they were unnecessary.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The company reduced costs by eliminating unnecessary expenses.", "The revision removes duplication and uses a direct verb phrase."),
      choice("The company reduced costs by eliminating expenses that were both unnecessary and also not needed.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The company reduced its costs through the elimination of expenses that were unnecessary.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The revision removes duplication and uses a direct verb phrase.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-07",
    passage: "The committee reached a unanimous agreement in which every member agreed.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The committee reached a unanimous agreement.", "\u201cUnanimous\u201d already means that every member agreed."),
      choice("The committee reached an agreement that was unanimous because every member agreed unanimously.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Every member of the committee reached an agreement in a unanimous way.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The committee came to an agreement that all members agreed to.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cUnanimous\u201d already means that every member agreed.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-08",
    passage: "The narrator returns back to the village after ten years away.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The narrator returns back again to the village after being away for ten years.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("After ten years away, the narrator makes a return back to the village.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The narrator goes back in return to the village after ten years.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The narrator returns to the village after ten years away.", "\u201cReturns\u201d already includes the meaning of \u201cback.\u201d"),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cReturns\u201d already includes the meaning of \u201cback.\u201d",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-09",
    passage: "The researchers compared the two materials with each other under identical conditions.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Under conditions that were identical, the researchers compared both materials to each other.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The two materials were compared with one another by the researchers under identical conditions.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The researchers compared the two materials under identical conditions.", "\u201cCompared the two materials\u201d already implies comparison with each other."),
      choice("The researchers made a comparison of the two materials with each other under identical conditions.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cCompared the two materials\u201d already implies comparison with each other.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-10",
    passage: "The treaty was signed at noon, at which point in time the fighting stopped.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The fighting stopped at the time when the treaty at noon was signed.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The treaty was signed at noon, when the fighting stopped.", "\u201cWhen\u201d replaces the wordy phrase without losing the temporal relationship."),
      choice("The treaty was signed at noon, which was the point in time when the fighting stopped.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("At noon, the treaty was signed, and at that point in time the fighting came to a stop.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cWhen\u201d replaces the wordy phrase without losing the temporal relationship.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-11",
    passage: "The critic argues that the novel's fragmented chronology is a feature that serves the function of reflecting the narrator's uncertain memory.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The critic argues that the novel's fragmented chronology reflects the narrator's uncertain memory.", "The revision replaces abstract noun phrases with the direct verb \u201creflects.\u201d"),
      choice("The critic makes the argument that the novel's fragmented chronology is a feature serving the function of reflecting uncertain memory on the narrator's part.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("According to the critic's argument, the chronology, which is fragmented, has the function of reflecting the narrator's memory that is uncertain.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The novel's fragmented chronology is argued by the critic to be a feature whose function is reflection of uncertainty in memory.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The revision replaces abstract noun phrases with the direct verb \u201creflects.\u201d",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-12",
    passage: "The study's findings provide an indication that the treatment may possibly reduce recovery time.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The study's findings provide an indication suggesting that the treatment may possibly reduce recovery time.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The findings of the study are indicative of the possibility that recovery time may possibly be reduced by the treatment.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The study provides findings that give an indication about a possible reduction in recovery time.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The study's findings suggest that the treatment may reduce recovery time.", "\u201cSuggest\u201d is more direct, and \u201cmay\u201d already conveys possibility."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cSuggest\u201d is more direct, and \u201cmay\u201d already conveys possibility.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-13",
    passage: "The policy had the effect of causing firms to delay investments until a later time.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Firms delayed investments until a later time as an effect caused by the policy.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The effect of the policy was a causing of delays in investments by firms.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The policy caused firms to delay investments.", "The direct verb \u201ccaused\u201d eliminates unnecessary nominalizations and \u201cuntil a later time.\u201d"),
      choice("The policy had an effect that caused firms to delay investments until later in time.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The direct verb \u201ccaused\u201d eliminates unnecessary nominalizations and \u201cuntil a later time.\u201d",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-14",
    passage: "Participants who had prior experience beforehand completed the task more quickly.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Participants having experience previously beforehand were quicker in completing the task.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Participants with prior experience completed the task more quickly.", "\u201cPrior\u201d already means earlier, and \u201cwith\u201d is more concise than \u201cwho had.\u201d"),
      choice("Participants who had experience that was prior beforehand completed the task more quickly.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Those participants who beforehand had prior experience completed the task in a quicker manner.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cPrior\u201d already means earlier, and \u201cwith\u201d is more concise than \u201cwho had.\u201d",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-15",
    passage: "The report recommends the implementation of a system for the purpose of tracking applications.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The report recommends implementing a system to track applications.", "The revision uses active verb forms and removes the wordy purpose phrase."),
      choice("The report recommends implementation of a system that has the purpose of tracking applications.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For the purpose of tracking applications, the report gives a recommendation for system implementation.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The report's recommendation is for the implementation of a tracking system for applications for tracking purposes.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "The revision uses active verb forms and removes the wordy purpose phrase.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-concision-16",
    passage: "The letters reveal that residents were in agreement with one another about rebuilding the bridge again.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The letters reveal that residents were mutually in agreement with one another about rebuilding the bridge again.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Residents, the letters reveal, had agreement among themselves to rebuild the bridge again another time.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The letters show an agreement that was shared by residents with one another about bridge rebuilding.", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("The letters reveal that residents agreed to rebuild the bridge.", "\u201cAgreed\u201d replaces a wordy phrase, and \u201crebuild\u201d already means build again."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Identify words or phrases that repeat an idea already expressed.",
      "\u201cAgreed\u201d replaces a wordy phrase, and \u201crebuild\u201d already means build again.",
      "Choose the shortest grammatically complete option that preserves the intended meaning.",
    ],
  }),
];