import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const transitionsExpansion4Questions = [
  createExpansionQuestion({
    id: "rexp4-transition-01",
    passage: "The first trial produced inconsistent measurements. _____, the researchers recalibrated the instrument before the second trial.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Therefore,", "The recalibration is a result of the inconsistent measurements."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Meanwhile,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The recalibration is a result of the inconsistent measurements.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-02",
    passage: "The bridge was designed for trains. _____, it later became a pedestrian walkway.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("However,", "The later use contrasts with the bridge's original purpose."),
      choice("For instance,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Likewise,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Consequently,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The later use contrasts with the bridge's original purpose.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-03",
    passage: "The exhibit includes paintings from the 1920s. _____, it features several sculptures from the same decade.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Instead,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Nevertheless,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("As a result,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In addition,", "The sculptures are an additional feature of the exhibit."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The sculptures are an additional feature of the exhibit.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-04",
    passage: "The store lowered delivery fees. _____, online orders increased.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Meanwhile,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("As a result,", "The increase in orders is presented as a consequence of the lower fees."),
      choice("In contrast,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The increase in orders is presented as a consequence of the lower fees.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-05",
    passage: "The coating performed well in dry laboratory tests. _____, its performance declined during outdoor tests conducted in heavy rain.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("In addition,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("By contrast,", "The outdoor result contrasts with the laboratory result."),
      choice("Consequently,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The outdoor result contrasts with the laboratory result.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-06",
    passage: "Real-time arrival displays did not reduce actual bus wait times. _____, riders reported that waiting felt less uncertain.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Nevertheless,", "The reported benefit occurred despite the unchanged wait time."),
      choice("Therefore,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Specifically,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The reported benefit occurred despite the unchanged wait time.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-07",
    passage: "The city published more records online. _____, many documents were image files that could not be searched.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Accordingly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Likewise,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("However,", "The second sentence presents a limitation of the apparent improvement."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The second sentence presents a limitation of the apparent improvement.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-08",
    passage: "Official reports describe the strike as brief. _____, workers' diaries refer to disruptions lasting several weeks.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For instance,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Moreover,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In contrast,", "The diaries conflict with the official description."),
      choice("As a result,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The diaries conflict with the official description.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-09",
    passage: "The model predicts earlier flowering as temperatures rise. _____, some species respond mainly to day length rather than temperature.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Yet", "The second statement limits the general prediction."),
      choice("Therefore,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The second statement limits the general prediction.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-10",
    passage: "The critic praises the novel's vivid setting. _____, she argues that the ending is overly predictable.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("At the same time,", "The critic offers praise and criticism simultaneously."),
      choice("For this reason,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In other words,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The critic offers praise and criticism simultaneously.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-11",
    passage: "The experimental material retained 92% of its strength after cooling. The standard material retained 74%. _____, the two materials were tested at different humidity levels, so the comparison is not fully controlled.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Accordingly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In the same way,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Even so,", "The final sentence qualifies the apparent advantage despite the preceding result."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The final sentence qualifies the apparent advantage despite the preceding result.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-12",
    passage: "Sales rose after the company reduced prices. _____, a major competitor closed during the same month, providing another possible explanation for the increase.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For instance,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("However,", "The competitor's closure complicates the causal interpretation."),
      choice("Therefore,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The competitor's closure complicates the causal interpretation.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-13",
    passage: "Participants who chose flexible schedules reported greater satisfaction. _____, because employees selected their own schedules, the study cannot rule out self-selection.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Likewise,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Still,", "The second sentence qualifies the result with a methodological limitation."),
      choice("Consequently,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The second sentence qualifies the result with a methodological limitation.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-14",
    passage: "A census recorded a sharp population decline after the flood. _____, school records show that many families returned the following year.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("On the other hand,", "The later records complicate an interpretation of permanent population loss."),
      choice("As a result,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For instance,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The later records complicate an interpretation of permanent population loss.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-15",
    passage: "The portal increased the number of records available to the public. _____, the use of technical file formats meant that many residents could not easily analyze those records.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Therefore,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("In addition,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Nonetheless,", "The second sentence introduces a practical limitation despite increased availability."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The second sentence introduces a practical limitation despite increased availability.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp4-transition-16",
    passage: "One scholar interprets the novel's repeated doors as symbols of opportunity. _____, another scholar notes that many of the doors are locked or lead back to rooms already visited.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For example,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Similarly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
      choice("Conversely,", "The second scholar offers an opposing interpretation."),
      choice("Accordingly,", "This choice is wordy, redundant, illogical, or does not fit the relationship between ideas."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 70,
    tags: ["reading-expansion-pack-4", "expression-of-ideas"],
    walkthrough: [
      "Determine the logical relationship between the sentence before and after the blank.",
      "The second scholar offers an opposing interpretation.",
      "Choose the transition that expresses that exact relationship.",
    ],
  }),
];