import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const finalConcisionQuestions = [
  createExpansionQuestion({
    id: "repl5-concision-01",
    passage: "The instrument was able to detect changes that were very small in size.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Very small changes in size were able to be detected by the instrument.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The instrument had the ability to detect changes that were small in their size.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The instrument detected very small changes.", "The direct verb removes unnecessary wording without changing the meaning."),
      choice("The instrument was able to make detections of changes small in size.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The direct verb removes unnecessary wording without changing the meaning.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-concision-02",
    passage: "The council made a decision to postpone the vote until a later date.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The vote was postponed until a date that was later by a council decision.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The council decided to postpone the vote.", "\u201cDecided\u201d replaces the wordy phrase \u201cmade a decision.\u201d"),
      choice("The council made the decision that the vote would be postponed until later.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("A decision was made by the council to postpone the vote to a later date.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "\u201cDecided\u201d replaces the wordy phrase \u201cmade a decision.\u201d",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-concision-03",
    passage: "The report provides an explanation of why prices increased at a rapid rate.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The report explains why prices increased rapidly.", "The direct verb and adverb make the sentence more concise."),
      choice("The report provides an explanation regarding why prices increased at a rapid rate.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("Why prices increased rapidly is provided as an explanation in the report.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The report is explanatory of the reason why prices increased rapidly.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The direct verb and adverb make the sentence more concise.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-concision-04",
    passage: "The agency conducted an evaluation of the program for the purpose of determining its effectiveness.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The agency conducted an evaluation in order to determine how effective the program was.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("For the purpose of determining effectiveness, the agency conducted an evaluation of the program.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("An evaluation of the program was conducted by the agency to determine effectiveness.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The agency evaluated the program to determine its effectiveness.", "Active verbs replace abstract nouns and remove redundancy."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "Active verbs replace abstract nouns and remove redundancy.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-concision-05",
    passage: "The essay makes the argument that the painting is a work that challenges traditional perspective.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The painting is argued by the essay to be challenging traditional perspective.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The essay's argument is that the painting is a work challenging traditional perspective.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("The essay argues that the painting challenges traditional perspective.", "The concise revision uses direct verbs and preserves the claim."),
      choice("The essay makes an argument about the painting being a work that challenges perspective traditionally.", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The concise revision uses direct verbs and preserves the claim.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
];