import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const finalPronounQuestions = [
  createExpansionQuestion({
    id: "repl5-pronouns-01",
    passage: "The samples were labeled before the technicians stored _____.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("it", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("their", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("them", "The plural object \u201csamples\u201d requires the object pronoun \u201cthem.\u201d"),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The plural object \u201csamples\u201d requires the object pronoun \u201cthem.\u201d",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-02",
    passage: "When the curator met the donor, _____ described how the manuscript had been preserved.",
    prompt: "Which choice most clearly completes the text if the donor gave the description?",
    choices: [
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the curator", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the donor", "Repeating the noun removes ambiguity between the two people."),
      choice("she", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "Repeating the noun removes ambiguity between the two people.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-03",
    passage: "The board informed the managers that _____ would present the revised budget.",
    prompt: "Which choice most clearly completes the text if the managers would present it?",
    choices: [
      choice("the board", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the managers", "The explicit noun phrase identifies the intended subject."),
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("it", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The explicit noun phrase identifies the intended subject.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-04",
    passage: "The alloy was compared with the ceramic after _____ had been heated to 500\u00b0C.",
    prompt: "Which choice most clearly completes the text if only the alloy was heated?",
    choices: [
      choice("the alloy", "Repeating the noun avoids ambiguity between two singular antecedents."),
      choice("it", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the ceramic", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "Repeating the noun avoids ambiguity between two singular antecedents.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-05",
    passage: "The mayor spoke with the director after _____ had approved the revised plan.",
    prompt: "Which choice most clearly completes the text if the director approved it?",
    choices: [
      choice("she", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the mayor", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the director", "The explicit noun clearly identifies who approved the plan."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The explicit noun clearly identifies who approved the plan.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-06",
    passage: "The critic discussed the poem with the editor because _____ had questioned its final line.",
    prompt: "Which choice most clearly completes the text if the editor raised the question?",
    choices: [
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the critic", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the editor", "Repeating the noun prevents an unclear pronoun reference."),
      choice("she", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "Repeating the noun prevents an unclear pronoun reference.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-pronouns-07",
    passage: "The researchers interviewed the participants after _____ had completed the second survey.",
    prompt: "Which choice most clearly completes the text if the participants completed it?",
    choices: [
      choice("the researchers", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("the participants", "The explicit plural noun removes ambiguity in \u201cthey.\u201d"),
      choice("they", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("them", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Pronouns",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The explicit plural noun removes ambiguity in \u201cthey.\u201d",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
];