import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const finalTransitionQuestions = [
  createExpansionQuestion({
    id: "repl5-transitions-01",
    passage: "The battery lasted longer in cool conditions. _____, its performance declined sharply in extreme heat.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("However,", "The second sentence contrasts with the first."),
      choice("Therefore,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("For example,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("Similarly,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The second sentence contrasts with the first.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-transitions-02",
    passage: "The official record lists only two meetings. _____, several private letters mention a third gathering.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Consequently,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("For instance,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("Likewise,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("By contrast,", "The private letters conflict with the official record."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The private letters conflict with the official record.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-transitions-03",
    passage: "The subsidy lowered the initial purchase price. _____, maintenance costs remained high.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For example,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("Similarly,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("Nevertheless,", "The maintenance problem remained despite the lower price."),
      choice("As a result,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The maintenance problem remained despite the lower price.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
  createExpansionQuestion({
    id: "repl5-transitions-04",
    passage: "The first chapter presents the city as orderly and predictable. _____, later chapters reveal hidden conflicts beneath that appearance.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Moreover,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("In contrast,", "The later chapters present an opposing view."),
      choice("Accordingly,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
      choice("For example,", "This choice is less precise, grammatically incorrect, ambiguous, or does not preserve the intended relationship."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["final-coverage-restoration", "reading-expansion-pack-12"],
    walkthrough: [
      "Identify the sentence's grammatical structure or logical relationship.",
      "The later chapters present an opposing view.",
      "Choose the option that is precise, clear, and conventionally correct.",
    ],
  }),
];