import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const centralIdeasExpansion2Questions = [
  createExpansionQuestion({
    id: "rexp2-central-01",
    passage: "Researchers compared two coral reefs after a heat wave. One reef had greater genetic diversity and recovered much faster, but the study did not establish that diversity alone caused the recovery because water quality also differed between the sites.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Genetic diversity had no relationship to recovery.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Water quality was identical at the two reefs.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The study proved that diversity was the sole cause of recovery.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The more diverse reef recovered faster, though other site differences prevent a simple causal conclusion.", "The text reports an association but explicitly limits the causal claim."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The text reports an association but explicitly limits the causal claim.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-02",
    passage: "A city's early maps label a riverside district as industrial, while later oral histories describe homes, shops, and schools there. Taken together, the sources suggest that official maps captured only part of the district's actual use.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Schools replaced the river during the period.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Different sources reveal that the district served more purposes than official maps indicated.", "The passage uses two source types to show that the mapped label was incomplete."),
      choice("The oral histories prove that no industry existed.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The maps recorded every building in the district.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The passage uses two source types to show that the mapped label was incomplete.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-03",
    passage: "A satellite study found that lakes with darker water warmed more quickly in spring. The researchers note, however, that darker lakes were also generally shallower, and shallow lakes tend to warm faster. They therefore recommend experiments that independently vary water color and depth.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Dark water always causes lakes to become deeper.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The study found no relationship between lake features and warming.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Satellite observations can independently vary lake depth.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The observed link between water color and warming may be influenced by lake depth, so controlled tests are needed.", "The central point is the confounding role of depth and the need for control."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The central point is the confounding role of depth and the need for control.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-04",
    passage: "The narrator repeatedly describes a village bell as dependable, yet each time the bell rings the villagers misinterpret what it signals. By the end, the bell's mechanical regularity contrasts with the community's uncertain judgments.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The narrator argues that machines cannot be dependable.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The bell's consistency highlights the villagers' unreliable interpretations.", "The contrast between regular signal and unstable interpretation drives the passage."),
      choice("The bell gradually stops working.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The villagers always understand the bell correctly.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Literature",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The contrast between regular signal and unstable interpretation drives the passage.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-05",
    passage: "A survey showed that employees with flexible schedules reported higher satisfaction. But employees were allowed to choose whether to adopt flexible schedules, so those who expected to benefit most may have selected them. The researchers caution that the survey cannot isolate the effect of flexibility itself.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Flexible schedules necessarily reduce satisfaction.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Employees were randomly assigned to schedules.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The survey proves that flexibility has no effect.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Higher satisfaction among flexible-schedule employees may partly reflect self-selection.", "The passage centers on self-selection as a limitation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The passage centers on self-selection as a limitation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-06",
    passage: "After a city introduced congestion pricing, downtown traffic declined and subway ridership rose. During the same period, several large employers adopted remote-work policies. Analysts therefore disagree about how much of the traffic decline should be attributed to pricing alone.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Analysts agree that pricing caused every observed change.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Traffic changes followed congestion pricing, but simultaneous remote-work changes complicate causal attribution.", "The main idea combines the observed pattern with the competing explanation."),
      choice("Subway ridership fell after the policy.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Remote work increased downtown traffic.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The main idea combines the observed pattern with the competing explanation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-07",
    passage: "A transparency law required agencies to publish contracts online. Publication rates increased sharply, but many files were scanned images that could not be searched. Advocates argued that access had improved formally while remaining limited in practice.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The law reduced the number of published contracts.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Searchable files became illegal.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Advocates opposed public access to contracts.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The law increased publication but did not guarantee that records were practically usable.", "The key distinction is between nominal availability and functional accessibility."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The key distinction is between nominal availability and functional accessibility.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-central-08",
    passage: "A scholar notes that a poet's later editions remove several regional expressions. Rather than viewing the revisions simply as stylistic refinement, the scholar links them to the publisher's effort to market the poems nationally.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Stylistic revision and marketing can never overlap.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The revisions may reflect commercial efforts to broaden the poems' audience, not just stylistic preferences.", "The passage offers a commercial interpretation that complicates a purely stylistic one."),
      choice("The poet added more regional expressions in every edition.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The publisher refused to sell the poems nationally.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The passage offers a commercial interpretation that complicates a purely stylistic one.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
];
