import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const crossTextExpansion2Questions = [
  createExpansionQuestion({
    id: "rexp2-cross-01",
    passage: "Text 1: Green roofs reduced summer roof temperatures in a city study.\n\nText 2: The cooling effect was greatest on roofs with deeper soil.",
    prompt: "How does Text 2 relate to Text 1?",
    choices: [
      choice("It shows that soil depth never matters.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It identifies a condition that influenced the effect reported in Text 1.", "Text 2 qualifies the general result by naming a factor."),
      choice("It denies that green roofs affect temperature.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It discusses a different planet.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Text 2 qualifies the general result by naming a factor.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-02",
    passage: "Text 1: A reviewer praises a novel's short chapters for creating urgency.\n\nText 2: Another reviewer finds that the same short chapters make the story feel fragmented.",
    prompt: "How do the reviewers differ?",
    choices: [
      choice("They discuss different novels.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They agree that the chapters are too long.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They disagree about whether the novel has chapters.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They evaluate the effect of the same structural feature differently.", "Both focus on short chapters but assign opposite effects."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Humanities Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Both focus on short chapters but assign opposite effects.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-03",
    passage: "Text 1: Official reports describe a strike as brief and orderly.\n\nText 2: Workers' letters describe weeks of food shortages and uncertainty.",
    prompt: "What does Text 2 contribute to the topic of Text 1?",
    choices: [
      choice("It discusses an unrelated election.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It provides evidence that the strike's effects were more severe than the official description suggests.", "The letters complicate the official characterization."),
      choice("It proves that the strike never occurred.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It repeats the official account exactly.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired History Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The letters complicate the official characterization.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-04",
    passage: "Text 1: A model predicts that warmer springs will advance flowering dates.\n\nText 2: Observations show that some species flower earlier, while others respond mainly to day length.",
    prompt: "Taken together, what do the texts suggest?",
    choices: [
      choice("All species rely only on temperature.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Day length becomes shorter in warmer springs.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Models cannot study flowering.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Species may respond differently to warming because flowering cues vary.", "Text 2 adds variation in biological cues."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Text 2 adds variation in biological cues.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-05",
    passage: "Text 1: Remote work reduced commuting time for many employees.\n\nText 2: Some employees used the saved time for additional work rather than leisure.",
    prompt: "How does Text 2 qualify Text 1?",
    choices: [
      choice("It discusses only train schedules.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that time saved from commuting does not necessarily become free time.", "The benefit exists, but its use varies."),
      choice("It proves that remote work increases commuting.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It claims that employees never work from home.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Social Science Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The benefit exists, but its use varies.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-06",
    passage: "Text 1: A subsidy increased purchases of home insulation.\n\nText 2: Many recipients had already planned to insulate their homes.",
    prompt: "What question does Text 2 raise about the effect described in Text 1?",
    choices: [
      choice("Whether insulation exists.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Whether recipients owned homes.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Whether subsidies always lower energy prices immediately.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Whether the subsidy created new purchases or mainly accelerated planned ones.", "Text 2 raises an additionality question."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Economics Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Text 2 raises an additionality question.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-07",
    passage: "Text 1: Publishing meeting videos increased public access.\n\nText 2: Videos without captions remained inaccessible to many residents.",
    prompt: "How does Text 2 relate to Text 1?",
    choices: [
      choice("It changes the topic to road construction.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It identifies an accessibility limitation in the reform.", "The second text limits the scope of the claimed access gain."),
      choice("It proves that no videos were published.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It argues that meetings should be secret.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Government Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The second text limits the scope of the claimed access gain.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-08",
    passage: "Text 1: A scholar interprets repeated mirrors in a play as symbols of self-knowledge.\n\nText 2: Another scholar notes that characters often use mirrors to disguise themselves.",
    prompt: "How does Text 2 challenge Text 1?",
    choices: [
      choice("It proves that the play contains no mirrors.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It agrees that every mirror has one fixed meaning.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It discusses the play's ticket prices.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It suggests that the mirrors may also represent concealment rather than only self-knowledge.", "The second interpretation introduces an opposing symbolic function."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Humanities Texts",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The second interpretation introduces an opposing symbolic function.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-09",
    passage: "Text 1: A trial found that a new crop variety yielded more grain.\n\nText 2: The new variety also received more irrigation than the comparison crop.",
    prompt: "How would Text 2 most likely affect an interpretation of Text 1?",
    choices: [
      choice("It establishes that yield cannot be measured.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It weakens the claim that the variety alone caused the higher yield.", "Unequal irrigation is a confounding factor."),
      choice("It proves that irrigation has no effect.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that both crops received identical treatment.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Unequal irrigation is a confounding factor.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-10",
    passage: "Text 1: A census indicates a population decline after a flood.\n\nText 2: School records show many families returning the following year.",
    prompt: "Taken together, what do the texts suggest?",
    choices: [
      choice("The flood increased the permanent population immediately.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("No families ever left.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("School records and censuses measure identical events.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Some of the census decline may have reflected temporary displacement.", "Later returns complicate a permanent-loss interpretation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired History Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Later returns complicate a permanent-loss interpretation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-11",
    passage: "Text 1: People who use fitness apps exercise more often.\n\nText 2: People already committed to exercise are more likely to download fitness apps.",
    prompt: "How does Text 2 affect the causal interpretation of Text 1?",
    choices: [
      choice("It confirms random assignment.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It suggests that self-selection may partly explain the association.", "Preexisting motivation offers an alternative explanation."),
      choice("It proves that apps reduce exercise.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that app users never exercise.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Social Science Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Preexisting motivation offers an alternative explanation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-12",
    passage: "Text 1: Lower fares were followed by higher ridership.\n\nText 2: A major employer simultaneously ended remote work.",
    prompt: "What do the texts together indicate?",
    choices: [
      choice("Fare changes had no relationship to ridership.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Remote work increased during the period.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Only one factor changed.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The ridership increase may reflect both lower fares and more commuting.", "A simultaneous policy change complicates attribution."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Economics Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "A simultaneous policy change complicates attribution.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-13",
    passage: "Text 1: A critic reads a recurring river as a symbol of freedom.\n\nText 2: Several river scenes occur when characters are trapped or forced to retreat.",
    prompt: "How does Text 2 challenge Text 1?",
    choices: [
      choice("It discusses another work entirely.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It suggests that the river's meaning may include constraint as well as freedom.", "Contrasting scene contexts broaden the symbol's possible meaning."),
      choice("It proves there is no river.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It confirms a single unchanging meaning.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Humanities Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Contrasting scene contexts broaden the symbol's possible meaning.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-cross-14",
    passage: "Text 1: Laboratory tests show a coating resists corrosion.\n\nText 2: Field tests reveal cracks after repeated temperature changes.",
    prompt: "How does Text 2 relate to Text 1?",
    choices: [
      choice("It proves the coating never resisted corrosion.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that temperature never changes outdoors.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It repeats the laboratory result without qualification.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that performance under controlled conditions may not fully predict field durability.", "Field stress introduces conditions absent from the lab."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Field stress introduces conditions absent from the lab.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
];
