import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const quantitativeEvidenceExpansion2Questions = [
  createExpansionQuestion({
    id: "rexp2-quant-01",
    passage: "Average leaf area after three treatments:\nWater only: 14 cm\u00b2\nNutrient A: 19 cm\u00b2\nNutrient B: 16 cm\u00b2",
    prompt: "Which statement is best supported by the data?",
    choices: [
      choice("All treatments produced equal results.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Plants receiving Nutrient A had the largest average leaf area.", "19 cm\u00b2 is the largest value."),
      choice("Water-only plants had the largest leaves.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Nutrient B produced 19 cm\u00b2 leaves.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "19 cm\u00b2 is the largest value.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-02",
    passage: "Monthly subscriptions:\nJanuary: 420\nFebruary: 465\nMarch: 510",
    prompt: "Which choice best describes the trend?",
    choices: [
      choice("Subscriptions fell each month.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("January and March were equal.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Subscriptions rose and then fell below 420.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Subscriptions increased each month.", "The values rise from 420 to 465 to 510."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Economics Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The values rise from 420 to 465 to 510.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-03",
    passage: "Average recovery time:\nMethod A: 8.4 days\nMethod B: 7.1 days\nMethod C: 7.0 days",
    prompt: "Which choice most accurately characterizes the results?",
    choices: [
      choice("All methods produced identical times.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Methods B and C produced similar recovery times, both shorter than Method A.", "B and C differ by only 0.1 day and are both below A."),
      choice("Method A was fastest.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Method B exceeded Method C by 7 days.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Experimental Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "B and C differ by only 0.1 day and are both below A.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-04",
    passage: "Survey support for a proposal:\nAges 18\u201329: 61%\nAges 30\u201349: 58%\nAges 50+: 42%",
    prompt: "Which statement is best supported?",
    choices: [
      choice("Support increased steadily with age.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("All groups showed 61% support.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The oldest group had the highest support.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Support was highest among the youngest group and lowest among the oldest group.", "The percentages decrease across age groups."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The percentages decrease across age groups.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-05",
    passage: "Mean temperature reduction:\nMaterial X: 3.2\u00b0C\nMaterial Y: 3.0\u00b0C\nMaterial Z: 1.1\u00b0C",
    prompt: "Which conclusion is best supported?",
    choices: [
      choice("No material changed temperature.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Materials X and Y performed similarly and both outperformed Z.", "X and Y differ by 0.2\u00b0C and both exceed Z substantially."),
      choice("Material Z produced the greatest reduction.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("X and Y differed by more than 2\u00b0C.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "X and Y differ by 0.2\u00b0C and both exceed Z substantially.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-06",
    passage: "Letters digitized:\nCollection A: 240\nCollection B: 315\nCollection C: 302",
    prompt: "Which statement is best supported?",
    choices: [
      choice("Collection A contains the most.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Collection B exceeds C by 100.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("All collections are equal.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Collection B contains the most digitized letters, though only slightly more than Collection C.", "315 is highest and only 13 above 302."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Historical Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "315 is highest and only 13 above 302.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-07",
    passage: "Average wait time before and after a scheduling change:\nBefore: 18 minutes\nAfter: 12 minutes",
    prompt: "Which choice best quantifies the change?",
    choices: [
      choice("The change was less than 1 minute.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Average wait time fell by 6 minutes, or one-third of the original value.", "18 minus 12 is 6, and 6/18 is one-third."),
      choice("Wait time rose by 6 minutes.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Wait time fell by 18 minutes.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Economics Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "18 minus 12 is 6, and 6/18 is one-third.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-08",
    passage: "Germination rate:\nControl: 54%\nTreatment 1: 68%\nTreatment 2: 69%",
    prompt: "Which interpretation is most accurate?",
    choices: [
      choice("The control had the highest rate.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Treatment 1 exceeded Treatment 2 by 15 points.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The treatments had no germination.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Both treatments outperformed the control, while the two treatments performed almost identically.", "The treatment rates are close and both exceed 54%."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Experimental Data",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The treatment rates are close and both exceed 54%.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-09",
    passage: "Observed algae growth:\nLow light: 2.1 g\nMedium light: 4.8 g\nHigh light: 4.7 g\n\nWater temperature also rose with light level.",
    prompt: "Why do the data not by themselves prove that light caused the growth pattern?",
    choices: [
      choice("Low light produced some growth.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Temperature changed along with light and may also have affected growth.", "A correlated variable creates confounding."),
      choice("Growth was measured in grams.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Medium and high light produced similar values.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "A correlated variable creates confounding.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-10",
    passage: "Mean test scores:\nControl: 72\nProgram group: 79\n\nThe program group had a higher average pretest score.",
    prompt: "Which choice best evaluates the evidence?",
    choices: [
      choice("The control group scored higher.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Pretest scores can never matter.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The program certainly caused all 7 points.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The program group scored higher, but the pretest difference limits causal conclusions about the program.", "Baseline differences complicate attribution."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Experimental Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Baseline differences complicate attribution.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-11",
    passage: "Sales change after advertising:\nRegion A: +12%\nRegion B: +4%\nRegion C: +2%\n\nRegion A also opened five new stores.",
    prompt: "Which statement best evaluates the claim that advertising caused Region A's larger increase?",
    choices: [
      choice("Region B had the largest increase.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The new stores are another factor that could have contributed to Region A's growth.", "A simultaneous expansion confounds the comparison."),
      choice("The percentages prove advertising was the sole cause.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("New stores cannot affect sales.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Economics Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "A simultaneous expansion confounds the comparison.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-12",
    passage: "Reported satisfaction:\nFlexible schedule: 84%\nFixed schedule: 68%\n\nEmployees selected their own schedule type.",
    prompt: "Which choice best evaluates the evidence?",
    choices: [
      choice("The data prove fixed schedules cause satisfaction.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Employees were randomly assigned.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The percentages are identical.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The difference is consistent with a benefit of flexibility, but self-selection may explain part of it.", "Voluntary selection limits causal inference."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Voluntary selection limits causal inference.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-13",
    passage: "Battery retention after 300 cycles:\nDesign A: 82%\nDesign B: 75%\n\nDesign A batteries were tested at a lower temperature.",
    prompt: "Why is a direct comparison limited?",
    choices: [
      choice("Temperature has no physical effect.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Temperature differed between the tests and may affect retention.", "Unequal conditions reduce comparability."),
      choice("Retention percentages cannot be compared.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("Design B retained more capacity.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Unequal conditions reduce comparability.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-quant-14",
    passage: "Recorded households:\nCensus year 1: 1,240\nCensus year 2: 980\n\nMany residents were temporarily housed outside the district during year 2.",
    prompt: "Which interpretation is most justified?",
    choices: [
      choice("The district permanently lost exactly 260 households.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("No households left temporarily.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The census proves the district grew.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("The decline may reflect temporary displacement as well as permanent population loss.", "Temporary relocation complicates a permanent-loss conclusion."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Historical Data",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "Temporary relocation complicates a permanent-loss conclusion.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
];
