import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const textStructureExpansion2Questions = [
  createExpansionQuestion({
    id: "rexp2-structure-01",
    passage: "The passage first describes a device that measures soil moisture. It then explains that farmers can use the measurements to decide when irrigation is actually needed.",
    prompt: "What is the main purpose of the second sentence?",
    choices: [
      choice("To compare the device with a weather satellite.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To explain a practical use of the device described in the first sentence.", "The second sentence moves from description to application."),
      choice("To deny that soil moisture can be measured.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To describe the invention's historical origin.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The second sentence moves from description to application.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-02",
    passage: "A critic opens by calling a film visually restrained. The next paragraph catalogs moments when color suddenly becomes intense, arguing that these exceptions make emotional turning points more noticeable.",
    prompt: "How does the second paragraph relate to the first?",
    choices: [
      choice("It proves that the film contains no color.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It repeats the first paragraph without adding analysis.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It changes the topic from film to sculpture.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It explains how departures from the film's usual restraint create emphasis.", "The paragraph qualifies the general description by analyzing meaningful exceptions."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The paragraph qualifies the general description by analyzing meaningful exceptions.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-03",
    passage: "The author begins with a widely accepted model of bird migration. She then presents tracking data from one species that does not fit the model and closes by proposing a revised model with two migration strategies.",
    prompt: "Which choice best describes the structure of the text?",
    choices: [
      choice("It rejects all models as useless.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It presents a standard explanation, identifies anomalous evidence, and proposes a broader account.", "The organization is model, challenge, revision."),
      choice("It lists three unrelated species.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It introduces a revised model before any evidence.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The organization is model, challenge, revision.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-04",
    passage: "The passage quotes a law promising equal access to land, then contrasts the law with court records showing that fees prevented many applicants from filing claims. The final sentence argues that legal equality did not ensure practical equality.",
    prompt: "What is the function of the court records?",
    choices: [
      choice("They show that the law was never written.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They define the meaning of land.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They prove that every applicant received land.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("They provide evidence that complicates the promise stated in the law.", "The records reveal a barrier that undercuts the law's formal promise."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The records reveal a barrier that undercuts the law's formal promise.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-05",
    passage: "A scene is narrated twice: first through a child who sees a parade, then through an adult who recognizes a political protest. The repeated details remain the same, but their meaning changes with the observer.",
    prompt: "What is the main purpose of presenting the scene twice?",
    choices: [
      choice("To replace the child narrator permanently.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To show how perspective can alter the interpretation of the same events.", "The repeated event receives contrasting meanings from different viewpoints."),
      choice("To establish that the two scenes occur in different countries.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To prove that the parade never happened.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Literature",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The repeated event receives contrasting meanings from different viewpoints.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-06",
    passage: "The text reports that neighborhoods with more benches have more pedestrian activity. It then asks whether benches attract walkers or whether busy areas are more likely to receive benches.",
    prompt: "What is the function of the question?",
    choices: [
      choice("To prove that benches reduce walking.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To define the word neighborhood.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To show that pedestrian activity cannot be observed.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To identify uncertainty about the direction of causation.", "The question raises reverse causation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The question raises reverse causation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-07",
    passage: "The author describes a fall in prices after a new competitor entered a market. A later paragraph notes that raw-material costs also fell during the same period.",
    prompt: "How does the later paragraph affect the earlier explanation?",
    choices: [
      choice("It argues that prices did not change.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It introduces another factor that could have contributed to the price decline.", "The later information provides an alternative causal factor."),
      choice("It confirms that competition was the only cause.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("It shows that raw-material costs increased.", "This choice is unsupported, too broad, or inconsistent with the text."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The later information provides an alternative causal factor.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp2-structure-08",
    passage: "The passage first praises open-data portals for making records available. It then argues that highly technical file formats can prevent nonexperts from using those records effectively.",
    prompt: "Which choice best describes the text's overall purpose?",
    choices: [
      choice("To argue that records should remain secret.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To compare two election systems.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To explain how to design a database server.", "This choice is unsupported, too broad, or inconsistent with the text."),
      choice("To acknowledge the benefit of open data while identifying a limitation in accessibility.", "The passage balances a benefit with a practical limitation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-2", "coverage-gap"],
    walkthrough: [
      "Identify the text's central claim, relationship, or evidentiary requirement.",
      "The passage balances a benefit with a practical limitation.",
      "Reject choices that depend on information not established by the passage.",
    ],
  }),
];
