import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const modifiersReplacementQuestions = [
  createExpansionQuestion({
    id: "repl2-modifiers-01",
    passage: "Covered by a thin layer of frost, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("researchers photographed the field.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there was a bright reflection across the field.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the leaves sparkled in the morning sun.", "The noun immediately after the modifier must be the thing covered by frost."),
      choice("the morning sun made the leaves sparkle.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The noun immediately after the modifier must be the thing covered by frost.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-02",
    passage: "After examining the original maps, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("new questions about the expedition emerged.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the historian revised her account of the route.", "The historian is the person who examined the maps."),
      choice("the route seemed less certain.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("a revised account was prepared.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The historian is the person who examined the maps.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-03",
    passage: "Painted with broad blue strokes, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the mural dominates the entrance hall.", "The mural is what was painted with broad blue strokes."),
      choice("visitors notice the mural immediately.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the entrance hall appears brighter.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("attention is drawn to the mural.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The mural is what was painted with broad blue strokes.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-04",
    passage: "While waiting for the interview to begin, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the consent form was reviewed.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the interview room remained quiet.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there were several instructions on the table.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the participants reviewed the consent form.", "The participants are the people who were waiting."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The participants are the people who were waiting.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-05",
    passage: "Using a high-resolution scanner, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the sample revealed tiny fractures.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there were tiny fractures in the sample.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the researchers detected tiny fractures in the sample.", "The researchers are the users of the scanner."),
      choice("tiny fractures in the sample were detected.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The researchers are the users of the scanner.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-06",
    passage: "Designed to reduce processing delays, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("there is automatic routing in the new system.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the new application system routes forms automatically.", "The application system is what was designed to reduce delays."),
      choice("applicants can submit forms more quickly.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("forms are routed automatically by the new system.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The application system is what was designed to reduce delays.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-07",
    passage: "Walking through the deserted station, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the narrator notices the echo of every footstep.", "The narrator is the person walking through the station."),
      choice("every footstep produces an echo.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the station seems increasingly unfamiliar.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there are echoes throughout the station.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The narrator is the person walking through the station.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-08",
    passage: "After reviewing the revised sales figures, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the forecast was lowered.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("slower growth appeared likely.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the revised figures suggested weaker demand.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the analysts lowered their forecast.", "The analysts are the people who reviewed the figures."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The analysts are the people who reviewed the figures.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-09",
    passage: "Although initially dismissed as overly experimental, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the author's reputation grew rapidly.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there was later widespread praise for the novel.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the novel later became one of the author's most influential works.", "The novel is what was initially dismissed."),
      choice("critics later praised the novel.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The novel is what was initially dismissed.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-10",
    passage: "By comparing samples collected at four depths, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("there appeared to be a temperature gradient.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the research team identified a consistent temperature gradient.", "The research team performs the comparison."),
      choice("a consistent temperature gradient was identified.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the samples revealed a temperature gradient.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The research team performs the comparison.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-11",
    passage: "Having selected their own work schedules, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("the participants may have differed in motivation before the study began.", "The participants are the people who selected their schedules."),
      choice("motivation may have differed before the study.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the researchers could not eliminate every source of bias.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there may have been differences among the participants.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The participants are the people who selected their schedules.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-modifiers-12",
    passage: "Preserved in archives across three cities, _____",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("historians can consult the letters in several places.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the archives contain a complete record.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("there is an unusually complete documentary record.", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("the letters provide an unusually complete record of the expedition.", "The letters are what were preserved in the archives."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Modifiers",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The letters are what were preserved in the archives.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
];