import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const verbAgreementReplacementQuestions = [
  createExpansionQuestion({
    id: "repl2-agreement-01",
    passage: "The results of the second trial _____ consistent with the researchers' prediction.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("is", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("has been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were", "The plural subject \u201cresults\u201d requires the plural verb \u201cwere.\u201d"),
      choice("was", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The plural subject \u201cresults\u201d requires the plural verb \u201cwere.\u201d",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-02",
    passage: "A collection of ship logs _____ stored in the regional archive.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("have been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("is", "The singular head noun \u201ccollection\u201d controls the verb."),
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The singular head noun \u201ccollection\u201d controls the verb.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-03",
    passage: "The sketches and the finished painting _____ displayed side by side.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "The compound subject joined by \u201cand\u201d is plural."),
      choice("is", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("was", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("has been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The compound subject joined by \u201cand\u201d is plural.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-04",
    passage: "Each of the proposed changes _____ public comment.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("require", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have required", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were requiring", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("requires", "The subject \u201cEach\u201d is singular."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The subject \u201cEach\u201d is singular.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-05",
    passage: "Neither the batteries nor the control unit _____ operating at full capacity.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("was", "With \u201cneither...nor,\u201d the verb agrees with the nearer singular subject \u201cunit.\u201d"),
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "With \u201cneither...nor,\u201d the verb agrees with the nearer singular subject \u201cunit.\u201d",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-06",
    passage: "The number of small businesses using the program _____ increased since January.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("has", "The singular noun \u201cnumber\u201d is the subject."),
      choice("have", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The singular noun \u201cnumber\u201d is the subject.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-07",
    passage: "A series of follow-up interviews _____ scheduled for next month.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("is", "The singular noun \u201cseries\u201d takes a singular verb here."),
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The singular noun \u201cseries\u201d takes a singular verb here.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-08",
    passage: "The diary, together with two maps, _____ evidence of the expedition's route.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("provide", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have provided", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were providing", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("provides", "The parenthetical phrase does not change the singular subject \u201cdiary.\u201d"),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The parenthetical phrase does not change the singular subject \u201cdiary.\u201d",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-09",
    passage: "Neither the shift in temperature nor the changes in humidity _____ sufficient to explain the result.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("is", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("has been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were", "The nearer subject \u201cchanges\u201d is plural, so the verb must be plural."),
      choice("was", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The nearer subject \u201cchanges\u201d is plural, so the verb must be plural.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-10",
    passage: "What the committee considered most important _____ the accessibility of the records.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("was", "The subject is the singular noun clause beginning with \u201cWhat.\u201d"),
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The subject is the singular noun clause beginning with \u201cWhat.\u201d",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-11",
    passage: "More than one respondent _____ concern about the survey's wording.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("expressed", "The construction \u201cmore than one\u201d takes a singular verb in standard usage."),
      choice("express", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have expressed", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were expressing", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The construction \u201cmore than one\u201d takes a singular verb in standard usage.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "repl2-agreement-12",
    passage: "The extent to which the two methods differ _____ still uncertain.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("have been", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("were", "This choice creates a subject\u2013verb agreement error or leaves the modifier attached to the wrong noun."),
      choice("is", "The singular head noun \u201cextent\u201d controls the verb."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-9"],
    walkthrough: [
      "Identify the grammatical subject or the noun modified by the introductory phrase.",
      "The singular head noun \u201cextent\u201d controls the verb.",
      "Choose the option that creates a clear and grammatically complete sentence.",
    ],
  }),
];