import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const mainIdeaExpansion7Questions = [
  createExpansionQuestion({
    id: "rexp7-main-01",
    passage: "A city planted rows of trees along a busy avenue. Five years later, summer surface temperatures on the shaded sidewalks were lower than on nearby unshaded sidewalks.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Unshaded sidewalks receive less sunlight.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Street trees can reduce surface temperatures by providing shade.", "The passage connects tree planting with lower sidewalk temperatures."),
      choice("Busy avenues are always cooler than quiet streets.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Trees grow only in cities with hot summers.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Main Idea",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Identify the passage's broadest supported point.",
      "The passage connects tree planting with lower sidewalk temperatures.",
      "Reject choices that focus on a minor detail or introduce an unsupported claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-main-02",
    passage: "A former post office was converted into a community arts center. The renovation preserved the original service windows and reused them as ticket counters.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The building was adapted for a new use while retaining elements of its original design.", "The central idea combines adaptive reuse with preservation."),
      choice("The post office continued operating during the renovation.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Ticket counters are more important than art studios.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("The service windows were removed from the building.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Main Idea",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Identify the passage's broadest supported point.",
      "The central idea combines adaptive reuse with preservation.",
      "Reject choices that focus on a minor detail or introduce an unsupported claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-main-03",
    passage: "Students who received a checklist before beginning a long assignment completed more of the required steps than students who did not receive one.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The assignment became shorter after the checklist was introduced.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Students without checklists completed every step.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Checklists eliminated the need for instructions.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("A checklist helped students complete more parts of a complex assignment.", "The passage presents a positive effect of the checklist on task completion."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Main Idea",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Identify the passage's broadest supported point.",
      "The passage presents a positive effect of the checklist on task completion.",
      "Reject choices that focus on a minor detail or introduce an unsupported claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-main-04",
    passage: "A museum reorganized an exhibition by theme rather than by date. As a result, works produced decades apart appeared beside one another, encouraging visitors to compare how different artists addressed similar subjects.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Visitors preferred older works to newer ones.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("Artists from the same decade always used the same themes.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("A thematic arrangement encouraged comparisons among works from different periods.", "The central point is that thematic organization enables cross-period comparison."),
      choice("The museum removed all dates from the artworks.", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Main Idea",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Identify the passage's broadest supported point.",
      "The central point is that thematic organization enables cross-period comparison.",
      "Reject choices that focus on a minor detail or introduce an unsupported claim.",
    ],
  }),
];