import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const wordsInContextExpansion7Questions = [
  createExpansionQuestion({
    id: "rexp7-wic-01",
    passage: "The researchers used a transparent chamber so that they could observe the insects without disturbing them.",
    prompt: "As used in the text, what does \u201ctransparent\u201d most nearly mean?",
    choices: [
      choice("sealed", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("temporary", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("clear", "The chamber allows observation through it, so \u201ctransparent\u201d means clear."),
      choice("fragile", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Words in Context",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Substitute each answer choice into the sentence.",
      "The chamber allows observation through it, so \u201ctransparent\u201d means clear.",
      "Choose the meaning that fits the local context rather than the word's most familiar definition.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-wic-02",
    passage: "Although the official account was widely accepted, the newly discovered letters complicate that narrative by revealing disagreements among local leaders.",
    prompt: "As used in the text, what does \u201ccomplicate\u201d most nearly mean?",
    choices: [
      choice("publish publicly", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("make less straightforward", "The letters introduce conflicting evidence, making the accepted account less simple."),
      choice("confirm completely", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("shorten considerably", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Words in Context",
    domain: "Craft and Structure",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Substitute each answer choice into the sentence.",
      "The letters introduce conflicting evidence, making the accepted account less simple.",
      "Choose the meaning that fits the local context rather than the word's most familiar definition.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-wic-03",
    passage: "The reminders were designed to prompt participants to complete the survey before the deadline.",
    prompt: "As used in the text, what does \u201cprompt\u201d most nearly mean?",
    choices: [
      choice("encourage", "The reminders are intended to encourage action."),
      choice("question", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("delay", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("record", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Words in Context",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Substitute each answer choice into the sentence.",
      "The reminders are intended to encourage action.",
      "Choose the meaning that fits the local context rather than the word's most familiar definition.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-wic-04",
    passage: "The critic argues that the novel's final image reinforces the theme introduced in its opening chapter.",
    prompt: "As used in the text, what does \u201creinforces\u201d most nearly mean?",
    choices: [
      choice("contradicts", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("conceals", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("replaces", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("strengthens", "The final image supports and strengthens an existing theme."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Words in Context",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Substitute each answer choice into the sentence.",
      "The final image supports and strengthens an existing theme.",
      "Choose the meaning that fits the local context rather than the word's most familiar definition.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp7-wic-05",
    passage: "Because the policy affected only a narrow group of firms, the researchers cautioned against extrapolating the results to the entire industry.",
    prompt: "As used in the text, what does \u201cextrapolating\u201d most nearly mean?",
    choices: [
      choice("excluding firms from the analysis", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("repeating the same experiment", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
      choice("extending a conclusion beyond the observed group", "The warning concerns applying a limited result to a broader population."),
      choice("calculating the exact cost of the policy", "This choice does not match the word's meaning in context or does not state the passage's central idea."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Words in Context",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 75,
    tags: ["reading-expansion-pack-7", "final-gap-closure"],
    walkthrough: [
      "Substitute each answer choice into the sentence.",
      "The warning concerns applying a limited result to a broader population.",
      "Choose the meaning that fits the local context rather than the word's most familiar definition.",
    ],
  }),
];