import type { ExamQuestion, ExamDifficulty } from "./types";

type PassageRecord = { title:string; genre:string; difficulty:ExamDifficulty; text:string; claim:string; inference:string; purpose:string; };

const records: PassageRecord[] = [
  { title:`Urban ecology`, genre:`Science`, difficulty:`Medium`, text:`Researchers studying rooftop gardens found that plots planted with several native species attracted more pollinators than plots planted with a single ornamental species. Because all plots received the same amount of water, the researchers concluded that plant diversity—not irrigation—best explained the difference.`, claim:`Native plant diversity can increase pollinator activity in rooftop gardens.`, inference:`The controlled watering strengthens the claim that plant diversity caused the observed difference.`, purpose:`to explain how a controlled comparison supports a causal conclusion` },
  { title:`Sleep and memory`, genre:`Science`, difficulty:`Easy`, text:`In a study of memory, participants who slept after learning a list recalled more items the next day than participants who remained awake for the same number of hours. The researchers noted, however, that the groups differed slightly in age.`, claim:`Sleep may support memory retention, though the age difference limits certainty.`, inference:`The age difference is a possible alternative explanation for part of the result.`, purpose:`to report a finding while acknowledging a limitation` },
  { title:`Coral restoration`, genre:`Science`, difficulty:`Hard`, text:`Marine biologists transplanted fragments from heat-tolerant corals to damaged reefs. Survival improved during a mild warming event, but the researchers cautioned that tolerance to one event does not guarantee resilience during repeated or more intense warming.`, claim:`Heat-tolerant coral fragments may aid restoration, but their long-term resilience remains uncertain.`, inference:`The researchers would likely support longer studies involving repeated warming events.`, purpose:`to qualify a promising result by identifying what remains unknown` },
  { title:`Bird migration`, genre:`Science`, difficulty:`Medium`, text:`Tracking data showed that some migratory birds departed earlier in warmer springs. Yet arrival dates at northern breeding grounds changed little because birds paused longer at intermediate stopover sites.`, claim:`Earlier departure did not necessarily produce earlier arrival because stopover behavior also changed.`, inference:`Migration timing depends on decisions made throughout the route, not only at departure.`, purpose:`to show why one measured change did not lead to an expected outcome` },
  { title:`Battery materials`, genre:`Science`, difficulty:`Hard`, text:`A new battery electrode stored more energy than a conventional electrode during its first fifty cycles. After two hundred cycles, however, its capacity declined more sharply. Engineers therefore described the design as promising for short-term applications but unsuitable for devices requiring long service life.`, claim:`The new electrode offers an early performance advantage but loses durability over time.`, inference:`The engineers value long-term capacity retention when judging suitability for durable devices.`, purpose:`to compare short-term benefits with long-term limitations` },
  { title:`Language learning`, genre:`Social Science`, difficulty:`Easy`, text:`Students who practiced new words in several short sessions remembered more of them than students who spent the same total time in one session. The result supports the idea that spacing practice can improve retention.`, claim:`Spreading practice across sessions can improve vocabulary retention.`, inference:`How practice time is distributed can matter even when total study time is unchanged.`, purpose:`to present evidence for a particular study strategy` },
  { title:`Public transit`, genre:`Social Science`, difficulty:`Medium`, text:`After a city added frequent bus service on two major routes, ridership increased most in neighborhoods where stops were already within walking distance of many homes. In areas with sparse stops, the increase was modest.`, claim:`Service frequency increased ridership most where routes were also physically accessible.`, inference:`Frequency alone may not substantially increase ridership when stops are difficult to reach.`, purpose:`to identify a condition that shaped the effect of a policy change` },
  { title:`Museum labels`, genre:`Humanities`, difficulty:`Hard`, text:`Visitors spent more time with artworks when labels posed an open question rather than supplying a single interpretation. Interviews suggested that the questions encouraged viewers to compare the label with details they noticed themselves.`, claim:`Open-ended labels may deepen engagement by inviting visitors to form interpretations.`, inference:`Some visitors value opportunities to test their own observations against curatorial guidance.`, purpose:`to explain a mechanism behind a change in visitor behavior` },
  { title:`Ancient trade`, genre:`History`, difficulty:`Medium`, text:`Chemical analysis of glass beads found at an inland settlement revealed minerals associated with a distant coastal region. The finding does not prove that merchants traveled the entire distance themselves, but it does indicate that the settlement participated in a broad exchange network.`, claim:`The beads provide evidence that the settlement was connected to long-distance trade.`, inference:`Goods may have passed through several intermediaries before reaching the settlement.`, purpose:`to draw a cautious historical conclusion from material evidence` },
  { title:`Diary chronology`, genre:`History`, difficulty:`Hard`, text:`A newly discovered diary records a council meeting three days earlier than official minutes indicate. Historians do not regard the discrepancy as proof that the minutes were falsified; instead, they suggest that the diary writer may have used the date on which discussion began rather than the date of the formal vote.`, claim:`The diary complicates the chronology but does not necessarily discredit the official record.`, inference:`Different documents may assign dates according to different stages of the same event.`, purpose:`to reconcile apparently conflicting historical sources` },
  { title:`Voting reform`, genre:`Government`, difficulty:`Medium`, text:`A reform allowing residents to register on election day increased registration, but turnout rose mainly among people who had recently moved. Researchers concluded that the reform reduced a specific administrative barrier rather than creating broad new interest in voting.`, claim:`Election-day registration chiefly helped voters facing recent-address barriers.`, inference:`The reform affected participation unevenly across groups.`, purpose:`to distinguish removal of an obstacle from creation of political motivation` },
  { title:`Price signals`, genre:`Economics`, difficulty:`Easy`, text:`When the price of reusable containers fell, more restaurants adopted them. Adoption rose fastest among restaurants that already had washing equipment, suggesting that the price change mattered most when other necessary infrastructure was present.`, claim:`Lower prices encouraged adoption, especially where supporting equipment already existed.`, inference:`The cost of one item may have limited impact when complementary resources are absent.`, purpose:`to explain why a price change had different effects across businesses` },
  { title:`Remote work`, genre:`Economics`, difficulty:`Hard`, text:`A firm reported higher output after allowing remote work, but the policy began during a period when demand for its services also rose. Because output might have increased even without the policy, analysts warned against attributing the entire gain to remote work.`, claim:`The evidence does not isolate remote work as the sole cause of higher output.`, inference:`A comparison with similar firms that did not adopt remote work would strengthen the analysis.`, purpose:`to identify a confounding factor in a causal claim` },
  { title:`Narrative distance`, genre:`Literature`, difficulty:`Medium`, text:`The narrator first describes the town from a distant hill, reducing its streets to a pattern of lights. The next paragraph shifts to a child listening behind one particular door. The movement from panorama to close detail links the town’s public appearance with a private moment.`, claim:`The shift in scale connects a broad setting to an individual experience.`, inference:`The doorway serves as a transition from public description to private experience.`, purpose:`to analyze how a change in narrative perspective creates meaning` },
  { title:`Unreliable memory`, genre:`Literature`, difficulty:`Hard`, text:`The speaker insists that she remembers every detail of the journey, yet she repeatedly revises the color of the train and the order of the stations. These corrections do not merely add realism; they invite readers to question the certainty of her larger claims.`, claim:`The speaker’s changing details make her account seem unreliable.`, inference:`Minor inconsistencies can shape how readers judge broader assertions.`, purpose:`to explain how repeated revisions affect the narrator’s credibility` },
  { title:`Poetic repetition`, genre:`Literature`, difficulty:`Easy`, text:`At the end of each stanza, the poem repeats the phrase “still the river moves.” Although the surrounding images shift from winter to spring, the repeated line emphasizes continuity beneath seasonal change.`, claim:`The repeated line highlights persistence despite changing conditions.`, inference:`The river functions as an image of continuity.`, purpose:`to explain the effect of a repeated phrase` },
  { title:`Scientific models`, genre:`Science`, difficulty:`Hard`, text:`Model A reproduced past temperature patterns more accurately than Model B, but Model B better predicted results from a later experiment. The researchers therefore rejected the idea that a model should be judged by a single measure of success.`, claim:`Different measures can lead to different judgments about model quality.`, inference:`Predictive performance on new data may reveal strengths not visible in historical fit.`, purpose:`to challenge a one-dimensional standard for evaluating models` },
  { title:`Forest recovery`, genre:`Science`, difficulty:`Medium`, text:`Ten years after a fire, tree cover had returned to most of the study area, but the mix of species differed from the prefire forest. The researchers described the site as structurally recovered but not ecologically identical to its earlier state.`, claim:`Recovery in overall tree cover did not restore the original species composition.`, inference:`Ecological recovery can be evaluated using more than one criterion.`, purpose:`to distinguish two meanings of recovery` },
  { title:`Archaeological absence`, genre:`History`, difficulty:`Hard`, text:`No imported pottery was found in the earliest layer of the site. Archaeologists cautioned that this absence may reflect limited excavation rather than true isolation, since only a small portion of the layer has been uncovered.`, claim:`The lack of imported pottery is not yet strong evidence that the site was isolated.`, inference:`Further excavation could change the interpretation of the earliest layer.`, purpose:`to explain why negative evidence should be treated cautiously` },
  { title:`School schedule`, genre:`Social Science`, difficulty:`Medium`, text:`A district moved the start of the school day later. Average attendance improved, but the largest gains occurred during winter months, when students previously traveled before sunrise.`, claim:`The later start time improved attendance especially under difficult winter travel conditions.`, inference:`Seasonal conditions influenced the size of the policy’s effect.`, purpose:`to show that a policy’s effect varied by context` },
  { title:`Bilingual signs`, genre:`Social Science`, difficulty:`Easy`, text:`Visitors navigated a transit station more quickly after bilingual signs were installed. The improvement was largest for first-time visitors, while regular commuters showed little change.`, claim:`Bilingual signs mainly benefited travelers unfamiliar with the station.`, inference:`Experience with the station reduced the need for additional guidance.`, purpose:`to compare how two groups responded to a design change` },
  { title:`Open data`, genre:`Government`, difficulty:`Hard`, text:`A city published detailed spending data online. Journalists used the data extensively, but most residents did not visit the portal. Officials concluded that transparency had increased even though direct public use remained limited, because intermediaries translated the data into reports.`, claim:`Open data can increase transparency through intermediaries even when few residents use the portal directly.`, inference:`Public impact need not depend on every resident consulting raw data.`, purpose:`to broaden the meaning of public access` },
  { title:`Historical monument`, genre:`Humanities`, difficulty:`Medium`, text:`A monument erected in 1910 depicts an event from 1775. A historian argues that the monument reveals as much about the values of 1910 as about the event it commemorates, since its design reflects debates occurring when it was built.`, claim:`The monument is evidence about both the commemorated event and the era of its construction.`, inference:`Commemorations can reflect later political concerns.`, purpose:`to explain why an artifact may illuminate two historical periods` },
  { title:`Algorithmic fairness`, genre:`Social Science`, difficulty:`Hard`, text:`An algorithm produced equal overall accuracy for two groups, but its errors differed: it generated more false positives for one group and more false negatives for the other. Researchers argued that equal accuracy alone was insufficient evidence of fairness.`, claim:`Equal overall accuracy can conceal unequal patterns of error.`, inference:`Evaluating fairness requires examining the kinds of mistakes a system makes.`, purpose:`to show why an aggregate measure can be misleading` },
];


const rotate = <T,>(items:T[], shift:number) => items.map((_,i)=>items[(i+shift)%items.length]);
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const choice=(text:string, rationale:string)=>({text,rationale});

function mainIdeaQuestion(record:PassageRecord,index:number):ExamQuestion{
  const correct=record.claim;
  const distractors=[
    `The passage argues that ${record.genre.toLowerCase()} research can never support a reliable conclusion.`,
    `The passage focuses mainly on a minor procedural detail rather than the broader finding.`,
    `The passage presents the evidence as proving a broader claim than the text actually supports.`,
  ];
  const shift=index%4, ordered=rotate([correct,...distractors],shift), answer=ordered.indexOf(correct);
  return {id:`rw2-main-${index}`,examId:`rw2-main-${index}`,section:"Reading & Writing",courseId:"reading-v2-main-idea",courseTitle:`Reading Engine 2.0 · ${record.genre}`,difficulty:record.difficulty,skill:"Main Idea",domain:"Information and Ideas",passageType:record.genre,passage:record.text,prompt:"Which choice best states the main idea of the text?",choices:ordered.map((text,i)=>choice(text,i===answer?`The text directly supports this central claim: ${record.claim}`:"This choice is too broad, too narrow, or inconsistent with a qualification in the text.")),answer};
}

function reasoningQuestion(record:PassageRecord,index:number):ExamQuestion{
  const usePurpose=index%2===0;
  const correct=usePurpose?record.purpose:record.inference;
  const distractors=usePurpose?[
    "to dismiss the evidence because it does not establish absolute certainty",
    "to provide background information unrelated to the conclusion",
    "to argue that the observed result applies without qualification in every context",
  ]:[
    "The evidence eliminates every alternative explanation for the result.",
    "The author would reject any need for additional evidence.",
    "The finding necessarily applies to all populations and settings.",
  ];
  const shift=(index+1)%4, ordered=rotate([correct,...distractors],shift), answer=ordered.indexOf(correct);
  return {id:`rw2-reason-${index}`,examId:`rw2-reason-${index}`,section:"Reading & Writing",courseId:usePurpose?"reading-v2-purpose":"reading-v2-inference",courseTitle:`Reading Engine 2.0 · ${record.genre}`,difficulty:record.difficulty,skill:usePurpose?"Author's Purpose":"Inference",domain:usePurpose?"Craft and Structure":"Information and Ideas",passageType:record.genre,passage:record.text,prompt:usePurpose?"Which choice best describes the function of the text as a whole?":"Which choice is most strongly supported by the text?",choices:ordered.map((text,i)=>choice(text,i===answer?`This follows from the text's reasoning: ${correct}`:"This choice overstates, contradicts, or is not established by the text.")),answer};
}

export const readingBankV2:ExamQuestion[]=records.flatMap((record,index)=>[
  mainIdeaQuestion(record,index),
  reasoningQuestion(record,index),
]);

const contextItems = [
  ["The committee called the estimate tentative because several measurements still had to be verified.","tentative","provisional rather than final",["deliberately misleading","unusually detailed","widely celebrated"]],
  ["The second experiment corroborated the first by producing nearly identical results.","corroborated","confirmed with additional evidence",["replaced without explanation","made less precise","contradicted completely"]],
  ["The policy was intended to mitigate traffic congestion, not eliminate every delay.","mitigate","make less severe",["measure exactly","cause unexpectedly","describe neutrally"]],
  ["Because the sample was small, the researchers were cautious about extrapolating the result to the entire population.","extrapolating","extending a conclusion beyond the observed data",["recording a result twice","removing an outlier","calculating an average"]],
  ["The historian qualified her claim by noting that the surviving records represent only one region.","qualified","limited or made less absolute",["proved beyond doubt","repeated word for word","translated into another language"]],
  ["The new evidence does not refute the earlier theory, but it does reveal one of the theory's limits.","refute","show to be false",["summarize briefly","support indirectly","make more popular"]],
  ["The difference was subtle but consequential: it changed how the entire dataset was interpreted.","consequential","important because of its effects",["easy to overlook and irrelevant","arranged in sequence","based only on tradition"]],
  ["The apparent agreement was superficial; the two authors relied on fundamentally different assumptions.","superficial","existing only at the surface level",["carefully reasoned","historically accurate","mutually beneficial"]],
  ["The editor deleted redundant phrases to make the paragraph more concise.","concise","brief while retaining necessary meaning",["emotionally forceful","technically uncertain","deliberately repetitive"]],
  ["The evidence for the claim remained equivocal because two equally plausible explanations fit the data.","equivocal","open to more than one interpretation",["decisive and complete","unrelated to the issue","based on fabrication"]],
  ["The discovery precipitated a new investigation that began only days later.","precipitated","caused to happen suddenly",["prevented permanently","described inaccurately","postponed gradually"]],
  ["The researchers scrutinized the unusual measurement before including it in the analysis.","scrutinized","examined very closely",["ignored as irrelevant","copied without checking","announced publicly"]],
  ["The evidence was robust: the pattern appeared across several methods and independent samples.","robust","strong and reliable",["temporary and accidental","narrowly defined","difficult to explain"]],
  ["The speaker conceded that the opposing argument identified a genuine weakness in the proposal.","conceded","acknowledged as true",["dismissed without consideration","rephrased for clarity","predicted in advance"]],
  ["The survey question was ambiguous, so respondents may have interpreted it in different ways.","ambiguous","having more than one possible meaning",["offensive in tone","supported by data","limited in length"]],
  ["The additional examples bolster the author's claim by showing that the pattern is not isolated.","bolster","strengthen or support",["narrow dramatically","replace entirely","question indirectly"]],
  ["The explanation is plausible, but the available evidence does not yet establish that it is correct.","plausible","seemingly reasonable",["impossible to test","certainly false","unnecessarily complex"]],
  ["The distinction is nuanced: both policies reduce costs, but they distribute the savings differently.","nuanced","involving subtle distinctions",["completely obvious","based on error","unrelated to context"]],
  ["The pilot program proved viable after it met its goals without exceeding its budget.","viable","capable of working successfully",["morally questionable","historically unusual","difficult to describe"]],
  ["The report substantiates its conclusion with records from three independent archives.","substantiates","supports with evidence",["weakens through repetition","hides from review","replaces with speculation"]],
] as const;

export const wordsInContextV2:ExamQuestion[]=contextItems.map((item,index)=>{
 const [sentence,word,meaning,distractors]=item; const difficulty:ExamDifficulty=index%3===0?"Easy":index%3===1?"Medium":"Hard";
 const shift=(index+2)%4; const ordered=rotate([meaning,...distractors],shift); const answer=ordered.indexOf(meaning);
 return {id:`rw2-context-${index}`,examId:`rw2-context-${index}`,section:"Reading & Writing",courseId:"reading-v2-words-in-context",courseTitle:"Reading Engine 2.0 · Words in Context",difficulty,skill:"Words in Context",domain:"Craft and Structure",passageType:"Academic",passage:sentence,prompt:`As used in the text, “${word}” most nearly means`,choices:ordered.map((text,i)=>choice(text,i===answer?`In this sentence, “${word}” means ${meaning}.`:"This meaning does not fit the logical role of the word in the sentence.")),answer};
});
