import type { ExamQuestion } from "./types";

type VocabularyEntry = {
  id: string;
  difficulty: "Easy" | "Medium" | "Hard";
  word: string;
  passage: string;
  prompt: string;
  choices: string[];
  answer: number;
};

const entries: VocabularyEntry[] = [
  {
    id: "vocab-exp2-01",
    difficulty: "Easy",
    word: "abundant",
    passage: "After several wet seasons, groundwater was once again ____ enough to support both farms and nearby towns.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["scarce", "abundant", "uncertain", "contaminated"],
    answer: 1,
  },
  {
    id: "vocab-exp2-02",
    difficulty: "Easy",
    word: "adapt",
    passage: "To survive in colder climates, the plant must ____ by developing thicker leaves and a shorter growing cycle.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["retreat", "adapt", "decline", "hesitate"],
    answer: 1,
  },
  {
    id: "vocab-exp2-03",
    difficulty: "Easy",
    word: "apparent",
    passage: "The pattern was not obvious at first, but it became ____ after the data were arranged chronologically.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["apparent", "temporary", "irrelevant", "arbitrary"],
    answer: 0,
  },
  {
    id: "vocab-exp2-04",
    difficulty: "Easy",
    word: "beneficial",
    passage: "Regular maintenance proved ____ because it prevented minor defects from becoming costly failures.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["beneficial", "avoidable", "random", "limited"],
    answer: 0,
  },
  {
    id: "vocab-exp2-05",
    difficulty: "Easy",
    word: "clarify",
    passage: "The author added a diagram to ____ how the machine’s internal parts interact.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["complicate", "clarify", "challenge", "conceal"],
    answer: 1,
  },
  {
    id: "vocab-exp2-06",
    difficulty: "Easy",
    word: "decline",
    passage: "Attendance began to ____ after the museum shortened its weekend hours.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["decline", "stabilize", "expand", "converge"],
    answer: 0,
  },
  {
    id: "vocab-exp2-07",
    difficulty: "Easy",
    word: "emerge",
    passage: "As more documents were examined, a consistent explanation began to ____ from the evidence.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["vanish", "emerge", "weaken", "pause"],
    answer: 1,
  },
  {
    id: "vocab-exp2-08",
    difficulty: "Easy",
    word: "explicit",
    passage: "The contract is ____ about the deadline, stating that all materials must arrive by June 1.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["flexible", "implicit", "explicit", "tentative"],
    answer: 2,
  },
  {
    id: "vocab-exp2-09",
    difficulty: "Easy",
    word: "maintain",
    passage: "The laboratory must ____ a constant temperature so that the samples remain stable.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["maintain", "measure", "reduce", "question"],
    answer: 0,
  },
  {
    id: "vocab-exp2-10",
    difficulty: "Easy",
    word: "notable",
    passage: "One ____ feature of the new bridge is its unusually low use of concrete.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["notable", "ordinary", "temporary", "uncertain"],
    answer: 0,
  },
  {
    id: "vocab-exp2-11",
    difficulty: "Easy",
    word: "predict",
    passage: "Using the earlier measurements, the model can ____ how quickly the river level will rise.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conceal", "predict", "prevent", "record"],
    answer: 1,
  },
  {
    id: "vocab-exp2-12",
    difficulty: "Easy",
    word: "retain",
    passage: "The revised design allows the building to ____ heat during winter while remaining cool in summer.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["retain", "release", "ignore", "estimate"],
    answer: 0,
  },
  {
    id: "vocab-exp2-13",
    difficulty: "Medium",
    word: "ambivalent",
    passage: "The critic was ____ about the novel: she admired its style but questioned its conclusion.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["enthusiastic", "ambivalent", "indifferent", "certain"],
    answer: 1,
  },
  {
    id: "vocab-exp2-14",
    difficulty: "Medium",
    word: "constrain",
    passage: "Limited funding may ____ the number of sites the research team can examine.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["constrain", "expand", "verify", "transform"],
    answer: 0,
  },
  {
    id: "vocab-exp2-15",
    difficulty: "Medium",
    word: "derive",
    passage: "Researchers can ____ an estimate of the planet’s mass from its effect on nearby objects.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["derive", "dismiss", "obscure", "reverse"],
    answer: 0,
  },
  {
    id: "vocab-exp2-16",
    difficulty: "Medium",
    word: "diminish",
    passage: "The treatment did not eliminate the symptoms, but it did ____ their severity.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["intensify", "diminish", "document", "predict"],
    answer: 1,
  },
  {
    id: "vocab-exp2-17",
    difficulty: "Medium",
    word: "distort",
    passage: "A poorly chosen scale can ____ the visual impression created by a graph.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["clarify", "distort", "confirm", "stabilize"],
    answer: 1,
  },
  {
    id: "vocab-exp2-18",
    difficulty: "Medium",
    word: "elicit",
    passage: "The interviewer used open-ended questions to ____ detailed responses from participants.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["suppress", "elicit", "summarize", "replace"],
    answer: 1,
  },
  {
    id: "vocab-exp2-19",
    difficulty: "Medium",
    word: "feasible",
    passage: "The proposal is scientifically sound, but engineers must determine whether it is economically ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["feasible", "arbitrary", "preliminary", "pervasive"],
    answer: 0,
  },
  {
    id: "vocab-exp2-20",
    difficulty: "Medium",
    word: "impartial",
    passage: "To ensure a fair competition, the judges were selected for their ability to remain ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["impartial", "skeptical", "innovative", "reluctant"],
    answer: 0,
  },
  {
    id: "vocab-exp2-21",
    difficulty: "Medium",
    word: "offset",
    passage: "The energy savings may ____ the higher initial cost of the equipment within five years.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["increase", "offset", "conceal", "measure"],
    answer: 1,
  },
  {
    id: "vocab-exp2-22",
    difficulty: "Medium",
    word: "persistent",
    passage: "Despite repeated repairs, a ____ leak continued to damage the building’s foundation.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["marginal", "persistent", "temporary", "beneficial"],
    answer: 1,
  },
  {
    id: "vocab-exp2-23",
    difficulty: "Medium",
    word: "refine",
    passage: "After the pilot study, the researchers used participant feedback to ____ the survey questions.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["refine", "discard", "generalize", "contradict"],
    answer: 0,
  },
  {
    id: "vocab-exp2-24",
    difficulty: "Medium",
    word: "sustain",
    passage: "The small reserve cannot ____ the growing population indefinitely without additional resources.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["sustain", "isolate", "predict", "distort"],
    answer: 0,
  },
  {
    id: "vocab-exp2-25",
    difficulty: "Hard",
    word: "anomalous",
    passage: "The unusually high reading was treated as ____ because it differed sharply from every other measurement.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["representative", "anomalous", "predictable", "coherent"],
    answer: 1,
  },
  {
    id: "vocab-exp2-26",
    difficulty: "Hard",
    word: "concede",
    passage: "Although the historian defended her interpretation, she did ____ that the new letter weakened one part of her argument.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["concede", "deny", "substantiate", "eliminate"],
    answer: 0,
  },
  {
    id: "vocab-exp2-27",
    difficulty: "Hard",
    word: "defer",
    passage: "Because the evidence was incomplete, the committee chose to ____ its decision until the next meeting.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["accelerate", "defer", "publicize", "reverse"],
    answer: 1,
  },
  {
    id: "vocab-exp2-28",
    difficulty: "Hard",
    word: "equivocal",
    passage: "The witness’s response was ____: it could be interpreted as either agreement or hesitation.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["explicit", "equivocal", "comprehensive", "objective"],
    answer: 1,
  },
  {
    id: "vocab-exp2-29",
    difficulty: "Hard",
    word: "inadvertent",
    passage: "The omission was ____ rather than deliberate; the editor had accidentally skipped a page.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["strategic", "inadvertent", "systematic", "inevitable"],
    answer: 1,
  },
  {
    id: "vocab-exp2-30",
    difficulty: "Hard",
    word: "mitigate",
    passage: "Planting trees along city streets can help ____ extreme summer temperatures by increasing shade.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["exacerbate", "mitigate", "quantify", "replicate"],
    answer: 1,
  },
  {
    id: "vocab-exp2-31",
    difficulty: "Hard",
    word: "obsolete",
    passage: "Once digital sensors became standard, the older mechanical device was largely ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["innovative", "obsolete", "viable", "preliminary"],
    answer: 1,
  },
  {
    id: "vocab-exp2-32",
    difficulty: "Hard",
    word: "qualify",
    passage: "The researcher used the phrase “in this sample” to ____ the claim and avoid implying that it applied universally.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["strengthen absolutely", "qualify", "contradict", "repeat"],
    answer: 1,
  },
  {
    id: "vocab-exp2-33",
    difficulty: "Hard",
    word: "relegate",
    passage: "The discovery may ____ the earlier theory to a minor role rather than eliminate it entirely.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["elevate", "relegate", "corroborate", "clarify"],
    answer: 1,
  },
  {
    id: "vocab-exp2-34",
    difficulty: "Hard",
    word: "salient",
    passage: "Among the many details in the report, the most ____ was the sudden decline in operating costs.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["salient", "peripheral", "tentative", "arbitrary"],
    answer: 0,
  },
  {
    id: "vocab-exp2-35",
    difficulty: "Hard",
    word: "transient",
    passage: "The improvement proved ____: performance rose briefly, then returned to its previous level.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["permanent", "transient", "robust", "comprehensive"],
    answer: 1,
  },
  {
    id: "vocab-exp2-36",
    difficulty: "Hard",
    word: "validate",
    passage: "Replicating the experiment with a larger sample could help ____ the original findings.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["undermine", "validate", "distort", "defer"],
    answer: 1,
  },
];

export const vocabularyExpansionPack2: ExamQuestion[] = entries.map((entry) => ({
  id: entry.id,
  examId: entry.id,
  section: "Reading & Writing",
  courseId: "vocabulary-expansion-pack-2",
  courseTitle: "Vocabulary · Words in Context",
  difficulty: entry.difficulty,
  domain: "Craft and Structure",
  skill: "Words in Context",
  questionType: "multiple-choice",
  passage: entry.passage,
  prompt: entry.prompt,
  choices: entry.choices.map((text, index) => ({
    text,
    rationale:
      index === entry.answer
        ? `"${entry.word}" best matches the logical relationship and precise meaning established by the passage.`
        : "This option is grammatically possible but does not match the passage's meaning as precisely as the correct answer.",
  })),
  answer: entry.answer,
  walkthrough: [
    "Use the surrounding details to determine the direction and degree of meaning required by the blank.",
    `The context calls for the meaning expressed by "${entry.word}".`,
    `"${entry.word}" is the most precise completion; the distractors conflict with the passage's logic or emphasis.`,
  ],
  estimatedTime: 75,
  tags: [
    "vocabulary",
    "words-in-context",
    "vocabulary-expansion-pack-2",
    entry.difficulty,
    entry.word,
  ],
}));
