import type { ExamQuestion } from "./types";

type Entry = {
  id: string;
  difficulty: "Easy" | "Medium" | "Hard";
  word: string;
  passage: string;
  prompt: string;
  choices: string[];
  answer: number;
};

const entries: Entry[] = [
  {
    id: "vocab-exp1-01",
    difficulty: "Easy",
    word: "advocate",
    passage: "Several public-health researchers ____ expanding access to preventive screenings because early detection can reduce treatment costs.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["advocate", "temporary", "conventional", "obscure"],
    answer: 0,
  },
  {
    id: "vocab-exp1-02",
    difficulty: "Easy",
    word: "allocate",
    passage: "The city council voted to ____ additional funds to repair aging bridges before winter.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "temporary", "allocate"],
    answer: 3,
  },
  {
    id: "vocab-exp1-03",
    difficulty: "Easy",
    word: "coherent",
    passage: "Although the report contained many details, its central argument remained ____ because each section clearly supported the same conclusion.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "coherent", "obscure"],
    answer: 2,
  },
  {
    id: "vocab-exp1-04",
    difficulty: "Easy",
    word: "convey",
    passage: "The graph uses a steep upward line to ____ how rapidly enrollment increased after the new program began.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "convey", "temporary", "conventional"],
    answer: 1,
  },
  {
    id: "vocab-exp1-05",
    difficulty: "Easy",
    word: "credible",
    passage: "Because the witness’s account matched the security footage and phone records, investigators considered it highly ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["credible", "conventional", "obscure", "temporary"],
    answer: 0,
  },
  {
    id: "vocab-exp1-06",
    difficulty: "Easy",
    word: "fundamental",
    passage: "Access to clean water is a ____ requirement for public health; without it, many other interventions are ineffective.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "conventional", "fundamental"],
    answer: 3,
  },
  {
    id: "vocab-exp1-07",
    difficulty: "Easy",
    word: "innovative",
    passage: "The engineer’s ____ design used recycled materials in a way no previous model had attempted.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "innovative", "temporary"],
    answer: 2,
  },
  {
    id: "vocab-exp1-08",
    difficulty: "Easy",
    word: "objective",
    passage: "To remain ____, the review panel evaluated every proposal using the same published criteria.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "objective", "conventional", "obscure"],
    answer: 1,
  },
  {
    id: "vocab-exp1-09",
    difficulty: "Easy",
    word: "preliminary",
    passage: "The team emphasized that its findings were ____ and could change after additional data were collected.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["preliminary", "obscure", "temporary", "conventional"],
    answer: 0,
  },
  {
    id: "vocab-exp1-10",
    difficulty: "Easy",
    word: "scarce",
    passage: "During the drought, fresh water became increasingly ____, forcing residents to reduce household use.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "obscure", "scarce"],
    answer: 3,
  },
  {
    id: "vocab-exp1-11",
    difficulty: "Easy",
    word: "transform",
    passage: "The new rail line could ____ the neighborhood by reducing travel times and attracting businesses.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "transform", "conventional"],
    answer: 2,
  },
  {
    id: "vocab-exp1-12",
    difficulty: "Easy",
    word: "reluctant",
    passage: "Although the evidence was strong, the committee was ____ to approve the policy before hearing from affected residents.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "reluctant", "obscure", "temporary"],
    answer: 1,
  },
  {
    id: "vocab-exp1-13",
    difficulty: "Medium",
    word: "arbitrary",
    passage: "The editor rejected the article without citing any standard or factual problem, so the author viewed the decision as ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["arbitrary", "temporary", "conventional", "obscure"],
    answer: 0,
  },
  {
    id: "vocab-exp1-14",
    difficulty: "Medium",
    word: "compelling",
    passage: "The archaeologist’s interpretation was especially ____ because it accounted for both the newly discovered tools and earlier dating results.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "temporary", "compelling"],
    answer: 3,
  },
  {
    id: "vocab-exp1-15",
    difficulty: "Medium",
    word: "discern",
    passage: "Because the manuscript was badly faded, scholars could barely ____ the name written in the margin.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "discern", "obscure"],
    answer: 2,
  },
  {
    id: "vocab-exp1-16",
    difficulty: "Medium",
    word: "facilitate",
    passage: "The revised database is intended to ____ collaboration by allowing researchers in different countries to update the same records.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "facilitate", "temporary", "conventional"],
    answer: 1,
  },
  {
    id: "vocab-exp1-17",
    difficulty: "Medium",
    word: "fluctuate",
    passage: "Daily temperatures in the desert can ____ sharply, rising above 35°C in the afternoon and falling near freezing at night.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["fluctuate", "conventional", "obscure", "temporary"],
    answer: 0,
  },
  {
    id: "vocab-exp1-18",
    difficulty: "Medium",
    word: "inhibit",
    passage: "Excessive noise can ____ concentration, making it difficult for students to complete complex tasks.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "conventional", "inhibit"],
    answer: 3,
  },
  {
    id: "vocab-exp1-19",
    difficulty: "Medium",
    word: "marginal",
    passage: "The second redesign produced only a ____ improvement in battery life—about two minutes per charge.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "marginal", "temporary"],
    answer: 2,
  },
  {
    id: "vocab-exp1-20",
    difficulty: "Medium",
    word: "pervasive",
    passage: "Smartphones are so ____ in modern life that many daily tasks now assume immediate internet access.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "pervasive", "conventional", "obscure"],
    answer: 1,
  },
  {
    id: "vocab-exp1-21",
    difficulty: "Medium",
    word: "reconcile",
    passage: "To ____ the two conflicting estimates, the analysts rechecked the assumptions used in each model.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["reconcile", "obscure", "temporary", "conventional"],
    answer: 0,
  },
  {
    id: "vocab-exp1-22",
    difficulty: "Medium",
    word: "reinforce",
    passage: "The second experiment helped ____ the original conclusion by producing nearly identical results.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "obscure", "reinforce"],
    answer: 3,
  },
  {
    id: "vocab-exp1-23",
    difficulty: "Medium",
    word: "skeptical",
    passage: "Given that the company had not released its data, many scientists remained ____ of its extraordinary claim.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "skeptical", "conventional"],
    answer: 2,
  },
  {
    id: "vocab-exp1-24",
    difficulty: "Medium",
    word: "robust",
    passage: "The model remained accurate even when the researchers changed several assumptions, suggesting that its conclusions were ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "robust", "obscure", "temporary"],
    answer: 1,
  },
  {
    id: "vocab-exp1-25",
    difficulty: "Hard",
    word: "comprehensive",
    passage: "The review was unusually ____, addressing not only the study’s methods and results but also its historical context and ethical implications.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["comprehensive", "temporary", "conventional", "obscure"],
    answer: 0,
  },
  {
    id: "vocab-exp1-26",
    difficulty: "Hard",
    word: "contradict",
    passage: "Far from confirming the earlier survey, the new data appear to ____ its central claim that demand has steadily increased.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "temporary", "contradict"],
    answer: 3,
  },
  {
    id: "vocab-exp1-27",
    difficulty: "Hard",
    word: "exacerbate",
    passage: "By reducing shade and increasing paved surfaces, rapid development may ____ the urban heat-island effect.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "exacerbate", "obscure"],
    answer: 2,
  },
  {
    id: "vocab-exp1-28",
    difficulty: "Hard",
    word: "implicit",
    passage: "The essay never directly states that the policy failed, but that judgment is ____ in its repeated references to unmet goals and wasted funds.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "implicit", "temporary", "conventional"],
    answer: 1,
  },
  {
    id: "vocab-exp1-29",
    difficulty: "Hard",
    word: "nuanced",
    passage: "Rather than portraying the reform as wholly successful or wholly disastrous, the historian offers a ____ account that distinguishes among regions and social groups.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["nuanced", "conventional", "obscure", "temporary"],
    answer: 0,
  },
  {
    id: "vocab-exp1-30",
    difficulty: "Hard",
    word: "plausible",
    passage: "Although the hypothesis remains unproven, it is ____ because it fits the observed pattern and is consistent with established theory.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "conventional", "plausible"],
    answer: 3,
  },
  {
    id: "vocab-exp1-31",
    difficulty: "Hard",
    word: "substantiate",
    passage: "The newly discovered letters may ____ the biographer’s claim by providing direct evidence that the two writers met in 1924.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "obscure", "substantiate", "temporary"],
    answer: 2,
  },
  {
    id: "vocab-exp1-32",
    difficulty: "Hard",
    word: "tentative",
    passage: "Because the sample was small and geographically narrow, the researchers presented their conclusion as ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "tentative", "conventional", "obscure"],
    answer: 1,
  },
  {
    id: "vocab-exp1-33",
    difficulty: "Hard",
    word: "undermine",
    passage: "If the calibration error is confirmed, it would ____ confidence in the experiment’s reported measurements.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["undermine", "obscure", "temporary", "conventional"],
    answer: 0,
  },
  {
    id: "vocab-exp1-34",
    difficulty: "Hard",
    word: "unprecedented",
    passage: "The storm produced rainfall totals with no known parallel in the region’s recorded history, making the event ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["temporary", "conventional", "obscure", "unprecedented"],
    answer: 3,
  },
  {
    id: "vocab-exp1-35",
    difficulty: "Hard",
    word: "viable",
    passage: "The proposal is technically ambitious, but lower material costs may make it financially ____ for smaller manufacturers.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["obscure", "temporary", "viable", "conventional"],
    answer: 2,
  },
  {
    id: "vocab-exp1-36",
    difficulty: "Hard",
    word: "corroborate",
    passage: "Independent satellite images could ____ the field team’s report that the glacier retreated several kilometers.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conventional", "corroborate", "obscure", "temporary"],
    answer: 1,
  },
];

export const vocabularyExpansionPack1: ExamQuestion[] = entries.map((entry) => ({
  id: entry.id,
  examId: entry.id,
  section: "Reading & Writing",
  courseId: "vocabulary-expansion-pack-1",
  courseTitle: "Vocabulary · Words in Context",
  difficulty: entry.difficulty,
  domain: "Craft and Structure",
  skill: "Words in Context",
  questionType: "multiple-choice",
  passage: entry.passage,
  prompt: entry.prompt,
  choices: entry.choices.map((text, index) => ({
    text,
    rationale: index === entry.answer
      ? `"${entry.word}" best matches the meaning established by the context.`
      : "This choice does not fit the context as precisely as the correct answer.",
  })),
  answer: entry.answer,
  walkthrough: [
    "Identify the logical relationship around the blank.",
    `The context requires the sense expressed by "${entry.word}".`,
    `"${entry.word}" is the most precise completion.`,
  ],
  estimatedTime: 75,
  tags: ["vocabulary", "words-in-context", "vocabulary-expansion-pack-1", entry.difficulty, entry.word],
}));
