import type { ExamQuestion } from "./types";

type VocabularyEntry = {
  id: string;
  difficulty: "Easy" | "Medium" | "Hard";
  word: string;
  passage: string;
  prompt: string;
  choices: string[];
  answer: number;
};

const entries: VocabularyEntry[] = [
  {
    id: "vocab-exp3-01",
    difficulty: "Easy",
    word: "accurate",
    passage: "Because the instrument had been carefully calibrated, its measurements were considered highly ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["approximate", "accurate", "temporary", "complex"],
    answer: 1,
  },
  {
    id: "vocab-exp3-02",
    difficulty: "Easy",
    word: "assist",
    passage: "Volunteers were recruited to ____ researchers with cataloging the newly discovered documents.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["delay", "assist", "question", "replace"],
    answer: 1,
  },
  {
    id: "vocab-exp3-03",
    difficulty: "Easy",
    word: "brief",
    passage: "The committee requested a ____ summary that presented the main findings in no more than two pages.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["brief", "uncertain", "technical", "controversial"],
    answer: 0,
  },
  {
    id: "vocab-exp3-04",
    difficulty: "Easy",
    word: "consistent",
    passage: "The results were ____ across all three trials, with nearly identical values each time.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["consistent", "random", "limited", "incomplete"],
    answer: 0,
  },
  {
    id: "vocab-exp3-05",
    difficulty: "Easy",
    word: "demonstrate",
    passage: "The experiment was designed to ____ how temperature affects the rate of the reaction.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["conceal", "demonstrate", "reduce", "predict"],
    answer: 1,
  },
  {
    id: "vocab-exp3-06",
    difficulty: "Easy",
    word: "efficient",
    passage: "The redesigned motor is more ____ because it produces the same output while using less energy.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["efficient", "fragile", "temporary", "conventional"],
    answer: 0,
  },
  {
    id: "vocab-exp3-07",
    difficulty: "Easy",
    word: "exclude",
    passage: "The researchers decided to ____ incomplete surveys from the final analysis.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["exclude", "combine", "repeat", "publish"],
    answer: 0,
  },
  {
    id: "vocab-exp3-08",
    difficulty: "Easy",
    word: "frequent",
    passage: "Because delays were so ____, passengers began choosing a different train line.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["minor", "frequent", "unexpected", "brief"],
    answer: 1,
  },
  {
    id: "vocab-exp3-09",
    difficulty: "Easy",
    word: "identify",
    passage: "The analysis helped scientists ____ the chemical responsible for the unusual color.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["identify", "remove", "estimate", "imitate"],
    answer: 0,
  },
  {
    id: "vocab-exp3-10",
    difficulty: "Easy",
    word: "reliable",
    passage: "The sensor proved ____ by producing stable readings under a wide range of conditions.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["reliable", "obsolete", "tentative", "arbitrary"],
    answer: 0,
  },
  {
    id: "vocab-exp3-11",
    difficulty: "Easy",
    word: "significant",
    passage: "The policy led to a ____ reduction in waste, cutting disposal volume by nearly half.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["significant", "marginal", "uncertain", "temporary"],
    answer: 0,
  },
  {
    id: "vocab-exp3-12",
    difficulty: "Easy",
    word: "verify",
    passage: "The team repeated the calculation to ____ that no arithmetic error had occurred.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["verify", "distort", "ignore", "generalize"],
    answer: 0,
  },
  {
    id: "vocab-exp3-13",
    difficulty: "Medium",
    word: "attribute",
    passage: "The authors ____ the decline in sales primarily to rising transportation costs.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["attribute", "conceal", "separate", "reverse"],
    answer: 0,
  },
  {
    id: "vocab-exp3-14",
    difficulty: "Medium",
    word: "bolster",
    passage: "Additional field observations would ____ the claim by providing evidence from another region.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["weaken", "bolster", "qualify", "delay"],
    answer: 1,
  },
  {
    id: "vocab-exp3-15",
    difficulty: "Medium",
    word: "cumulative",
    passage: "Although each annual increase was small, the ____ effect over a decade was substantial.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["isolated", "cumulative", "temporary", "arbitrary"],
    answer: 1,
  },
  {
    id: "vocab-exp3-16",
    difficulty: "Medium",
    word: "discrepancy",
    passage: "The auditors investigated the ____ between the amount recorded and the amount actually received.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["agreement", "discrepancy", "forecast", "benefit"],
    answer: 1,
  },
  {
    id: "vocab-exp3-17",
    difficulty: "Medium",
    word: "indicate",
    passage: "The darker areas on the map ____ regions with higher population density.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["indicate", "exclude", "mitigate", "distort"],
    answer: 0,
  },
  {
    id: "vocab-exp3-18",
    difficulty: "Medium",
    word: "inevitable",
    passage: "Given the approaching storm and the damaged roof, further leakage seemed ____.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["avoidable", "inevitable", "marginal", "ambiguous"],
    answer: 1,
  },
  {
    id: "vocab-exp3-19",
    difficulty: "Medium",
    word: "integrate",
    passage: "The updated curriculum aims to ____ laboratory work with classroom instruction.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["separate", "integrate", "simplify", "postpone"],
    answer: 1,
  },
  {
    id: "vocab-exp3-20",
    difficulty: "Medium",
    word: "modify",
    passage: "Engineers had to ____ the design after tests revealed excessive vibration.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["modify", "validate", "preserve", "document"],
    answer: 0,
  },
  {
    id: "vocab-exp3-21",
    difficulty: "Medium",
    word: "negligible",
    passage: "The second treatment produced a ____ change, too small to affect the study’s conclusion.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["substantial", "negligible", "unexpected", "persistent"],
    answer: 1,
  },
  {
    id: "vocab-exp3-22",
    difficulty: "Medium",
    word: "precede",
    passage: "A short introduction will ____ the main presentation and explain its goals.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["follow", "precede", "replace", "contradict"],
    answer: 1,
  },
  {
    id: "vocab-exp3-23",
    difficulty: "Medium",
    word: "simulate",
    passage: "The software can ____ hurricane conditions without exposing equipment to an actual storm.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["simulate", "eliminate", "measure", "qualify"],
    answer: 0,
  },
  {
    id: "vocab-exp3-24",
    difficulty: "Medium",
    word: "transparent",
    passage: "To build public trust, the agency made its review process more ____ by publishing the criteria and results.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["secretive", "transparent", "tentative", "subjective"],
    answer: 1,
  },
  {
    id: "vocab-exp3-25",
    difficulty: "Hard",
    word: "circumscribe",
    passage: "The agreement was designed to ____ the committee’s authority, limiting it to financial matters only.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["expand", "circumscribe", "publicize", "validate"],
    answer: 1,
  },
  {
    id: "vocab-exp3-26",
    difficulty: "Hard",
    word: "conflate",
    passage: "The article tends to ____ correlation with causation, treating two distinct ideas as if they were identical.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["distinguish", "conflate", "substantiate", "mitigate"],
    answer: 1,
  },
  {
    id: "vocab-exp3-27",
    difficulty: "Hard",
    word: "contingent",
    passage: "The project’s approval is ____ on the city securing additional funding.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["independent", "contingent", "permanent", "implicit"],
    answer: 1,
  },
  {
    id: "vocab-exp3-28",
    difficulty: "Hard",
    word: "delineate",
    passage: "The report carefully ____ the responsibilities of each department to prevent overlap.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["delineates", "conceals", "reverses", "generalizes"],
    answer: 0,
  },
  {
    id: "vocab-exp3-29",
    difficulty: "Hard",
    word: "disparate",
    passage: "The committee struggled to combine the ____ proposals, which differed in both purpose and method.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["coherent", "disparate", "preliminary", "viable"],
    answer: 1,
  },
  {
    id: "vocab-exp3-30",
    difficulty: "Hard",
    word: "ephemeral",
    passage: "The surge in demand was ____; sales returned to normal within a week.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["ephemeral", "persistent", "robust", "cumulative"],
    answer: 0,
  },
  {
    id: "vocab-exp3-31",
    difficulty: "Hard",
    word: "impute",
    passage: "It would be unfair to ____ motives to the researcher without direct evidence of intent.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["impute", "verify", "clarify", "simulate"],
    answer: 0,
  },
  {
    id: "vocab-exp3-32",
    difficulty: "Hard",
    word: "incongruous",
    passage: "The modern glass tower looked ____ beside the row of eighteenth-century stone houses.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["harmonious", "incongruous", "inevitable", "transparent"],
    answer: 1,
  },
  {
    id: "vocab-exp3-33",
    difficulty: "Hard",
    word: "proliferate",
    passage: "Without effective controls, invasive plants can ____ rapidly and displace native species.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["decline", "proliferate", "stabilize", "recede"],
    answer: 1,
  },
  {
    id: "vocab-exp3-34",
    difficulty: "Hard",
    word: "reticent",
    passage: "The witness remained ____ during the interview, offering only brief and guarded answers.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["reticent", "explicit", "enthusiastic", "comprehensive"],
    answer: 0,
  },
  {
    id: "vocab-exp3-35",
    difficulty: "Hard",
    word: "spurious",
    passage: "The apparent relationship was later shown to be ____ because it disappeared after researchers controlled for age.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["robust", "spurious", "salient", "inevitable"],
    answer: 1,
  },
  {
    id: "vocab-exp3-36",
    difficulty: "Hard",
    word: "vindicate",
    passage: "The newly released records may ____ the scientist by showing that her disputed calculations were correct.",
    prompt: "Which choice most logically and precisely completes the text?",
    choices: ["undermine", "vindicate", "qualify", "defer"],
    answer: 1,
  },
];

export const vocabularyExpansionPack3: ExamQuestion[] = entries.map((entry) => ({
  id: entry.id,
  examId: entry.id,
  section: "Reading & Writing",
  courseId: "vocabulary-expansion-pack-3",
  courseTitle: "Vocabulary · Words in Context",
  difficulty: entry.difficulty,
  domain: "Craft and Structure",
  skill: "Words in Context",
  questionType: "multiple-choice",
  passage: entry.passage,
  prompt: entry.prompt,
  choices: entry.choices.map((text, index) => ({
    text,
    rationale:
      index === entry.answer
        ? `"${text}" best matches the logical relationship and precise meaning established by the passage.`
        : "This option does not match the passage's meaning as precisely as the correct answer.",
  })),
  answer: entry.answer,
  walkthrough: [
    "Identify the relationship among the ideas surrounding the blank.",
    `The passage requires the sense expressed by "${entry.word}".`,
    "The correct choice fits both the logic and degree of meaning in context.",
  ],
  estimatedTime: 75,
  tags: [
    "vocabulary",
    "words-in-context",
    "vocabulary-expansion-pack-3",
    entry.difficulty,
    entry.word,
  ],
}));
