import type { SatDay } from "./types";

export const day05: SatDay = {
  day: 5,
  title: "Research, Data, and Reliability",
  description: "Strengthen the vocabulary used in scientific passages, experiments, data interpretation, and evaluation of sources.",
  words: [
    {
      word: "accurate",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "correct and free from error",
      example: "The device produced accurate measurements under controlled conditions.",
      synonyms: ["correct", "precise", "reliable"],
      collocations: ["accurate evidence", "accurate pattern"],
      wordFamily: ["accurate"],
    },
    {
      word: "analyze",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to examine something carefully by separating it into parts",
      example: "Researchers analyzed the samples for chemical differences.",
      synonyms: ["examine", "study", "evaluate"],
      collocations: ["analyze evidence", "analyze pattern"],
      wordFamily: ["analyze"],
    },
    {
      word: "anomaly",
      partOfSpeech: "noun",
      rating: 5,
      definition: "something that differs from what is normal or expected",
      example: "One unusually high result appeared to be an anomaly.",
      synonyms: ["irregularity", "exception", "outlier"],
      collocations: ["anomaly evidence", "anomaly pattern"],
      wordFamily: ["anomaly"],
    },
    {
      word: "correlate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to have or show a relationship with another variable",
      example: "Exercise frequency correlates with reported energy levels.",
      synonyms: ["associate", "connect", "correspond"],
      collocations: ["correlate evidence", "correlate pattern"],
      wordFamily: ["correlate"],
      satTip: "Correlation shows association; it does not by itself prove causation.",
    },
    {
      word: "criterion",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a standard used to make a judgment or decision",
      example: "Accuracy was the main criterion for selecting the model.",
      synonyms: ["standard", "measure", "requirement"],
      collocations: ["criterion evidence", "criterion pattern"],
      wordFamily: ["criterion"],
    },
    {
      word: "data",
      partOfSpeech: "noun",
      rating: 5,
      definition: "facts or measurements collected for analysis",
      example: "The data reveal a steady decline in water use.",
      synonyms: ["information", "figures", "observations"],
      collocations: ["data evidence", "data pattern"],
      wordFamily: ["data"],
    },
    {
      word: "empirical",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "based on observation or experiment rather than theory alone",
      example: "The claim is supported by empirical evidence.",
      synonyms: ["observational", "experimental", "evidence-based"],
      collocations: ["empirical evidence", "empirical pattern"],
      wordFamily: ["empirical"],
    },
    {
      word: "estimate",
      partOfSpeech: "noun",
      rating: 5,
      definition: "an approximate calculation or judgment",
      example: "The official estimate was lower than the final total.",
      synonyms: ["approximation", "projection", "assessment"],
      collocations: ["estimate evidence", "estimate pattern"],
      wordFamily: ["estimate"],
    },
    {
      word: "methodology",
      partOfSpeech: "noun",
      rating: 5,
      definition: "the system of methods used in a study or field",
      example: "The article explains the study's methodology in detail.",
      synonyms: ["procedure", "approach", "methods"],
      collocations: ["methodology evidence", "methodology pattern"],
      wordFamily: ["methodology"],
    },
    {
      word: "purpose",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a goal or purpose",
      example: "The primary objective was to determine whether the treatment was safe.",
      synonyms: ["goal", "aim", "purpose"],
      collocations: ["objective evidence", "objective pattern"],
      wordFamily: ["objective"],
      satTip: "Here objective is a noun meaning goal.",
    },
    {
      word: "observe",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to notice, watch, or record carefully",
      example: "The team observed the animals over several months.",
      synonyms: ["notice", "monitor", "record"],
      collocations: ["observe evidence", "observe pattern"],
      wordFamily: ["observe"],
    },
    {
      word: "outlier",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a data point that differs greatly from the rest",
      example: "The unusually low score was treated as an outlier.",
      synonyms: ["anomaly", "exception", "extreme value"],
      collocations: ["outlier evidence", "outlier pattern"],
      wordFamily: ["outlier"],
    },
    {
      word: "parameter",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a limit, condition, or measurable feature used in a system or study",
      example: "The researchers changed one parameter at a time.",
      synonyms: ["variable", "condition", "limit"],
      collocations: ["parameter evidence", "parameter pattern"],
      wordFamily: ["parameter"],
    },
    {
      word: "precision",
      partOfSpeech: "noun",
      rating: 5,
      definition: "the quality of being exact and consistent",
      example: "The instrument measures distance with great precision.",
      synonyms: ["exactness", "accuracy", "specificity"],
      collocations: ["precision evidence", "precision pattern"],
      wordFamily: ["precision"],
    },
    {
      word: "replicate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to repeat a study or process to see whether the same result occurs",
      example: "Other teams were unable to replicate the original finding.",
      synonyms: ["repeat", "reproduce", "duplicate"],
      collocations: ["replicate evidence", "replicate pattern"],
      wordFamily: ["replicate"],
    },
    {
      word: "representative",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "typical of a larger group",
      example: "The sample was designed to be representative of the national population.",
      synonyms: ["typical", "characteristic", "reflective"],
      collocations: ["representative evidence", "representative pattern"],
      wordFamily: ["representative"],
    },
    {
      word: "reliable",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "consistently accurate or dependable",
      example: "The researchers used a reliable measurement tool.",
      synonyms: ["dependable", "consistent", "trustworthy"],
      collocations: ["reliable evidence", "reliable pattern"],
      wordFamily: ["reliable"],
    },
    {
      word: "sample",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a smaller group selected from a larger population",
      example: "The survey included a sample of 1,200 adults.",
      synonyms: ["subset", "selection", "group"],
      collocations: ["sample evidence", "sample pattern"],
      wordFamily: ["sample"],
    },
    {
      word: "statistical",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "related to the collection and analysis of numerical data",
      example: "The difference was statistically significant.",
      synonyms: ["numerical", "quantitative", "data-based"],
      collocations: ["statistical evidence", "statistical pattern"],
      wordFamily: ["statistical"],
    },
    {
      word: "validate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to confirm that something is accurate, sound, or acceptable",
      example: "A second experiment helped validate the model.",
      synonyms: ["confirm", "verify", "support"],
      collocations: ["validate evidence", "validate pattern"],
      wordFamily: ["validate"],
    },
    {
      word: "variable",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a factor that can change or take different values",
      example: "Temperature was the only variable altered during the test.",
      synonyms: ["factor", "element", "quantity"],
      collocations: ["variable evidence", "variable pattern"],
      wordFamily: ["variable"],
    },
    {
      word: "verify",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to check or prove that something is true or accurate",
      example: "The team repeated the measurement to verify the result.",
      synonyms: ["confirm", "check", "substantiate"],
      collocations: ["verify evidence", "verify pattern"],
      wordFamily: ["verify"],
    },
    {
      word: "valid",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "well-founded, logically sound, or accurately measuring what is intended",
      example: "The researchers questioned whether the survey was a valid measure of stress.",
      synonyms: ["sound", "legitimate", "well-founded"],
      collocations: ["valid evidence", "valid pattern"],
      wordFamily: ["valid"],
    },
    {
      word: "robust",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "strong, reliable, and able to remain effective under different conditions",
      example: "The conclusion remained robust across several analyses.",
      synonyms: ["strong", "resilient", "reliable"],
      collocations: ["robust evidence", "robust pattern"],
      wordFamily: ["robust"],
    },
    {
      word: "preliminary",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "not final or fully certain",
      example: "Because the sample was small, the conclusion remained tentative.",
      synonyms: ["preliminary", "provisional", "uncertain"],
      collocations: ["tentative evidence", "tentative pattern"],
      wordFamily: ["tentative"],
    }
  ],
  questions: [
    {
      id: 1,
      prompt: "The device produced ______ measurements under controlled conditions.",
      choices: ["analyze", "anomaly", "correlate", "accurate"],
      answer: "accurate",
      explanation: "Accurate means correct and free from error.",
    },
    {
      id: 2,
      prompt: "Choose the word that best completes the idea: To examine something carefully by separating it into parts: ______.",
      choices: ["anomaly", "correlate", "analyze", "accurate"],
      answer: "analyze",
      explanation: "Analyze means to examine something carefully by separating it into parts.",
    },
    {
      id: 3,
      prompt: "One unusually high result appeared to be an ______.",
      choices: ["correlate", "anomaly", "accurate", "analyze"],
      answer: "anomaly",
      explanation: "Anomaly means something that differs from what is normal or expected.",
    },
    {
      id: 4,
      prompt: "Exercise frequency ______ with reported energy levels.",
      choices: ["correlate", "accurate", "analyze", "anomaly"],
      answer: "correlate",
      explanation: "Correlate means to have or show a relationship with another variable.",
    },
    {
      id: 5,
      prompt: "Accuracy was the main ______ for selecting the model.",
      choices: ["accurate", "analyze", "anomaly", "criterion"],
      answer: "criterion",
      explanation: "Criterion means a standard used to make a judgment or decision.",
    },
    {
      id: 6,
      prompt: "The ______ reveal a steady decline in water use.",
      choices: ["analyze", "anomaly", "data", "accurate"],
      answer: "data",
      explanation: "Data means facts or measurements collected for analysis.",
    },
    {
      id: 7,
      prompt: "The claim is supported by ______ evidence.",
      choices: ["anomaly", "empirical", "accurate", "analyze"],
      answer: "empirical",
      explanation: "Empirical means based on observation or experiment rather than theory alone.",
    },
    {
      id: 8,
      prompt: "The official ______ was lower than the final total.",
      choices: ["estimate", "accurate", "analyze", "anomaly"],
      answer: "estimate",
      explanation: "Estimate means an approximate calculation or judgment.",
    },
    {
      id: 9,
      prompt: "The article explains the study's ______ in detail.",
      choices: ["accurate", "analyze", "anomaly", "methodology"],
      answer: "methodology",
      explanation: "Methodology means the system of methods used in a study or field.",
    },
    {
      id: 10,
      prompt: "The primary ______ was to determine whether the treatment was safe.",
      choices: ["analyze", "anomaly", "purpose", "accurate"],
      answer: "purpose",
      explanation: "Purpose means an intended goal or aim.",
    },
    {
      id: 11,
      prompt: "Choose the word that best completes the idea: To notice, watch, or record carefully: ______.",
      choices: ["anomaly", "observe", "accurate", "analyze"],
      answer: "observe",
      explanation: "Observe means to notice, watch, or record carefully.",
    },
    {
      id: 12,
      prompt: "The unusually low score was treated as an ______.",
      choices: ["outlier", "accurate", "analyze", "anomaly"],
      answer: "outlier",
      explanation: "Outlier means a data point that differs greatly from the rest.",
    },
    {
      id: 13,
      prompt: "The researchers changed one ______ at a time.",
      choices: ["accurate", "analyze", "anomaly", "parameter"],
      answer: "parameter",
      explanation: "Parameter means a limit, condition, or measurable feature used in a system or study.",
    },
    {
      id: 14,
      prompt: "The instrument measures distance with great ______.",
      choices: ["analyze", "anomaly", "precision", "accurate"],
      answer: "precision",
      explanation: "Precision means the quality of being exact and consistent.",
    },
    {
      id: 15,
      prompt: "Other teams were unable to ______ the original finding.",
      choices: ["anomaly", "replicate", "accurate", "analyze"],
      answer: "replicate",
      explanation: "Replicate means to repeat a study or process to see whether the same result occurs.",
    }
  ],
};
