import type { SatDay } from "./types";

export const day03: SatDay = {
  day: 3,
  title: "Cause, Effect, and Process",
  description: "Learn the vocabulary used to explain mechanisms, consequences, sequences, and causal relationships.",
  words: [
    {
      word: "accelerate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to cause something to happen faster",
      example: "Higher temperatures can accelerate the chemical reaction.",
      synonyms: ["speed up", "hasten", "advance"],
      collocations: ["accelerate evidence", "accelerate pattern"],
      wordFamily: ["accelerate"],
    },
    {
      word: "consequence",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a result or effect of an action or condition",
      example: "One consequence of the policy was a decline in traffic.",
      synonyms: ["result", "outcome", "effect"],
      collocations: ["consequence evidence", "consequence pattern"],
      wordFamily: ["consequence"],
    },
    {
      word: "contribute",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to help cause or produce something",
      example: "Several factors contributed to the population increase.",
      synonyms: ["add to", "promote", "help cause"],
      collocations: ["contribute evidence", "contribute pattern"],
      wordFamily: ["contribute"],
    },
    {
      word: "derive",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to obtain or develop from a source",
      example: "The formula is derived from earlier research.",
      synonyms: ["obtain", "originate", "draw"],
      collocations: ["derive evidence", "derive pattern"],
      wordFamily: ["derive"],
    },
    {
      word: "emerge",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to become visible, known, or important",
      example: "A clear pattern emerged from the data.",
      synonyms: ["appear", "arise", "develop"],
      collocations: ["emerge evidence", "emerge pattern"],
      wordFamily: ["emerge"],
    },
    {
      word: "facilitate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to make a process or action easier",
      example: "The new software facilitates collaboration among researchers.",
      synonyms: ["enable", "assist", "ease"],
      collocations: ["facilitate evidence", "facilitate pattern"],
      wordFamily: ["facilitate"],
    },
    {
      word: "generate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to produce or create",
      example: "The system generates electricity from sunlight.",
      synonyms: ["produce", "create", "yield"],
      collocations: ["generate evidence", "generate pattern"],
      wordFamily: ["generate"],
    },
    {
      word: "inhibit",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to prevent, slow, or limit a process",
      example: "Low temperatures inhibit the growth of the bacteria.",
      synonyms: ["restrain", "limit", "suppress"],
      collocations: ["inhibit evidence", "inhibit pattern"],
      wordFamily: ["inhibit"],
    },
    {
      word: "initiate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to cause a process or event to begin",
      example: "A small signal initiates the response.",
      synonyms: ["begin", "launch", "trigger"],
      collocations: ["initiate evidence", "initiate pattern"],
      wordFamily: ["initiate"],
    },
    {
      word: "interact",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to act on or influence one another",
      example: "The two chemicals interact under high pressure.",
      synonyms: ["engage", "influence", "combine"],
      collocations: ["interact evidence", "interact pattern"],
      wordFamily: ["interact"],
    },
    {
      word: "mechanism",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a process or system that produces a particular result",
      example: "Scientists are studying the mechanism behind memory formation.",
      synonyms: ["process", "system", "means"],
      collocations: ["mechanism evidence", "mechanism pattern"],
      wordFamily: ["mechanism"],
    },
    {
      word: "precede",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to happen or come before something",
      example: "A brief warning usually precedes the storm.",
      synonyms: ["come before", "predate", "lead"],
      collocations: ["precede evidence", "precede pattern"],
      wordFamily: ["precede"],
    },
    {
      word: "prompt",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to cause or encourage an action or response",
      example: "The discovery prompted researchers to revise the theory.",
      synonyms: ["cause", "trigger", "provoke"],
      collocations: ["prompt evidence", "prompt pattern"],
      wordFamily: ["prompt"],
    },
    {
      word: "reinforce",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to strengthen an idea, feeling, or structure",
      example: "The new evidence reinforces the original conclusion.",
      synonyms: ["strengthen", "support", "confirm"],
      collocations: ["reinforce evidence", "reinforce pattern"],
      wordFamily: ["reinforce"],
    },
    {
      word: "result",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to occur as a consequence",
      example: "The change resulted in higher efficiency.",
      synonyms: ["follow", "arise", "ensue"],
      collocations: ["result evidence", "result pattern"],
      wordFamily: ["result"],
      satTip: "Result in introduces an effect; result from introduces a cause.",
    },
    {
      word: "sequence",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a particular order in which events or steps occur",
      example: "The experiment followed a precise sequence of steps.",
      synonyms: ["order", "series", "progression"],
      collocations: ["sequence evidence", "sequence pattern"],
      wordFamily: ["sequence"],
    },
    {
      word: "stimulate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to encourage activity, growth, or development",
      example: "The program stimulated interest in engineering.",
      synonyms: ["encourage", "activate", "promote"],
      collocations: ["stimulate evidence", "stimulate pattern"],
      wordFamily: ["stimulate"],
    },
    {
      word: "subsequent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "happening after something else",
      example: "Subsequent studies confirmed the finding.",
      synonyms: ["later", "following", "ensuing"],
      collocations: ["subsequent evidence", "subsequent pattern"],
      wordFamily: ["subsequent"],
    },
    {
      word: "sustain",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to continue or maintain something over time",
      example: "The region could not sustain rapid population growth.",
      synonyms: ["maintain", "support", "continue"],
      collocations: ["sustain evidence", "sustain pattern"],
      wordFamily: ["sustain"],
    },
    {
      word: "trigger",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to cause an event or process to begin",
      example: "A change in temperature can trigger migration.",
      synonyms: ["cause", "initiate", "set off"],
      collocations: ["trigger evidence", "trigger pattern"],
      wordFamily: ["trigger"],
    },
    {
      word: "underlie",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to form the basis or cause of something",
      example: "Several assumptions underlie the model.",
      synonyms: ["support", "form the basis of", "cause"],
      collocations: ["underlie evidence", "underlie pattern"],
      wordFamily: ["underlie"],
    },
    {
      word: "yield",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to produce a result, amount, or product",
      example: "The experiment yielded unexpected results.",
      synonyms: ["produce", "generate", "provide"],
      collocations: ["yield evidence", "yield pattern"],
      wordFamily: ["yield"],
    },
    {
      word: "cumulative",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "increasing by successive additions",
      example: "The cumulative effect became clear after several years.",
      synonyms: ["combined", "accumulated", "total"],
      collocations: ["cumulative evidence", "cumulative pattern"],
      wordFamily: ["cumulative"],
    },
    {
      word: "mediate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to influence or explain the relationship between two factors",
      example: "Social support may mediate the effects of stress.",
      synonyms: ["intervene", "moderate", "connect"],
      collocations: ["mediate evidence", "mediate pattern"],
      wordFamily: ["mediate"],
    },
    {
      word: "transform",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to change greatly in form, nature, or function",
      example: "Digital tools transformed how the team collected data.",
      synonyms: ["convert", "reshape", "alter"],
      collocations: ["transform evidence", "transform pattern"],
      wordFamily: ["transform"],
    }
  ],
  questions: [
    {
      id: 1,
      prompt: "Higher temperatures can ______ the chemical reaction.",
      choices: ["consequence", "contribute", "derive", "accelerate"],
      answer: "accelerate",
      explanation: "Accelerate means to cause something to happen faster.",
    },
    {
      id: 2,
      prompt: "One ______ of the policy was a decline in traffic.",
      choices: ["contribute", "derive", "consequence", "accelerate"],
      answer: "consequence",
      explanation: "Consequence means a result or effect of an action or condition.",
    },
    {
      id: 3,
      prompt: "Choose the word that best completes the idea: To help cause or produce something: ______.",
      choices: ["derive", "contribute", "accelerate", "consequence"],
      answer: "contribute",
      explanation: "Contribute means to help cause or produce something.",
    },
    {
      id: 4,
      prompt: "Choose the word that best completes the idea: To obtain or develop from a source: ______.",
      choices: ["derive", "accelerate", "consequence", "contribute"],
      answer: "derive",
      explanation: "Derive means to obtain or develop from a source.",
    },
    {
      id: 5,
      prompt: "Choose the word that best completes the idea: To become visible, known, or important: ______.",
      choices: ["accelerate", "consequence", "contribute", "emerge"],
      answer: "emerge",
      explanation: "Emerge means to become visible, known, or important.",
    },
    {
      id: 6,
      prompt: "The new software ______ collaboration among researchers.",
      choices: ["consequence", "contribute", "facilitate", "accelerate"],
      answer: "facilitate",
      explanation: "Facilitate means to make a process or action easier.",
    },
    {
      id: 7,
      prompt: "The system ______ electricity from sunlight.",
      choices: ["contribute", "generate", "accelerate", "consequence"],
      answer: "generate",
      explanation: "Generate means to produce or create.",
    },
    {
      id: 8,
      prompt: "Low temperatures ______ the growth of the bacteria.",
      choices: ["inhibit", "accelerate", "consequence", "contribute"],
      answer: "inhibit",
      explanation: "Inhibit means to prevent, slow, or limit a process.",
    },
    {
      id: 9,
      prompt: "A small signal ______ the response.",
      choices: ["accelerate", "consequence", "contribute", "initiate"],
      answer: "initiate",
      explanation: "Initiate means to cause a process or event to begin.",
    },
    {
      id: 10,
      prompt: "The two chemicals ______ under high pressure.",
      choices: ["consequence", "contribute", "interact", "accelerate"],
      answer: "interact",
      explanation: "Interact means to act on or influence one another.",
    },
    {
      id: 11,
      prompt: "Scientists are studying the ______ behind memory formation.",
      choices: ["contribute", "mechanism", "accelerate", "consequence"],
      answer: "mechanism",
      explanation: "Mechanism means a process or system that produces a particular result.",
    },
    {
      id: 12,
      prompt: "A brief warning usually ______ the storm.",
      choices: ["precede", "accelerate", "consequence", "contribute"],
      answer: "precede",
      explanation: "Precede means to happen or come before something.",
    },
    {
      id: 13,
      prompt: "The discovery ______ researchers to revise the theory.",
      choices: ["accelerate", "consequence", "contribute", "prompt"],
      answer: "prompt",
      explanation: "Prompt means to cause or encourage an action or response.",
    },
    {
      id: 14,
      prompt: "The new evidence ______ the original conclusion.",
      choices: ["consequence", "contribute", "reinforce", "accelerate"],
      answer: "reinforce",
      explanation: "Reinforce means to strengthen an idea, feeling, or structure.",
    },
    {
      id: 15,
      prompt: "The change ______ in higher efficiency.",
      choices: ["contribute", "result", "accelerate", "consequence"],
      answer: "result",
      explanation: "Result means to occur as a consequence.",
    }
  ],
};
