import type { SatDay } from "./types";

export const day04: SatDay = {
  day: 4,
  title: "Argument, Perspective, and Tone",
  description: "Develop the vocabulary needed to analyze viewpoints, rhetorical choices, authorial stance, and persuasion.",
  words: [
    {
      word: "acknowledge",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to recognize or admit the existence or truth of something",
      example: "The author acknowledges a limitation of the study.",
      synonyms: ["admit", "recognize", "concede"],
      collocations: ["acknowledge evidence", "acknowledge pattern"],
      wordFamily: ["acknowledge"],
    },
    {
      word: "assert",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to state something confidently and forcefully",
      example: "The critic asserts that the novel challenges social conventions.",
      synonyms: ["declare", "claim", "maintain"],
      collocations: ["assert evidence", "assert pattern"],
      wordFamily: ["assert"],
    },
    {
      word: "bias",
      partOfSpeech: "noun",
      rating: 5,
      definition: "an unfair preference that affects judgment",
      example: "The researchers designed the study to reduce selection bias.",
      synonyms: ["prejudice", "partiality", "inclination"],
      collocations: ["bias evidence", "bias pattern"],
      wordFamily: ["bias"],
    },
    {
      word: "cite",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to refer to evidence, an example, or a source",
      example: "The essay cites several studies to support its claim.",
      synonyms: ["quote", "reference", "mention"],
      collocations: ["cite evidence", "cite pattern"],
      wordFamily: ["cite"],
    },
    {
      word: "concede",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to admit that something is true, often reluctantly",
      example: "The author concedes that the proposal would be expensive.",
      synonyms: ["admit", "acknowledge", "grant"],
      collocations: ["concede evidence", "concede pattern"],
      wordFamily: ["concede"],
    },
    {
      word: "contention",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a claim or position maintained in an argument",
      example: "The evidence supports the author's central contention.",
      synonyms: ["claim", "argument", "position"],
      collocations: ["contention evidence", "contention pattern"],
      wordFamily: ["contention"],
    },
    {
      word: "criticize",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to point out faults or problems",
      example: "The article criticizes the policy for ignoring rural communities.",
      synonyms: ["challenge", "condemn", "fault"],
      collocations: ["criticize evidence", "criticize pattern"],
      wordFamily: ["criticize"],
    },
    {
      word: "emphasize",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to give special importance or attention to something",
      example: "The passage emphasizes the need for long-term planning.",
      synonyms: ["stress", "highlight", "underscore"],
      collocations: ["emphasize evidence", "emphasize pattern"],
      wordFamily: ["emphasize"],
    },
    {
      word: "endorse",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to publicly approve of or support",
      example: "Several experts endorsed the revised guidelines.",
      synonyms: ["support", "approve", "back"],
      collocations: ["endorse evidence", "endorse pattern"],
      wordFamily: ["endorse"],
    },
    {
      word: "objective",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "based on facts rather than personal feelings",
      example: "The report attempts to provide an objective assessment.",
      synonyms: ["impartial", "factual", "unbiased"],
      collocations: ["objective evidence", "objective pattern"],
      wordFamily: ["objective"],
      satTip: "Objective contrasts with subjective.",
    },
    {
      word: "perspective",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a particular way of viewing or understanding something",
      example: "The memoir presents the events from a child's perspective.",
      synonyms: ["viewpoint", "outlook", "standpoint"],
      collocations: ["perspective evidence", "perspective pattern"],
      wordFamily: ["perspective"],
    },
    {
      word: "qualify",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to limit or modify a statement by adding conditions",
      example: "The author qualifies the claim by noting several exceptions.",
      synonyms: ["limit", "modify", "restrict"],
      collocations: ["qualify evidence", "qualify pattern"],
      wordFamily: ["qualify"],
      satTip: "To qualify a claim is to limit it, not necessarily to reject it.",
    },
    {
      word: "refute",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to prove that a claim or argument is false",
      example: "The later evidence refuted the original explanation.",
      synonyms: ["disprove", "rebut", "invalidate"],
      collocations: ["refute evidence", "refute pattern"],
      wordFamily: ["refute"],
    },
    {
      word: "rhetorical",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "related to the effective use of language in speaking or writing",
      example: "The speech uses rhetorical questions to engage the audience.",
      synonyms: ["persuasive", "stylistic", "oratorical"],
      collocations: ["rhetorical evidence", "rhetorical pattern"],
      wordFamily: ["rhetorical"],
    },
    {
      word: "skeptical",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "not easily convinced; doubtful",
      example: "The scientist remained skeptical of the dramatic claim.",
      synonyms: ["doubtful", "questioning", "unconvinced"],
      collocations: ["skeptical evidence", "skeptical pattern"],
      wordFamily: ["skeptical"],
    },
    {
      word: "stance",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a position or attitude toward an issue",
      example: "The editorial takes a cautious stance on the proposal.",
      synonyms: ["position", "view", "attitude"],
      collocations: ["stance evidence", "stance pattern"],
      wordFamily: ["stance"],
    },
    {
      word: "subjective",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "based on personal opinions, feelings, or experiences",
      example: "The review is openly subjective rather than purely factual.",
      synonyms: ["personal", "interpretive", "biased"],
      collocations: ["subjective evidence", "subjective pattern"],
      wordFamily: ["subjective"],
    },
    {
      word: "support",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to provide evidence or reasoning for a claim",
      example: "The data support the conclusion that the treatment is effective.",
      synonyms: ["confirm", "substantiate", "back"],
      collocations: ["support evidence", "support pattern"],
      wordFamily: ["support"],
    },
    {
      word: "undermine",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to weaken the force, credibility, or effectiveness of something",
      example: "The missing data undermine confidence in the result.",
      synonyms: ["weaken", "damage", "erode"],
      collocations: ["undermine evidence", "undermine pattern"],
      wordFamily: ["undermine"],
    },
    {
      word: "viewpoint",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a particular opinion or way of considering a subject",
      example: "The article includes viewpoints from several communities.",
      synonyms: ["perspective", "opinion", "position"],
      collocations: ["viewpoint evidence", "viewpoint pattern"],
      wordFamily: ["viewpoint"],
    },
    {
      word: "ambivalent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "having mixed or conflicting feelings",
      example: "The narrator is ambivalent about returning home.",
      synonyms: ["uncertain", "conflicted", "mixed"],
      collocations: ["ambivalent evidence", "ambivalent pattern"],
      wordFamily: ["ambivalent"],
    },
    {
      word: "cautious",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "careful to avoid risk or overstatement",
      example: "The researchers offered a cautious interpretation of the results.",
      synonyms: ["careful", "reserved", "prudent"],
      collocations: ["cautious evidence", "cautious pattern"],
      wordFamily: ["cautious"],
    },
    {
      word: "dismissive",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "showing that something is not worthy of consideration",
      example: "The critic's dismissive tone weakens the fairness of the review.",
      synonyms: ["scornful", "contemptuous", "indifferent"],
      collocations: ["dismissive evidence", "dismissive pattern"],
      wordFamily: ["dismissive"],
    },
    {
      word: "nuanced",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "showing subtle distinctions or complexity",
      example: "The essay offers a nuanced account of the conflict.",
      synonyms: ["subtle", "complex", "refined"],
      collocations: ["nuanced evidence", "nuanced pattern"],
      wordFamily: ["nuanced"],
    },
    {
      word: "tentative",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "not fully certain or decided",
      example: "The researchers reached only a tentative conclusion.",
      synonyms: ["provisional", "uncertain", "preliminary"],
      collocations: ["tentative evidence", "tentative pattern"],
      wordFamily: ["tentative"],
    }
  ],
  questions: [
    {
      id: 1,
      prompt: "The author ______ a limitation of the study.",
      choices: ["assert", "bias", "cite", "acknowledge"],
      answer: "acknowledge",
      explanation: "Acknowledge means to recognize or admit the existence or truth of something.",
    },
    {
      id: 2,
      prompt: "The critic ______ that the novel challenges social conventions.",
      choices: ["bias", "cite", "assert", "acknowledge"],
      answer: "assert",
      explanation: "Assert means to state something confidently and forcefully.",
    },
    {
      id: 3,
      prompt: "The researchers designed the study to reduce selection ______.",
      choices: ["cite", "bias", "acknowledge", "assert"],
      answer: "bias",
      explanation: "Bias means an unfair preference that affects judgment.",
    },
    {
      id: 4,
      prompt: "The essay ______ several studies to support its claim.",
      choices: ["cite", "acknowledge", "assert", "bias"],
      answer: "cite",
      explanation: "Cite means to refer to evidence, an example, or a source.",
    },
    {
      id: 5,
      prompt: "The author ______ that the proposal would be expensive.",
      choices: ["acknowledge", "assert", "bias", "concede"],
      answer: "concede",
      explanation: "Concede means to admit that something is true, often reluctantly.",
    },
    {
      id: 6,
      prompt: "The evidence supports the author's central ______.",
      choices: ["assert", "bias", "contention", "acknowledge"],
      answer: "contention",
      explanation: "Contention means a claim or position maintained in an argument.",
    },
    {
      id: 7,
      prompt: "The article ______ the policy for ignoring rural communities.",
      choices: ["bias", "criticize", "acknowledge", "assert"],
      answer: "criticize",
      explanation: "Criticize means to point out faults or problems.",
    },
    {
      id: 8,
      prompt: "The passage ______ the need for long-term planning.",
      choices: ["emphasize", "acknowledge", "assert", "bias"],
      answer: "emphasize",
      explanation: "Emphasize means to give special importance or attention to something.",
    },
    {
      id: 9,
      prompt: "Choose the word that best completes the idea: To publicly approve of or support: ______.",
      choices: ["acknowledge", "assert", "bias", "endorse"],
      answer: "endorse",
      explanation: "Endorse means to publicly approve of or support.",
    },
    {
      id: 10,
      prompt: "The report attempts to provide an ______ assessment.",
      choices: ["assert", "bias", "objective", "acknowledge"],
      answer: "objective",
      explanation: "Objective means based on facts rather than personal feelings.",
    },
    {
      id: 11,
      prompt: "The memoir presents the events from a child's ______.",
      choices: ["bias", "perspective", "acknowledge", "assert"],
      answer: "perspective",
      explanation: "Perspective means a particular way of viewing or understanding something.",
    },
    {
      id: 12,
      prompt: "Choose the word that best completes the idea: To limit or modify a statement by adding conditions: ______.",
      choices: ["qualify", "acknowledge", "assert", "bias"],
      answer: "qualify",
      explanation: "Qualify means to limit or modify a statement by adding conditions.",
    },
    {
      id: 13,
      prompt: "Choose the word that best completes the idea: To prove that a claim or argument is false: ______.",
      choices: ["acknowledge", "assert", "bias", "refute"],
      answer: "refute",
      explanation: "Refute means to prove that a claim or argument is false.",
    },
    {
      id: 14,
      prompt: "The speech uses ______ questions to engage the audience.",
      choices: ["assert", "bias", "rhetorical", "acknowledge"],
      answer: "rhetorical",
      explanation: "Rhetorical means related to the effective use of language in speaking or writing.",
    },
    {
      id: 15,
      prompt: "The scientist remained ______ of the dramatic claim.",
      choices: ["bias", "skeptical", "acknowledge", "assert"],
      answer: "skeptical",
      explanation: "Skeptical means not easily convinced; doubtful.",
    }
  ],
};
