import type { SatDay } from "./types";

export const day02: SatDay = {
  day: 2,
  title: "Change, Comparison, and Degree",
  description: "Master words used to describe trends, contrasts, intensity, and relationships between ideas.",
  words: [
    {
      word: "alter",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to change something, usually in a partial way",
      example: "The revised policy altered how applications were reviewed.",
      synonyms: ["change", "modify", "adjust"],
      collocations: ["alter evidence", "alter pattern"],
      wordFamily: ["alter"],
    },
    {
      word: "apparent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "clearly visible or understood; seeming to be true",
      example: "The apparent decline disappeared after the data were corrected.",
      synonyms: ["obvious", "evident", "seeming"],
      collocations: ["apparent evidence", "apparent pattern"],
      wordFamily: ["apparent"],
    },
    {
      word: "approximate",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "close to the actual amount or value but not exact",
      example: "The researchers provided an approximate estimate of the population.",
      synonyms: ["estimated", "rough", "near"],
      collocations: ["approximate evidence", "approximate pattern"],
      wordFamily: ["approximate"],
    },
    {
      word: "arbitrary",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "based on personal choice rather than reason or a system",
      example: "The cutoff seemed arbitrary because no explanation was provided.",
      synonyms: ["random", "unreasoned", "subjective"],
      collocations: ["arbitrary evidence", "arbitrary pattern"],
      wordFamily: ["arbitrary"],
    },
    {
      word: "comparable",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "similar enough to be meaningfully compared",
      example: "The two studies used comparable methods and sample sizes.",
      synonyms: ["similar", "equivalent", "analogous"],
      collocations: ["comparable evidence", "comparable pattern"],
      wordFamily: ["comparable"],
    },
    {
      word: "contrast",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to show how two or more things differ",
      example: "The passage contrasts traditional methods with newer approaches.",
      synonyms: ["differentiate", "compare", "distinguish"],
      collocations: ["contrast evidence", "contrast pattern"],
      wordFamily: ["contrast"],
      satTip: "Contrast questions ask how two ideas differ, not merely what they share.",
    },
    {
      word: "conventional",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "based on what is generally accepted or commonly done",
      example: "The architect rejected conventional designs in favor of a flexible structure.",
      synonyms: ["traditional", "standard", "customary"],
      collocations: ["conventional evidence", "conventional pattern"],
      wordFamily: ["conventional"],
    },
    {
      word: "diminish",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to make or become smaller, weaker, or less important",
      example: "The effect diminished as the temperature decreased.",
      synonyms: ["reduce", "lessen", "decline"],
      collocations: ["diminish evidence", "diminish pattern"],
      wordFamily: ["diminish"],
    },
    {
      word: "distinct",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "clearly different or separate",
      example: "The two species have distinct feeding patterns.",
      synonyms: ["different", "separate", "recognizable"],
      collocations: ["distinct evidence", "distinct pattern"],
      wordFamily: ["distinct"],
    },
    {
      word: "dramatic",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "large, sudden, or striking",
      example: "The city experienced a dramatic increase in public transit use.",
      synonyms: ["striking", "sharp", "remarkable"],
      collocations: ["dramatic evidence", "dramatic pattern"],
      wordFamily: ["dramatic"],
    },
    {
      word: "equivalent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "equal in value, meaning, or effect",
      example: "The two measures are roughly equivalent in accuracy.",
      synonyms: ["equal", "comparable", "corresponding"],
      collocations: ["equivalent evidence", "equivalent pattern"],
      wordFamily: ["equivalent"],
    },
    {
      word: "exceed",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to be greater than a limit, amount, or expectation",
      example: "The final cost exceeded the original estimate.",
      synonyms: ["surpass", "outstrip", "go beyond"],
      collocations: ["exceed evidence", "exceed pattern"],
      wordFamily: ["exceed"],
    },
    {
      word: "fluctuate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to rise and fall irregularly",
      example: "Energy prices fluctuate throughout the year.",
      synonyms: ["vary", "shift", "oscillate"],
      collocations: ["fluctuate evidence", "fluctuate pattern"],
      wordFamily: ["fluctuate"],
    },
    {
      word: "gradual",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "happening slowly over time",
      example: "The recovery was gradual rather than immediate.",
      synonyms: ["slow", "steady", "incremental"],
      collocations: ["gradual evidence", "gradual pattern"],
      wordFamily: ["gradual"],
    },
    {
      word: "marginal",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "small or limited in importance, amount, or effect",
      example: "The new process produced only a marginal improvement.",
      synonyms: ["slight", "minor", "minimal"],
      collocations: ["marginal evidence", "marginal pattern"],
      wordFamily: ["marginal"],
    },
    {
      word: "moderate",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "average or limited in amount, intensity, or degree",
      example: "The treatment produced a moderate reduction in symptoms.",
      synonyms: ["medium", "limited", "reasonable"],
      collocations: ["moderate evidence", "moderate pattern"],
      wordFamily: ["moderate"],
    },
    {
      word: "negligible",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "so small or unimportant that it can be ignored",
      example: "The difference between the two measurements was negligible.",
      synonyms: ["insignificant", "minimal", "trivial"],
      collocations: ["negligible evidence", "negligible pattern"],
      wordFamily: ["negligible"],
    },
    {
      word: "parallel",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "similar and developing in the same way",
      example: "The two movements followed parallel paths.",
      synonyms: ["similar", "corresponding", "analogous"],
      collocations: ["parallel evidence", "parallel pattern"],
      wordFamily: ["parallel"],
    },
    {
      word: "predominant",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "present in the greatest amount or having the strongest influence",
      example: "Agriculture remained the predominant industry in the region.",
      synonyms: ["dominant", "main", "prevailing"],
      collocations: ["predominant evidence", "predominant pattern"],
      wordFamily: ["predominant"],
    },
    {
      word: "proportion",
      partOfSpeech: "noun",
      rating: 5,
      definition: "a part or share in relation to a whole",
      example: "A large proportion of respondents supported the proposal.",
      synonyms: ["share", "fraction", "ratio"],
      collocations: ["proportion evidence", "proportion pattern"],
      wordFamily: ["proportion"],
    },
    {
      word: "relative",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "considered in comparison with something else",
      example: "The value of the result depends on its relative importance.",
      synonyms: ["comparative", "related", "proportional"],
      collocations: ["relative evidence", "relative pattern"],
      wordFamily: ["relative"],
    },
    {
      word: "retain",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to continue to have or keep",
      example: "The material retains heat even after the source is removed.",
      synonyms: ["keep", "preserve", "maintain"],
      collocations: ["retain evidence", "retain pattern"],
      wordFamily: ["retain"],
    },
    {
      word: "subtle",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "not obvious; delicate or difficult to notice",
      example: "The author makes a subtle distinction between the two concepts.",
      synonyms: ["slight", "nuanced", "understated"],
      collocations: ["subtle evidence", "subtle pattern"],
      wordFamily: ["subtle"],
    },
    {
      word: "uniform",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "remaining the same throughout; consistent",
      example: "The samples were stored under uniform conditions.",
      synonyms: ["consistent", "even", "standardized"],
      collocations: ["uniform evidence", "uniform pattern"],
      wordFamily: ["uniform"],
    },
    {
      word: "vary",
      partOfSpeech: "verb",
      rating: 5,
      definition: "to differ or change",
      example: "Responses vary according to age and experience.",
      synonyms: ["differ", "change", "fluctuate"],
      collocations: ["vary evidence", "vary pattern"],
      wordFamily: ["vary"],
    }
  ],
  questions: [
    {
      id: 1,
      prompt: "The revised policy ______ how applications were reviewed.",
      choices: ["apparent", "approximate", "arbitrary", "alter"],
      answer: "alter",
      explanation: "Alter means to change something, usually in a partial way.",
    },
    {
      id: 2,
      prompt: "The ______ decline disappeared after the data were corrected.",
      choices: ["approximate", "arbitrary", "apparent", "alter"],
      answer: "apparent",
      explanation: "Apparent means clearly visible or understood; seeming to be true.",
    },
    {
      id: 3,
      prompt: "The researchers provided an ______ estimate of the population.",
      choices: ["arbitrary", "approximate", "alter", "apparent"],
      answer: "approximate",
      explanation: "Approximate means close to the actual amount or value but not exact.",
    },
    {
      id: 4,
      prompt: "The cutoff seemed ______ because no explanation was provided.",
      choices: ["arbitrary", "alter", "apparent", "approximate"],
      answer: "arbitrary",
      explanation: "Arbitrary means based on personal choice rather than reason or a system.",
    },
    {
      id: 5,
      prompt: "The two studies used ______ methods and sample sizes.",
      choices: ["alter", "apparent", "approximate", "comparable"],
      answer: "comparable",
      explanation: "Comparable means similar enough to be meaningfully compared.",
    },
    {
      id: 6,
      prompt: "The passage ______ traditional methods with newer approaches.",
      choices: ["apparent", "approximate", "contrast", "alter"],
      answer: "contrast",
      explanation: "Contrast means to show how two or more things differ.",
    },
    {
      id: 7,
      prompt: "The architect rejected ______ designs in favor of a flexible structure.",
      choices: ["approximate", "conventional", "alter", "apparent"],
      answer: "conventional",
      explanation: "Conventional means based on what is generally accepted or commonly done.",
    },
    {
      id: 8,
      prompt: "The effect ______ as the temperature decreased.",
      choices: ["diminish", "alter", "apparent", "approximate"],
      answer: "diminish",
      explanation: "Diminish means to make or become smaller, weaker, or less important.",
    },
    {
      id: 9,
      prompt: "The two species have ______ feeding patterns.",
      choices: ["alter", "apparent", "approximate", "distinct"],
      answer: "distinct",
      explanation: "Distinct means clearly different or separate.",
    },
    {
      id: 10,
      prompt: "The city experienced a ______ increase in public transit use.",
      choices: ["apparent", "approximate", "dramatic", "alter"],
      answer: "dramatic",
      explanation: "Dramatic means large, sudden, or striking.",
    },
    {
      id: 11,
      prompt: "The two measures are roughly ______ in accuracy.",
      choices: ["approximate", "equivalent", "alter", "apparent"],
      answer: "equivalent",
      explanation: "Equivalent means equal in value, meaning, or effect.",
    },
    {
      id: 12,
      prompt: "The final cost ______ the original estimate.",
      choices: ["exceed", "alter", "apparent", "approximate"],
      answer: "exceed",
      explanation: "Exceed means to be greater than a limit, amount, or expectation.",
    },
    {
      id: 13,
      prompt: "Energy prices ______ throughout the year.",
      choices: ["alter", "apparent", "approximate", "fluctuate"],
      answer: "fluctuate",
      explanation: "Fluctuate means to rise and fall irregularly.",
    },
    {
      id: 14,
      prompt: "The recovery was ______ rather than immediate.",
      choices: ["apparent", "approximate", "gradual", "alter"],
      answer: "gradual",
      explanation: "Gradual means happening slowly over time.",
    },
    {
      id: 15,
      prompt: "The new process produced only a ______ improvement.",
      choices: ["approximate", "marginal", "alter", "apparent"],
      answer: "marginal",
      explanation: "Marginal means small or limited in importance, amount, or effect.",
    }
  ],
};
