import type { SatDay } from "./types";

export const day01: SatDay = {
  day: 1,
  title: "Evidence and Reasoning",
  description:
    "Build the academic vocabulary used in claims, evidence, inference, interpretation, and argumentation.",
  words: [
    {
      word: "advocate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To publicly support or recommend a cause, policy, or idea.",
      example: "Many scientists advocate stricter environmental regulations.",
      synonyms: ["support", "promote", "endorse"],
      collocations: ["advocate reform", "advocate change", "advocate a policy"],
      wordFamily: ["advocate", "advocacy"],
      satTip: "As a noun, an advocate is a person who supports a cause.",
    },
    {
      word: "allocate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To distribute something for a particular purpose.",
      example: "The university allocated additional funding for research.",
      synonyms: ["assign", "distribute", "designate"],
      collocations: ["allocate resources", "allocate funds", "allocate time"],
      wordFamily: ["allocate", "allocation"],
    },
    {
      word: "attribute",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To regard something as being caused by a particular factor.",
      example: "The researchers attributed the improvement to better training.",
      synonyms: ["ascribe", "credit", "assign"],
      collocations: ["attribute success to", "attribute a change to"],
      satTip: "As a verb, attribute is usually followed by “to.”",
      wordFamily: ["attribute", "attribution"],
    },
    {
      word: "coherent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Logical, consistent, and easy to understand.",
      example: "The essay presents a coherent explanation of the evidence.",
      synonyms: ["logical", "consistent", "clear"],
      collocations: ["coherent argument", "coherent explanation", "coherent account"],
      wordFamily: ["coherent", "coherence", "coherently"],
    },
    {
      word: "compelling",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Strongly convincing or capable of attracting attention.",
      example: "The author offers compelling evidence for the new theory.",
      synonyms: ["convincing", "persuasive", "forceful"],
      collocations: ["compelling evidence", "compelling argument", "compelling reason"],
    },
    {
      word: "comprehensive",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Complete and including nearly all relevant details or aspects.",
      example: "The report provides a comprehensive review of the available research.",
      synonyms: ["thorough", "complete", "extensive"],
      collocations: ["comprehensive analysis", "comprehensive review", "comprehensive study"],
      wordFamily: ["comprehensive", "comprehensively"],
    },
    {
      word: "contradict",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To assert the opposite of a statement or conflict with it.",
      example: "The new results contradict the earlier conclusion.",
      synonyms: ["oppose", "conflict with", "dispute"],
      collocations: ["contradict a claim", "contradict the evidence"],
      wordFamily: ["contradict", "contradiction", "contradictory"],
    },
    {
      word: "convey",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To communicate or make an idea, feeling, or meaning known.",
      example: "The final paragraph conveys the author’s concern.",
      synonyms: ["communicate", "express", "transmit"],
      collocations: ["convey meaning", "convey information", "convey concern"],
      wordFamily: ["convey", "conveyance"],
    },
    {
      word: "infer",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To reach a conclusion based on evidence or reasoning.",
      example: "Readers can infer the speaker’s attitude from the final sentence.",
      synonyms: ["deduce", "conclude", "reason"],
      satTip: "The reader infers; the author or speaker implies.",
      wordFamily: ["infer", "inference", "inferential"],
    },
    {
      word: "imply",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To suggest something without stating it directly.",
      example: "The narrator’s hesitation implies that she doubts the plan.",
      synonyms: ["suggest", "indicate", "hint"],
      collocations: ["imply that", "strongly imply", "seem to imply"],
      satTip: "The writer implies; the reader infers.",
      wordFamily: ["imply", "implication", "implicit"],
    },
    {
      word: "hypothesis",
      partOfSpeech: "noun",
      rating: 5,
      definition: "A proposed explanation that can be tested through evidence or investigation.",
      example: "The experiment was designed to test the researcher’s hypothesis.",
      synonyms: ["proposition", "theory", "prediction"],
      collocations: ["test a hypothesis", "support a hypothesis", "reject a hypothesis"],
      wordFamily: ["hypothesis", "hypothesize", "hypothetical"],
    },
    {
      word: "evidence",
      partOfSpeech: "noun",
      rating: 5,
      definition: "Information or facts that support a conclusion, claim, or belief.",
      example: "The passage provides evidence that the policy improved attendance.",
      synonyms: ["proof", "support", "indication"],
      collocations: ["supporting evidence", "strong evidence", "provide evidence"],
      satTip: "Choose the evidence that directly supports the claim, not merely a related detail.",
      wordFamily: ["evidence", "evident", "evidently"],
    },
    {
      word: "assumption",
      partOfSpeech: "noun",
      rating: 5,
      definition: "An idea accepted as true without complete proof.",
      example: "The argument depends on the assumption that demand will remain stable.",
      synonyms: ["presumption", "belief", "supposition"],
      collocations: ["underlying assumption", "reasonable assumption", "challenge an assumption"],
      wordFamily: ["assume", "assumption"],
    },
    {
      word: "plausible",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Seemingly reasonable, believable, or likely to be true.",
      example: "The scientist offered a plausible explanation for the unusual pattern.",
      synonyms: ["credible", "believable", "reasonable"],
      collocations: ["plausible explanation", "plausible account", "seem plausible"],
      wordFamily: ["plausible", "plausibility", "plausibly"],
    },
    {
      word: "mitigate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To make something harmful, severe, or unpleasant less serious.",
      example: "Planting trees can help mitigate the effects of urban heat.",
      synonyms: ["reduce", "lessen", "alleviate"],
      collocations: ["mitigate risk", "mitigate damage", "mitigate the effects"],
      wordFamily: ["mitigate", "mitigation"],
    },
    {
      word: "substantial",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Large in amount, importance, value, or degree.",
      example: "The new method produced a substantial increase in efficiency.",
      synonyms: ["considerable", "significant", "major"],
      collocations: ["substantial evidence", "substantial increase", "substantial difference"],
      wordFamily: ["substantial", "substantially"],
    },
    {
      word: "significant",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Important, meaningful, or large enough to be noticeable.",
      example: "The researchers observed a significant difference between the groups.",
      synonyms: ["important", "meaningful", "notable"],
      collocations: ["significant effect", "significant difference", "statistically significant"],
      satTip: "In scientific passages, significant may refer to statistical importance.",
      wordFamily: ["significant", "significance", "significantly"],
    },
    {
      word: "consistent",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Remaining the same in behavior or agreeing with other facts or claims.",
      example: "The findings are consistent with the results of earlier studies.",
      synonyms: ["compatible", "steady", "uniform"],
      collocations: ["consistent with", "consistent pattern", "remain consistent"],
      wordFamily: ["consistent", "consistency", "consistently"],
    },
    {
      word: "interpret",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To explain or understand the meaning or significance of something.",
      example: "Historians interpret the document in different ways.",
      synonyms: ["explain", "understand", "analyze"],
      collocations: ["interpret data", "interpret a passage", "interpret the results"],
      wordFamily: ["interpret", "interpretation", "interpretive"],
    },
    {
      word: "illustrate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To clarify or demonstrate an idea by giving an example or visual representation.",
      example: "The graph illustrates the rapid growth of the city’s population.",
      synonyms: ["demonstrate", "show", "exemplify"],
      collocations: ["illustrate a point", "clearly illustrate", "illustrate how"],
      wordFamily: ["illustrate", "illustration", "illustrative"],
    },
    {
      word: "justify",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To show or prove that an action, claim, or decision is reasonable.",
      example: "The available evidence does not justify such a broad conclusion.",
      synonyms: ["defend", "support", "validate"],
      collocations: ["justify a claim", "justify a decision", "justify the conclusion"],
      wordFamily: ["justify", "justification", "justifiable"],
    },
    {
      word: "establish",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To show that something is true or certain through evidence or reasoning.",
      example: "The study establishes a link between sleep and memory.",
      synonyms: ["demonstrate", "confirm", "prove"],
      collocations: ["establish a connection", "establish a fact", "establish that"],
      wordFamily: ["establish", "establishment"],
    },
    {
      word: "indicate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To point to, suggest, or show that something is likely or true.",
      example: "The survey results indicate that public opinion has shifted.",
      synonyms: ["suggest", "show", "signal"],
      collocations: ["results indicate", "clearly indicate", "indicate that"],
      wordFamily: ["indicate", "indication", "indicative"],
    },
    {
      word: "evaluate",
      partOfSpeech: "verb",
      rating: 5,
      definition: "To judge the quality, importance, effectiveness, or value of something.",
      example: "The committee evaluated each proposal using the same criteria.",
      synonyms: ["assess", "judge", "appraise"],
      collocations: ["evaluate evidence", "evaluate effectiveness", "carefully evaluate"],
      wordFamily: ["evaluate", "evaluation", "evaluative"],
    },
    {
      word: "relevant",
      partOfSpeech: "adjective",
      rating: 5,
      definition: "Closely connected to the subject or question being considered.",
      example: "Only evidence relevant to the author’s claim should be included.",
      synonyms: ["applicable", "pertinent", "related"],
      collocations: ["relevant evidence", "directly relevant", "relevant information"],
      satTip: "A detail can be true but still irrelevant to the specific question.",
      wordFamily: ["relevant", "relevance", "irrelevant"],
    },
  ],
  questions: [
    {
      id: 1,
      prompt: "Many scientists ______ stricter regulations to reduce plastic pollution.",
      choices: ["allocate", "advocate", "infer", "contradict"],
      answer: "advocate",
      explanation: "Advocate means to publicly support or recommend a policy or idea.",
    },
    {
      id: 2,
      prompt: "From the evidence, the detective could ______ that the suspect had left earlier.",
      choices: ["imply", "infer", "allocate", "convey"],
      answer: "infer",
      explanation: "The detective reaches a conclusion from evidence, so infer is correct.",
    },
    {
      id: 3,
      prompt: "The study’s latest results appear to ______ its original conclusion.",
      choices: ["contradict", "allocate", "advocate", "convey"],
      answer: "contradict",
      explanation: "Contradict means to conflict with or assert the opposite of a claim.",
    },
    {
      id: 4,
      prompt: "The committee decided to ______ more funding to the tutoring program.",
      choices: ["infer", "allocate", "contradict", "advocate"],
      answer: "allocate",
      explanation: "Allocate means to distribute resources for a particular purpose.",
    },
    {
      id: 5,
      prompt: "The final image helps ______ the poet’s sense of isolation.",
      choices: ["attribute", "convey", "allocate", "infer"],
      answer: "convey",
      explanation: "Convey means to communicate or express an idea or feeling.",
    },
    {
      id: 6,
      prompt: "The researcher proposed a ______ explanation that could be tested experimentally.",
      choices: ["coherent", "hypothesis", "relevant", "mitigate"],
      answer: "hypothesis",
      explanation: "A hypothesis is a proposed explanation that can be tested.",
    },
    {
      id: 7,
      prompt: "Although the account cannot be proven, it is ______ given the available facts.",
      choices: ["plausible", "comprehensive", "contradictory", "substantial"],
      answer: "plausible",
      explanation: "Plausible means reasonable or believable.",
    },
    {
      id: 8,
      prompt: "The city planted additional trees to ______ the effects of extreme heat.",
      choices: ["illustrate", "mitigate", "establish", "evaluate"],
      answer: "mitigate",
      explanation: "Mitigate means to make something harmful less severe.",
    },
    {
      id: 9,
      prompt: "The graph helps ______ the relationship between income and access to transportation.",
      choices: ["illustrate", "justify", "attribute", "imply"],
      answer: "illustrate",
      explanation: "Illustrate means to clarify or demonstrate an idea.",
    },
    {
      id: 10,
      prompt: "The evidence is not strong enough to ______ the author’s broad conclusion.",
      choices: ["convey", "justify", "allocate", "infer"],
      answer: "justify",
      explanation: "Justify means to show that a conclusion is reasonable or supported.",
    },
    {
      id: 11,
      prompt: "The findings are ______ with earlier studies that reported the same pattern.",
      choices: ["consistent", "comprehensive", "compelling", "significant"],
      answer: "consistent",
      explanation: "Consistent with means agreeing with or compatible with.",
    },
    {
      id: 12,
      prompt: "The passage gives a ______ overview of the debate, including all major positions.",
      choices: ["plausible", "relevant", "comprehensive", "substantial"],
      answer: "comprehensive",
      explanation: "Comprehensive means complete and wide-ranging.",
    },
    {
      id: 13,
      prompt: "The survey results ______ that younger voters have different priorities.",
      choices: ["indicate", "mitigate", "justify", "allocate"],
      answer: "indicate",
      explanation: "Indicate means to show or suggest that something is true.",
    },
    {
      id: 14,
      prompt: "Before accepting the claim, readers should ______ the quality of its supporting evidence.",
      choices: ["establish", "evaluate", "convey", "advocate"],
      answer: "evaluate",
      explanation: "Evaluate means to judge quality, value, or effectiveness.",
    },
    {
      id: 15,
      prompt: "Which detail is most ______ to the question of whether the new method saves time?",
      choices: ["compelling", "coherent", "relevant", "substantial"],
      answer: "relevant",
      explanation: "Relevant means directly connected to the issue being considered.",
    },
  ],
};
