import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const authorsPurposeExpansion3Questions = [
  createExpansionQuestion({
    id: "rexp3-purpose-01",
    passage: "A paragraph explains that conventional sensors fail at very low temperatures, then introduces a new sensor designed to operate reliably in extreme cold.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To show that conventional sensors work best in all conditions.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To introduce a technology that addresses a limitation of conventional sensors.", "The paragraph establishes a limitation and presents a response to it."),
      choice("To argue that temperature cannot be measured.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To provide a biography of a sensor designer.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The paragraph establishes a limitation and presents a response to it.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-02",
    passage: "The author describes a railway station's original commercial role and then explains how its restoration preserved architectural details while converting it into a community center.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To explain how a historic building was adapted for a new use while retaining features of its past.", "The text focuses on adaptive reuse and preservation."),
      choice("To argue that all railway stations should close.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To list train schedules.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To compare ticket prices across cities.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The text focuses on adaptive reuse and preservation.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-03",
    passage: "A critic notes that a painter often left portions of the canvas visibly rough, arguing that these unfinished-looking areas draw attention to the act of painting itself.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To prove that the painter lacked time to finish any work.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To describe how canvas is manufactured.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To rank painters by popularity.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To explain how a stylistic feature shapes viewers' attention.", "The author interprets the effect of the rough areas."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The author interprets the effect of the rough areas.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-04",
    passage: "The passage reports that people are more likely to use public plazas when movable chairs are available, then suggests that the ability to rearrange seating gives visitors greater control over social distance.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To show that fixed chairs are always uncomfortable.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To describe the history of chair manufacturing.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To offer an explanation for why movable seating may encourage plaza use.", "The second idea explains the observed association."),
      choice("To argue that plazas should contain no furniture.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The second idea explains the observed association.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-05",
    passage: "The author presents evidence that repair subsidies extended the life of household appliances and then notes that longer product life can reduce replacement spending.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To argue that households should replace appliances more often.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To connect a repair policy with a possible economic consequence for households.", "The passage links policy, product longevity, and spending."),
      choice("To show that appliances cannot be repaired.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To explain how to manufacture refrigerators.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The passage links policy, product longevity, and spending.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-06",
    passage: "The passage describes an online records portal and emphasizes that searchable text, not merely scanned images, allows residents to locate specific information efficiently.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To distinguish formal availability of records from practical usability.", "The contrast centers on access versus usability."),
      choice("To argue against publishing records.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To describe scanner hardware.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To claim that residents never search public records.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The contrast centers on access versus usability.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-07",
    passage: "The author summarizes evidence that urban ponds support insect diversity but cautions that ponds near heavily traveled roads contain fewer sensitive species.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To prove that roads increase all insect populations.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To argue that cities contain no ponds.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To describe only road construction.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To present a benefit of urban ponds while identifying a condition that can limit it.", "The passage balances a general benefit with a limiting factor."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The passage balances a general benefit with a limiting factor.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-08",
    passage: "After quoting an official proclamation promising land access, the author cites application fees that excluded many low-income residents.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To prove that no proclamation existed.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To argue that fees always increase access.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To show that a formal promise of access could be limited by practical barriers.", "The evidence contrasts legal language with real-world barriers."),
      choice("To explain how land is surveyed.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The evidence contrasts legal language with real-world barriers.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-09",
    passage: "The narrator describes a familiar street using increasingly strange comparisons as night falls, making ordinary storefronts seem unfamiliar.",
    prompt: "What is the author's main purpose in using the changing comparisons?",
    choices: [
      choice("To explain how stores set prices.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To convey the narrator's growing sense of unease.", "The figurative shift tracks an emotional shift."),
      choice("To provide exact architectural measurements.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To show that the street physically moves.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The figurative shift tracks an emotional shift.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-10",
    passage: "A passage describes a successful laboratory test of a biodegradable film, then emphasizes that humidity and sunlight vary much more outdoors.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To caution that laboratory performance may not fully predict real-world performance.", "The author qualifies the lab result by noting environmental differences."),
      choice("To prove that the film fails outdoors.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To explain how sunlight is produced.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To argue that laboratory tests are never useful.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The author qualifies the lab result by noting environmental differences.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-11",
    passage: "The author reports that neighborhoods with community gardens show stronger social ties but asks whether already-connected neighborhoods are simply more likely to create gardens.",
    prompt: "What is the author's main purpose in posing the question?",
    choices: [
      choice("To deny that gardens exist.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To define social ties.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To show that neighborhoods are randomly assigned gardens.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To highlight an alternative explanation for the observed association.", "The question raises reverse causation."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The question raises reverse causation.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-12",
    passage: "The passage notes that sales rose after a price cut but also that a competitor closed during the same month.",
    prompt: "What is the author's main purpose in mentioning the competitor?",
    choices: [
      choice("To explain how competitors set salaries.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To show that no market changes occurred.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To identify another factor that could have contributed to the sales increase.", "The competitor's closure is a competing causal factor."),
      choice("To prove the price cut reduced sales.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The competitor's closure is a competing causal factor.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-13",
    passage: "The author first interprets repeated windows in a novel as symbols of possibility, then points out that several windows are barred.",
    prompt: "What is the author's main purpose in mentioning the barred windows?",
    choices: [
      choice("To show that symbols always have one meaning.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To complicate a single positive interpretation of the symbol.", "The contrary examples broaden the interpretation."),
      choice("To prove that the novel contains no windows.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To describe window manufacturing.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The contrary examples broaden the interpretation.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-14",
    passage: "A policy analysis praises digital applications for reducing travel to government offices but notes that residents without reliable internet may face new barriers.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To evaluate a reform by considering both its convenience and its accessibility limits.", "The author weighs a benefit against an access problem."),
      choice("To argue that all government services should close.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To explain how internet cables are made.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To claim that digital applications help every resident equally.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The author weighs a benefit against an access problem.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-15",
    passage: "The author describes an algorithm that performs well on carefully cropped images but less accurately on field photographs with shadows and overlapping objects.",
    prompt: "What is the author's main purpose?",
    choices: [
      choice("To prove that algorithms cannot analyze images.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To show that shadows improve every prediction.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To compare two camera brands.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To illustrate a gap between controlled-test performance and performance under realistic conditions.", "The contrast emphasizes generalization limits."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The contrast emphasizes generalization limits.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-purpose-16",
    passage: "The author compares a census with letters describing temporary evacuation after a flood.",
    prompt: "What is the author's main purpose in combining these sources?",
    choices: [
      choice("To show that the flood increased population.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To argue that letters and censuses are identical sources.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("To suggest that a recorded population decline may include temporary displacement.", "The second source changes how the census decline can be interpreted."),
      choice("To prove that censuses never count people.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Author's Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Ask what the author is doing with the information, not merely what topic is mentioned.",
      "The second source changes how the census decline can be interpreted.",
      "Prefer the choice that captures the passage's rhetorical goal without exaggeration.",
    ],
  }),
];
