import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const commandOfEvidenceExpansion3Questions = [
  createExpansionQuestion({
    id: "rexp3-evidence-01",
    passage: "A study of rooftop gardens found that plots with flowering herbs attracted more bee species than plots containing only grass. The researchers counted 14 bee species in herb plots and 6 in grass plots.",
    prompt: "Which finding from the text most directly supports the claim that flowering herbs can increase bee diversity?",
    choices: [
      choice("Researchers counted bees in every plot.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Grass plots contained plants.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Herb plots contained 14 bee species, compared with 6 in grass plots.", "The numerical comparison directly supports greater bee diversity in herb plots."),
      choice("Both types of plots were located on rooftops.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The numerical comparison directly supports greater bee diversity in herb plots.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-02",
    passage: "A historian argues that a port remained commercially active after a major storm. Shipping logs show that 82 vessels entered the port during the following month, compared with 87 in the same month a year earlier.",
    prompt: "Which detail best supports the historian's argument?",
    choices: [
      choice("The logs covered two different years.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The number of arriving vessels fell only from 87 to 82 after the storm.", "The small change in vessel arrivals is direct evidence of continued commercial activity."),
      choice("A storm struck the port.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The historian studied shipping logs.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The small change in vessel arrivals is direct evidence of continued commercial activity.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-03",
    passage: "Researchers suggest that providing exact bus arrival times reduces perceived waiting. Riders using real-time displays rated waits as less frustrating even though measured wait times were unchanged.",
    prompt: "Which finding best supports the researchers' suggestion?",
    choices: [
      choice("Riders with real-time information reported less frustration despite waiting the same amount of time.", "The contrast isolates perceived waiting rather than actual duration."),
      choice("Bus routes had scheduled arrival times.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Researchers measured actual waits.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Some riders used buses regularly.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The contrast isolates perceived waiting rather than actual duration.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-04",
    passage: "An economist claims that a reusable-container deposit encouraged returns. Before the deposit, 48% of containers were returned; afterward, 76% were returned.",
    prompt: "Which evidence most directly supports the economist's claim?",
    choices: [
      choice("The program involved reusable containers.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Deposits can be measured in money.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Return rates were recorded twice.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The return rate rose from 48% to 76% after the deposit was introduced.", "The before-and-after increase directly supports the claim."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The before-and-after increase directly supports the claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-05",
    passage: "A curator argues that visitors spent more time with paintings when labels included questions. Average viewing time was 31 seconds with question-based labels and 19 seconds with descriptive labels.",
    prompt: "Which detail best supports the curator's argument?",
    choices: [
      choice("The museum displayed paintings.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Visitors could read labels.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Average viewing time was 12 seconds longer with question-based labels.", "The measured viewing-time difference directly supports the claim."),
      choice("Both label types contained words.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The measured viewing-time difference directly supports the claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-06",
    passage: "A team proposes that a reflective pavement coating reduces surface heating. At noon, coated pavement averaged 41\u00b0C while nearby uncoated pavement averaged 49\u00b0C.",
    prompt: "Which finding best supports the team's proposal?",
    choices: [
      choice("Researchers used temperature measurements.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Coated pavement was 8\u00b0C cooler than uncoated pavement at noon.", "The temperature difference is the relevant evidence for reduced heating."),
      choice("Both surfaces were measured at noon.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The pavement was outdoors.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The temperature difference is the relevant evidence for reduced heating.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-07",
    passage: "A scholar argues that a newspaper reached readers beyond its home city. Subscription records list customers in twelve other towns by 1895.",
    prompt: "Which evidence best supports the scholar's argument?",
    choices: [
      choice("The newspaper had subscribers in twelve towns outside its home city.", "Subscribers outside the home city directly demonstrate geographic reach."),
      choice("The newspaper existed in 1895.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Subscription records were preserved.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The paper was printed in a city.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "Subscribers outside the home city directly demonstrate geographic reach.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-08",
    passage: "Researchers claim that a new filter removes fine particles more effectively. In identical tests, the new filter removed 93% of fine particles and the standard filter removed 78%.",
    prompt: "Which result most directly supports the claim?",
    choices: [
      choice("Both filters were tested.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Fine particles were present.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The standard filter removed some particles.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The new filter removed 15 percentage points more fine particles than the standard filter.", "The direct performance comparison supports greater effectiveness."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The direct performance comparison supports greater effectiveness.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-09",
    passage: "A study suggests that short retrieval quizzes improve later recall. Students who completed the quizzes recalled 71% of terms a week later, while students who only reread the terms recalled 54%.",
    prompt: "Which evidence best supports the study's suggestion?",
    choices: [
      choice("Recall was tested one week later.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Students were enrolled in a study.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The quiz group recalled 71% of terms versus 54% for the rereading group.", "The between-group recall difference is the evidence relevant to the claim."),
      choice("Both groups studied the same subject.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The between-group recall difference is the evidence relevant to the claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-10",
    passage: "Analysts argue that extending market hours increased sales opportunities for small vendors. After the change, average Saturday transactions per vendor rose from 23 to 34.",
    prompt: "Which detail best supports the analysts' argument?",
    choices: [
      choice("Analysts examined transactions.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Average Saturday transactions increased by 11 per vendor after hours were extended.", "The increase in transactions is direct evidence of more sales opportunities."),
      choice("The market operated on Saturdays.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Small vendors sold products.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The increase in transactions is direct evidence of more sales opportunities.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-11",
    passage: "A biologist hypothesizes that shade helps seedlings conserve water. After six hours, shaded seedlings retained 68% of their initial soil moisture, whereas unshaded seedlings retained 51%.",
    prompt: "Which finding best supports the hypothesis?",
    choices: [
      choice("Soil around shaded seedlings retained 17 percentage points more moisture.", "Higher retained moisture under shade supports the conservation hypothesis."),
      choice("Both groups were observed for six hours.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Seedlings grew in soil.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Moisture was measured as a percentage.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "Higher retained moisture under shade supports the conservation hypothesis.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-12",
    passage: "A city official argues that posting permit applications online improved access. The number of applications viewed by residents rose from 1,200 to 3,900 in the first six months after the portal launched.",
    prompt: "Which evidence best supports the official's argument?",
    choices: [
      choice("Permits existed before the portal.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The city tracked six months of data.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Residents could submit applications.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Resident views of permit applications more than tripled after the online portal launched.", "The large increase in views directly supports improved access."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The large increase in views directly supports improved access.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-13",
    passage: "A researcher claims that audio guides encouraged visitors to explore more galleries. Visitors using guides entered an average of 7.2 galleries, compared with 5.1 for visitors without guides.",
    prompt: "Which finding best supports the claim?",
    choices: [
      choice("Some visitors did not use guides.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Gallery visits were counted.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Guide users visited about two more galleries on average.", "The difference in galleries visited directly supports the claim."),
      choice("The museum had multiple galleries.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The difference in galleries visited directly supports the claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-14",
    passage: "A materials scientist argues that a coating slows corrosion. After 30 days in saltwater, coated samples lost 1.8% of their mass while uncoated samples lost 5.6%.",
    prompt: "Which result best supports the argument?",
    choices: [
      choice("Mass loss was expressed as a percentage.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Coated samples lost substantially less mass than uncoated samples.", "Lower mass loss is direct evidence of slower corrosion."),
      choice("Both samples were exposed to saltwater.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The test lasted 30 days.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "Lower mass loss is direct evidence of slower corrosion.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-15",
    passage: "Researchers propose that quieter study spaces improve concentration. Participants in a quiet room completed 18% more proofreading items correctly than participants exposed to intermittent conversation.",
    prompt: "Which finding best supports the proposal?",
    choices: [
      choice("Participants in the quiet room completed 18% more items correctly.", "The performance difference directly supports the concentration claim."),
      choice("Participants proofread written material.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Conversation occurred intermittently.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The experiment used two rooms.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The performance difference directly supports the concentration claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-16",
    passage: "A report argues that a shared cold-storage facility reduced produce waste. Participating farms reported spoilage of 7% after the facility opened, down from 18% before.",
    prompt: "Which evidence most directly supports the report's argument?",
    choices: [
      choice("The facility was shared.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Farms sold produce.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Spoilage was reported as a percentage.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Reported spoilage fell by 11 percentage points after cold storage became available.", "The decline in spoilage directly supports reduced waste."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The decline in spoilage directly supports reduced waste.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-17",
    passage: "A researcher claims that adding native plants improved storm-water absorption. Test plots with native plants absorbed 22 liters during a simulated storm, compared with 13 liters for turf plots.",
    prompt: "Which result best supports the claim?",
    choices: [
      choice("The experiment measured liters.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Turf is a type of ground cover.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Native-plant plots absorbed 9 liters more water than turf plots.", "The absorption difference directly supports the claim."),
      choice("Both plot types received simulated rain.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The absorption difference directly supports the claim.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-18",
    passage: "A historian argues that a community library served as more than a place to borrow books. Meeting records show that labor groups, language classes, and neighborhood committees regularly used its rooms.",
    prompt: "Which evidence best supports the historian's argument?",
    choices: [
      choice("The building contained rooms.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Several kinds of community groups regularly met in the library.", "Use by diverse groups demonstrates functions beyond lending."),
      choice("The library lent books.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Meeting records were preserved.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "History",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "Use by diverse groups demonstrates functions beyond lending.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-evidence-19",
    passage: "Researchers argue that translated election guides expanded access for multilingual voters. Requests for translated guides rose to 8,400, and surveys showed that 73% of users found them helpful.",
    prompt: "Which evidence best supports the claim that the guides were useful to their intended audience?",
    choices: [
      choice("Nearly three-quarters of surveyed users said the translated guides were helpful.", "The user evaluation directly addresses usefulness."),
      choice("The guides concerned elections.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("8,400 guides were requested.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Surveys can collect opinions.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Command of Evidence",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Locate the claim named in the question.",
      "The user evaluation directly addresses usefulness.",
      "Choose evidence that directly bears on that claim rather than merely repeating background information.",
    ],
  }),
];
