import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const inferenceExpansion3Questions = [
  createExpansionQuestion({
    id: "rexp3-inference-01",
    passage: "A desert plant opens its stomata mainly at night, when temperatures are lower and humidity is higher. This behavior reduces the amount of water lost while the plant takes in carbon dioxide.",
    prompt: "Which inference is best supported by the text?",
    choices: [
      choice("Opening stomata at night helps the plant conserve water in a dry environment.", "The timing is explicitly connected to reduced water loss."),
      choice("The plant cannot take in carbon dioxide at night.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Humidity is always lower at night.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The plant grows only during daylight.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The timing is explicitly connected to reduced water loss.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-02",
    passage: "A merchant's letters complain repeatedly about muddy roads, while his account book shows fewer sales to distant towns during the same rainy season.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The merchant stopped selling goods locally.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Rain increased sales in distant towns.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The account book was written by another merchant.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Poor road conditions likely interfered with the merchant's long-distance trade.", "The two sources connect transportation difficulty with reduced distant sales."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The two sources connect transportation difficulty with reduced distant sales.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-03",
    passage: "Participants were more likely to return borrowed tools when reminder messages included the tool's due date than when reminders simply asked for a return.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("General reminders always reduce returns.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Due dates make tools easier to use.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Specific deadline information may make reminder messages more effective.", "The difference between message types supports the role of specificity."),
      choice("People return tools only when threatened.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The difference between message types supports the role of specificity.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-04",
    passage: "A museum placed sketches beside finished sculptures. Visitors spent more time at displays containing both objects than at displays containing sculptures alone.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("Every visitor understood the artist's exact intentions.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Seeing preparatory work may encourage visitors to examine finished works more closely.", "Longer viewing at combined displays supports a cautious inference about engagement."),
      choice("Visitors preferred sketches because sculptures were removed.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Sketches always take longer to make than sculptures.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "Longer viewing at combined displays supports a cautious inference about engagement.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-05",
    passage: "A new battery retained more capacity than a standard battery after repeated charging, but it was tested at a lower temperature.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The capacity difference cannot confidently be attributed to battery design alone.", "Different test conditions introduce a plausible confound."),
      choice("The new battery certainly performs worse.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Temperature never affects batteries.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The standard battery was not tested.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "Different test conditions introduce a plausible confound.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-06",
    passage: "After a caf\u00e9 introduced mobile ordering, lunchtime sales increased. During the same month, a large office opened next door.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("Mobile ordering definitely caused the entire increase.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The new office reduced the number of nearby customers.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The caf\u00e9 stopped serving lunch.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The sales increase may have resulted from more than one change.", "Two simultaneous changes prevent a single-cause conclusion."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "Two simultaneous changes prevent a single-cause conclusion.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-07",
    passage: "Birds fitted with lightweight tracking tags followed the same migration route as untagged birds, but tagged birds rested slightly longer at one stopover.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("Untagged birds never rested.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The tracking tags made birds fly faster.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The tags may have had a small effect on behavior even though the overall route was unchanged.", "The route was stable, but rest behavior differed."),
      choice("The tags completely changed migration routes.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The route was stable, but rest behavior differed.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-08",
    passage: "A city moved permit applications online. Overall applications rose, but applications from neighborhoods with low broadband access did not.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The city eliminated permit requirements.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Online access may not benefit all neighborhoods equally when internet access differs.", "The uneven response aligns with unequal internet access."),
      choice("Broadband access is unrelated to online services.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Every neighborhood submitted more applications.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The uneven response aligns with unequal internet access.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-09",
    passage: "Two tree species grew equally well under normal rainfall. Under drought, Species A maintained growth while Species B slowed sharply.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("Species A may be better adapted to low-water conditions.", "The drought-specific performance supports greater tolerance."),
      choice("Species B always grows faster.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Normal rainfall prevents all tree growth.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Species A requires more water during drought.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The drought-specific performance supports greater tolerance.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-10",
    passage: "An official report calls a protest brief, but diaries describe disruptions continuing for several weeks.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The diaries prove the protest never occurred.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Official reports are always false.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The protest lasted exactly one day.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The official report may understate the duration or broader effects of the protest.", "The sources conflict in a way that supports a cautious qualification."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The sources conflict in a way that supports a cautious qualification.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-11",
    passage: "Students who chose optional tutoring improved more than students who did not choose it. The study did not randomly assign tutoring.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The students were randomly assigned.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Optional programs can never help students.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("Motivation or other preexisting differences may partly explain the improvement.", "Self-selection limits causal interpretation."),
      choice("Tutoring necessarily caused all improvement.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "Self-selection limits causal interpretation.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp3-inference-12",
    passage: "A poet removes regional expressions from later editions published for a national audience.",
    prompt: "Which inference is best supported?",
    choices: [
      choice("The first edition was never published.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("The revisions may have been intended partly to make the poems more broadly accessible.", "The timing and audience support a cautious marketing/accessibility inference."),
      choice("The poet disliked every regional expression.", "This choice is not adequately supported by the passage or does not answer the question asked."),
      choice("National readers could not understand any regional language.", "This choice is not adequately supported by the passage or does not answer the question asked."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Inference",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 80,
    tags: ["reading-expansion-pack-3", "coverage-gap"],
    walkthrough: [
      "Combine only facts supplied by the passage.",
      "The timing and audience support a cautious marketing/accessibility inference.",
      "Choose the cautious conclusion that follows from the evidence rather than a stronger claim the text cannot establish.",
    ],
  }),
];
