import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const concisionReplacementQuestions = [
  createExpansionQuestion({
    id: "repl4-concision-01",
    passage: "The portable sensor is small in size and easy to carry.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The portable sensor is a sensor that is small in size and easy to carry.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Being small in size, the portable sensor is also easy to carry around.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The portable sensor is small and easy to carry.", "\u201cSmall\u201d already expresses size, so \u201cin size\u201d is unnecessary."),
      choice("The portable sensor is small in its size and easy for carrying.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cSmall\u201d already expresses size, so \u201cin size\u201d is unnecessary.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-02",
    passage: "The archive contains letters that were written by local merchants.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The archive is a place containing letters that were written by merchants locally.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The archive contains letters written by local merchants.", "Removing \u201cthat were\u201d shortens the sentence without changing its meaning."),
      choice("The archive contains letters that local merchants had written themselves.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The archive contains in it letters written by local merchants.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "Removing \u201cthat were\u201d shortens the sentence without changing its meaning.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-03",
    passage: "The sculpture is circular in shape and made of bronze.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The circular bronze sculpture is displayed in the lobby.", "The revision expresses the same information directly and without redundancy."),
      choice("The sculpture, which is circular in shape and made of bronze, is displayed in the lobby.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The sculpture is a circular shape made out of bronze and is displayed in the lobby.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Displayed in the lobby is the sculpture, which has a circular shape and bronze material.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The revision expresses the same information directly and without redundancy.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-04",
    passage: "The survey was conducted in order to understand residents' travel habits.",
    prompt: "Which choice most effectively revises the sentence to make it more concise?",
    choices: [
      choice("The survey was conducted for the purpose of understanding residents' travel habits.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("In order to understand the travel habits of residents, the survey was conducted.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The survey that was conducted was done to understand how residents travel.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The survey was conducted to understand residents' travel habits.", "\u201cTo understand\u201d states purpose more concisely than \u201cin order to understand.\u201d"),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cTo understand\u201d states purpose more concisely than \u201cin order to understand.\u201d",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-05",
    passage: "Because the device is lightweight in weight, researchers can carry it into remote areas.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Due to the fact that the device is lightweight in its overall weight, researchers can carry it into remote areas.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The device, being lightweight in weight, can be carried by researchers into remote areas.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Because the device is lightweight, researchers can carry it into remote areas.", "\u201cLightweight\u201d already refers to weight."),
      choice("Because the device has a light weight in weight, researchers can carry it into remote areas.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cLightweight\u201d already refers to weight.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-06",
    passage: "The firm reduced costs by eliminating expenses that were unnecessary and not needed.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("Costs were reduced by the firm when it eliminated expenses not needed because they were unnecessary.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The firm reduced costs by eliminating unnecessary expenses.", "The revision removes duplication and uses a direct verb phrase."),
      choice("The firm reduced costs by eliminating expenses that were unnecessary and also not needed.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The firm reduced its costs through the elimination of expenses that were unnecessary.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The revision removes duplication and uses a direct verb phrase.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-07",
    passage: "The committee reached a unanimous agreement in which every member agreed.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The committee reached a unanimous agreement.", "\u201cUnanimous\u201d already means that every member agreed."),
      choice("The committee reached an agreement that was unanimous because every member agreed.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Every member of the committee reached an agreement unanimously.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The committee came to an agreement that all members agreed to.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cUnanimous\u201d already means that every member agreed.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-08",
    passage: "The narrator returns back to the village after ten years away.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The narrator returns back again to the village after ten years away.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("After ten years away, the narrator makes a return back to the village.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The narrator goes back in return to the village after ten years.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The narrator returns to the village after ten years away.", "\u201cReturns\u201d already includes the meaning of \u201cback.\u201d"),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cReturns\u201d already includes the meaning of \u201cback.\u201d",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-09",
    passage: "The critic argues that the novel's fragmented chronology is a feature that serves the function of reflecting the narrator's uncertain memory.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("According to the critic, the chronology, which is fragmented, has the function of reflecting uncertain memory.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The novel's fragmented chronology is argued by the critic to be a feature whose function is reflection of uncertainty.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The critic argues that the novel's fragmented chronology reflects the narrator's uncertain memory.", "The direct verb \u201creflects\u201d replaces an abstract and wordy phrase."),
      choice("The critic makes the argument that the fragmented chronology serves the function of reflecting uncertain memory.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The direct verb \u201creflects\u201d replaces an abstract and wordy phrase.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-10",
    passage: "The findings provide an indication that the treatment may possibly reduce recovery time.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The study provides findings that give an indication about a possible reduction in recovery time.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The findings suggest that the treatment may reduce recovery time.", "\u201cSuggest\u201d is more direct, and \u201cmay\u201d already expresses possibility."),
      choice("The findings provide an indication suggesting that the treatment may possibly reduce recovery time.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The findings are indicative of the possibility that recovery time may possibly be reduced.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "\u201cSuggest\u201d is more direct, and \u201cmay\u201d already expresses possibility.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-11",
    passage: "The policy had the effect of causing firms to delay investments until a later time.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The policy caused firms to delay investments.", "The direct verb \u201ccaused\u201d removes unnecessary nominalization and repetition."),
      choice("The policy had an effect that caused firms to delay investments until later in time.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Firms delayed investments until a later time as an effect caused by the policy.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The effect of the policy was a causing of delays in investments by firms.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The direct verb \u201ccaused\u201d removes unnecessary nominalization and repetition.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-concision-12",
    passage: "The report recommends the implementation of a system for the purpose of tracking applications.",
    prompt: "Which choice most effectively revises the sentence?",
    choices: [
      choice("The report recommends implementation of a system that has the purpose of tracking applications.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For the purpose of tracking applications, the report gives a recommendation for system implementation.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The report's recommendation is for the implementation of a tracking system for applications.", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("The report recommends implementing a system to track applications.", "Active verb forms make the sentence more concise."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Concision",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "Active verb forms make the sentence more concise.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
];