import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const transitionsReplacementQuestions = [
  createExpansionQuestion({
    id: "repl4-transitions-01",
    passage: "The first trial produced inconsistent readings. _____, the researchers recalibrated the instrument.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Therefore,", "The recalibration is a consequence of the inconsistent readings."),
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Meanwhile,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Similarly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The recalibration is a consequence of the inconsistent readings.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-02",
    passage: "The bridge was built for rail traffic. _____, it later became a pedestrian walkway.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For instance,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Likewise,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Consequently,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("However,", "The later use contrasts with the bridge's original purpose."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The later use contrasts with the bridge's original purpose.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-03",
    passage: "The exhibit includes paintings from the 1930s. _____, it features sculptures from the same decade.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Nevertheless,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("As a result,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("In addition,", "The sculptures are an additional feature of the exhibit."),
      choice("Instead,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The sculptures are an additional feature of the exhibit.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-04",
    passage: "The store lowered delivery fees. _____, online orders increased.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Meanwhile,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("As a result,", "The increase in orders is presented as a consequence of lower fees."),
      choice("In contrast,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The increase in orders is presented as a consequence of lower fees.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-05",
    passage: "The coating performed well in dry laboratory tests. _____, its performance declined during outdoor tests in heavy rain.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("By contrast,", "The outdoor result contrasts with the laboratory result."),
      choice("Consequently,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("In addition,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The outdoor result contrasts with the laboratory result.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-06",
    passage: "Real-time arrival displays did not reduce actual bus wait times. _____, riders reported that waiting felt less uncertain.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Therefore,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Specifically,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Similarly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Nevertheless,", "The perceived benefit occurred despite unchanged wait times."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The perceived benefit occurred despite unchanged wait times.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-07",
    passage: "The city published more records online. _____, many documents were image files that could not be searched.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Likewise,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("However,", "The second sentence presents a limitation of the apparent improvement."),
      choice("Accordingly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The second sentence presents a limitation of the apparent improvement.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-08",
    passage: "Official reports describe the strike as brief. _____, workers' diaries refer to disruptions lasting several weeks.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Moreover,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("In contrast,", "The diaries conflict with the official description."),
      choice("As a result,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For instance,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The diaries conflict with the official description.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-09",
    passage: "The experimental material retained more strength after cooling. _____, the materials were tested at different humidity levels, so the comparison was not fully controlled.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Even so,", "The final sentence qualifies the apparent advantage despite the preceding result."),
      choice("Accordingly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("In the same way,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The final sentence qualifies the apparent advantage despite the preceding result.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-10",
    passage: "Sales rose after the company reduced prices. _____, a major competitor closed during the same month, providing another possible explanation.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Therefore,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For instance,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Similarly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("However,", "The competitor's closure complicates the causal interpretation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The competitor's closure complicates the causal interpretation.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-11",
    passage: "Participants who chose flexible schedules reported greater satisfaction. _____, because employees selected their own schedules, the study could not rule out self-selection.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Likewise,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Still,", "The second sentence qualifies the result with a methodological limitation."),
      choice("Consequently,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The second sentence qualifies the result with a methodological limitation.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
  createExpansionQuestion({
    id: "repl4-transitions-12",
    passage: "One scholar interprets the novel's repeated doors as symbols of opportunity. _____, another scholar notes that many doors are locked or lead back to rooms already visited.",
    prompt: "Which choice completes the text with the most logical transition?",
    choices: [
      choice("Similarly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("Conversely,", "The second scholar offers an opposing interpretation."),
      choice("Accordingly,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
      choice("For example,", "This choice is unnecessarily wordy, redundant, or does not express the required logical relationship."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Transitions",
    domain: "Expression of Ideas",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-11"],
    walkthrough: [
      "Identify either the repeated meaning or the logical relationship between the ideas.",
      "The second scholar offers an opposing interpretation.",
      "Choose the concise option or transition that preserves the intended meaning.",
    ],
  }),
];