import { choice, createExpansionQuestion } from "./factory";

export const centralIdeasExpansionQuestions = [
  createExpansionQuestion({
    id: "rexp1-central-01",
    passage: "Mangrove seedlings planted near existing roots survived storms better than seedlings planted on exposed mudflats. The roots slowed moving water and trapped sediment around the young plants.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Existing mangrove roots can improve conditions for young seedlings during storms.", "Slower water and trapped sediment explain why seedlings near roots survived better."),
      choice("Mangrove seedlings can survive only when planted by people.", "This choice contradicts or overstates a detail in the passage."),
      choice("Storms always increase sediment around mangrove forests.", "This choice contradicts or overstates a detail in the passage."),
      choice("Exposed mudflats contain more mature roots than mangrove forests.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "Slower water and trapped sediment explain why seedlings near roots survived better.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-02",
    passage: "A town restored its nineteenth-century train station as a library. Rather than replacing the old ticket windows, designers converted them into small reading desks, preserving a visible link to the building's former use.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The town decided that libraries should resemble train stations.", "This choice contradicts or overstates a detail in the passage."),
      choice("Old ticket windows are more useful than modern library desks.", "This choice contradicts or overstates a detail in the passage."),
      choice("The station could not be used until every original feature was removed.", "This choice contradicts or overstates a detail in the passage."),
      choice("The station's redesign created a library while preserving features of the building's history.", "The passage emphasizes both a new function and preservation of an old feature."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The passage emphasizes both a new function and preservation of an old feature.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-03",
    passage: "Students who received weekly reminders about assignment deadlines submitted more work on time. The reminders did not change the difficulty of the assignments; they simply made the deadlines more noticeable.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Students preferred weekly assignments to long-term projects.", "This choice contradicts or overstates a detail in the passage."),
      choice("Deadline reminders reduced the amount of work students had to do.", "This choice contradicts or overstates a detail in the passage."),
      choice("Making deadlines more noticeable helped students submit work on time.", "The improvement is attributed to deadline visibility, not easier work."),
      choice("The assignments became easier after reminders were introduced.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The improvement is attributed to deadline visibility, not easier work.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-04",
    passage: "Mara had planned to replace the scratched kitchen table. Yet when she noticed the faint pencil marks showing her children's heights over the years, she cleaned the table and moved it beside the window instead.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Pencil marks make the table impossible to clean.", "This choice contradicts or overstates a detail in the passage."),
      choice("Memories associated with the table lead Mara to keep it.", "The height marks change Mara's decision by reminding her of family history."),
      choice("Mara moves the table because the kitchen is too dark.", "This choice contradicts or overstates a detail in the passage."),
      choice("The children ask Mara to buy a new table.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The height marks change Mara's decision by reminding her of family history.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-05",
    passage: "A bakery lowered the price of bread near closing time. Waste declined because customers bought loaves that otherwise would have remained unsold, while the bakery still earned some revenue from them.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Late-day discounts helped the bakery reduce waste while earning revenue.", "The passage presents two benefits of discounting bread before closing."),
      choice("The bakery stopped selling bread during the morning.", "This choice contradicts or overstates a detail in the passage."),
      choice("Customers preferred stale bread to freshly baked bread.", "This choice contradicts or overstates a detail in the passage."),
      choice("Lower prices caused the bakery to produce more unsold loaves.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The passage presents two benefits of discounting bread before closing.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-06",
    passage: "A city posted meeting agendas online three days before each council meeting. Residents then had more time to read proposals and prepare comments before public discussion began.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Residents were no longer allowed to speak at council meetings.", "This choice contradicts or overstates a detail in the passage."),
      choice("The city shortened every council meeting to three days.", "This choice contradicts or overstates a detail in the passage."),
      choice("Online agendas replaced all public discussion of proposals.", "This choice contradicts or overstates a detail in the passage."),
      choice("Posting agendas earlier gave residents more time to prepare for council meetings.", "The key result is additional preparation time for residents."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The key result is additional preparation time for residents.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-07",
    passage: "A museum displayed a sculptor's unfinished clay model beside the completed bronze statue. Visitors could compare the rough early shapes with the precise details of the final work.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Visitors were asked to finish the clay model themselves.", "This choice contradicts or overstates a detail in the passage."),
      choice("The sculptor used bronze before making any clay studies.", "This choice contradicts or overstates a detail in the passage."),
      choice("Displaying the model with the statue helped visitors observe the sculptor's process.", "The comparison reveals how the work developed from early model to final object."),
      choice("The clay model was more valuable than the bronze statue.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The comparison reveals how the work developed from early model to final object.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-08",
    passage: "A lightweight coating kept solar panels cooler during midday tests. Because hotter panels generally produce electricity less efficiently, the coated panels generated slightly more power than uncoated ones.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Uncoated panels generated more power at midday.", "This choice contradicts or overstates a detail in the passage."),
      choice("A cooling coating modestly improved solar-panel output.", "The coating reduced heat, which was associated with slightly higher output."),
      choice("Solar panels work best when they become extremely hot.", "This choice contradicts or overstates a detail in the passage."),
      choice("The coating increased the weight of the solar panels.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The coating reduced heat, which was associated with slightly higher output.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-09",
    passage: "Researchers found that urban trees reduced afternoon temperatures most on streets with wide, continuous canopies. Scattered trees still provided shade directly beneath them, but they had little effect on the temperature of the street as a whole.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Continuous tree canopies cool entire streets more effectively than scattered trees do.", "The text contrasts local shade from scattered trees with street-wide cooling from continuous canopies."),
      choice("Scattered trees provide no shade at all.", "This choice contradicts or overstates a detail in the passage."),
      choice("Urban streets cannot be cooled by vegetation.", "This choice contradicts or overstates a detail in the passage."),
      choice("Wide streets always have lower temperatures than narrow streets.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The text contrasts local shade from scattered trees with street-wide cooling from continuous canopies.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-10",
    passage: "Letters from a nineteenth-century merchant describe delays caused by flooded roads. Account books from the same year show unusually low sales in distant towns but normal sales nearby. Together, the records suggest that transportation problems limited the merchant's wider trade.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The merchant stopped keeping account books after the flood.", "This choice contradicts or overstates a detail in the passage."),
      choice("Nearby towns purchased no goods from the merchant.", "This choice contradicts or overstates a detail in the passage."),
      choice("The letters prove that every road in the region was permanently closed.", "This choice contradicts or overstates a detail in the passage."),
      choice("Different historical records together indicate that flooded roads disrupted long-distance sales.", "The letters identify transport delays, and the accounts show the strongest sales decline in distant markets."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The letters identify transport delays, and the accounts show the strongest sales decline in distant markets.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-11",
    passage: "At first, the narrator calls the empty house silent. As she approaches, however, she notices shutters tapping, vines scraping brick, and rain ticking in a broken gutter. The description shifts from absence of sound to an uneasy collection of small noises.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("The narrator repairs the shutters and gutter during the storm.", "This choice contradicts or overstates a detail in the passage."),
      choice("The noises prove that many people are living inside the house.", "This choice contradicts or overstates a detail in the passage."),
      choice("The narrator's closer attention transforms the house's silence into a disturbing pattern of sounds.", "The passage's central movement is from apparent silence to unsettling detail."),
      choice("The house becomes quieter as the narrator approaches.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The passage's central movement is from apparent silence to unsettling detail.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-12",
    passage: "A survey found that commuters valued real-time bus information even when it did not shorten their trips. Riders reported that knowing when a bus would arrive made waiting feel less uncertain and helped them decide whether to walk.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Real-time information caused transit agencies to shorten every route.", "This choice contradicts or overstates a detail in the passage."),
      choice("Real-time bus information can improve riders' experience by reducing uncertainty, even without reducing travel time.", "The benefit described is predictability and decision-making, not necessarily faster trips."),
      choice("Commuters used bus information only when buses arrived early.", "This choice contradicts or overstates a detail in the passage."),
      choice("Walking was always faster than taking the bus.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The benefit described is predictability and decision-making, not necessarily faster trips.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-13",
    passage: "When a cooperative purchased a shared refrigerated truck, small farms gained access to markets farther away. The truck did not increase how much the farms produced, but it reduced spoilage during transport and expanded where their products could be sold.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Shared refrigeration expanded small farms' market access by reducing transport losses.", "The passage distinguishes unchanged production from improved distribution and reduced spoilage."),
      choice("The truck caused farms to grow more crops immediately.", "This choice contradicts or overstates a detail in the passage."),
      choice("Distant markets refused to buy refrigerated products.", "This choice contradicts or overstates a detail in the passage."),
      choice("The cooperative replaced farming with a transportation business.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The passage distinguishes unchanged production from improved distribution and reduced spoilage.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-14",
    passage: "After a county translated emergency alerts into four additional languages, more residents reported receiving useful information during storms. Officials noted, however, that some rural households still lacked reliable phone service, so translation alone did not solve every access problem.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Translation made phone service reliable in rural areas.", "This choice contradicts or overstates a detail in the passage."),
      choice("The county stopped issuing alerts in its original language.", "This choice contradicts or overstates a detail in the passage."),
      choice("Storm information became less useful after translation.", "This choice contradicts or overstates a detail in the passage."),
      choice("Multilingual alerts improved access, but communication gaps remained where phone service was unreliable.", "The text balances a successful language-access measure with a remaining infrastructure limitation."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The text balances a successful language-access measure with a remaining infrastructure limitation.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-15",
    passage: "A curator rearranged a photography exhibit by theme rather than by date. Images taken decades apart now appeared beside one another, encouraging visitors to compare how different photographers treated similar subjects.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Visitors were required to arrange the photographs themselves.", "This choice contradicts or overstates a detail in the passage."),
      choice("Chronological order always prevents viewers from noticing subjects.", "This choice contradicts or overstates a detail in the passage."),
      choice("Organizing photographs thematically encouraged comparisons across time.", "The new organization places related subjects together despite different dates."),
      choice("The exhibit contained photographs from only one decade.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The new organization places related subjects together despite different dates.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-central-16",
    passage: "A machine-learning model identified plant diseases accurately in laboratory images but performed less well on photographs taken in fields. Shadows, damaged leaves, and varied camera angles introduced conditions that were rare in the training data.",
    prompt: "Which choice best states the main idea of the text?",
    choices: [
      choice("Camera angles had no effect on the model's performance.", "This choice contradicts or overstates a detail in the passage."),
      choice("The model's laboratory success did not fully transfer to field conditions that differed from its training data.", "The passage explains a gap between controlled-image performance and real-world performance."),
      choice("The model was trained only on photographs of healthy plants.", "This choice contradicts or overstates a detail in the passage."),
      choice("Field photographs contained no visible plant leaves.", "This choice contradicts or overstates a detail in the passage."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Central Ideas and Details",
    domain: "Information and Ideas",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Identify the passage's primary claim or development.",
      "The passage explains a gap between controlled-image performance and real-world performance.",
      "Reject choices that focus on a minor detail or make an unsupported absolute claim.",
    ],
  }),
];
