import { choice, createExpansionQuestion } from "./factory";

export const crossTextExpansionQuestions = [
  createExpansionQuestion({
    id: "rexp1-cross-01",
    passage: "Text 1: A study found that planting wildflowers beside farms increased the number of native bees observed nearby.\n\nText 2: Another study found that wildflower strips helped bees only when pesticides were applied infrequently.",
    prompt: "Based on the texts, how would the author of Text 2 most likely respond to the finding in Text 1?",
    choices: [
      choice("The first study must have counted birds rather than bees.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("The increase in bees may depend on farming practices in addition to the presence of wildflowers.", "Text 2 adds a condition—low pesticide use—to the benefit reported in Text 1."),
      choice("Wildflowers can never affect bee populations.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Pesticide use is unrelated to bee habitat.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Text 2 adds a condition—low pesticide use—to the benefit reported in Text 1.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-02",
    passage: "Text 1: A historian argues that a canal transformed the town by lowering transportation costs.\n\nText 2: A local diary emphasizes that the canal also brought seasonal workers and new languages to the town.",
    prompt: "What is one difference between the texts?",
    choices: [
      choice("Text 1 emphasizes economic change, whereas Text 2 emphasizes social change.", "The first text highlights costs; the second highlights population and language."),
      choice("Text 1 discusses the town after the canal closed, whereas Text 2 discusses it before construction.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Text 1 praises diaries, whereas Text 2 rejects all personal records.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Text 1 focuses on language, whereas Text 2 focuses only on shipping prices.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired History Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "The first text highlights costs; the second highlights population and language.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-03",
    passage: "Text 1: A critic praises a play's spare stage design because it keeps attention on the actors.\n\nText 2: Another critic argues that the same design makes the setting feel unfinished.",
    prompt: "How do the critics differ?",
    choices: [
      choice("They disagree about whether the play has actors.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("They discuss entirely different plays.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("They agree that elaborate scenery is the play's greatest strength.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("They interpret the effect of the minimal design differently.", "Both discuss the same feature but evaluate its effect differently."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Humanities Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Both discuss the same feature but evaluate its effect differently.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-04",
    passage: "Text 1: Lowering train fares increased ridership among weekend travelers.\n\nText 2: Fare reductions had little effect on commuters whose employers already paid their travel costs.",
    prompt: "Which statement is supported by both texts?",
    choices: [
      choice("Employers never pay commuting costs.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Weekend travelers and commuters respond identically to prices.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("The effect of a fare reduction can vary across groups of travelers.", "One group responds strongly, while another has little reason to respond."),
      choice("Lower fares always reduce train ridership.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Economics Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "One group responds strongly, while another has little reason to respond.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-05",
    passage: "Text 1: Survey respondents who work from home report greater schedule flexibility.\n\nText 2: Interviews show that some remote workers struggle to stop working at the end of the day.",
    prompt: "How does Text 2 relate to Text 1?",
    choices: [
      choice("It provides the same survey result without qualification.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It identifies a potential drawback that can accompany the flexibility described in Text 1.", "Text 2 complicates the benefit by describing blurred work boundaries."),
      choice("It proves that remote workers have no flexibility.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It changes the topic from work to transportation.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Social Science Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Text 2 complicates the benefit by describing blurred work boundaries.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-06",
    passage: "Text 1: A model predicts that earlier snowmelt will lengthen the growing season.\n\nText 2: Field observations show that plants sometimes emerge earlier but are then damaged by late frost.",
    prompt: "Taken together, what do the texts suggest?",
    choices: [
      choice("A longer potential growing season does not necessarily produce greater plant growth.", "Text 2 supplies a mechanism that can offset the benefit predicted in Text 1."),
      choice("Earlier snowmelt prevents every frost event.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Models cannot be used to study seasonal change.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("Plants always emerge later when snow melts early.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Science Texts",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Text 2 supplies a mechanism that can offset the benefit predicted in Text 1.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-07",
    passage: "Text 1: An official census records a sharp decline in a city's population after an earthquake.\n\nText 2: Tax records from the same year list many residents at temporary addresses outside the city, but later records show that some returned.",
    prompt: "How would Text 2 most likely affect an interpretation of Text 1?",
    choices: [
      choice("It proves that the earthquake increased the city's permanent population.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It shows that tax records and censuses count exactly the same thing.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It establishes that no residents ever left the city.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It suggests that the census decline may reflect temporary displacement as well as permanent departure.", "Temporary addresses and later returns complicate a simple permanent-loss interpretation."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired History Texts",
    module: 2,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Temporary addresses and later returns complicate a simple permanent-loss interpretation.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-cross-08",
    passage: "Text 1: A scholar argues that repeated images of doors in a novel symbolize opportunities available to the protagonist.\n\nText 2: Another scholar notes that several doors in the novel are locked or lead back to rooms the protagonist has already left.",
    prompt: "How does Text 2 challenge the interpretation in Text 1?",
    choices: [
      choice("It claims that symbols can have only one meaning.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It confirms that every door opens onto a new opportunity.", "This choice conflicts with or is not supported by the relationship between the two texts."),
      choice("It suggests that the door imagery may represent limitation or repetition, not only opportunity.", "Locked and circular paths provide textual evidence for meanings other than opportunity."),
      choice("It shows that the novel contains no doors.", "This choice conflicts with or is not supported by the relationship between the two texts."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Cross-Text Connections",
    domain: "Craft and Structure",
    passageType: "Paired Humanities Texts",
    module: 2,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "paired-text"],
    walkthrough: [
      "State the central claim or emphasis of each text.",
      "Locked and circular paths provide textual evidence for meanings other than opportunity.",
      "Choose the option that accurately describes agreement, qualification, or disagreement without exaggeration.",
    ],
  }),
];
