import { choice, createExpansionQuestion } from "./factory";

export const quantitativeEvidenceExpansionQuestions = [
  createExpansionQuestion({
    id: "rexp1-quant-01",
    passage: "Researchers measured the average height of bean plants after four weeks.\n\nNo fertilizer: 12 cm\nFertilizer A: 18 cm\nFertilizer B: 15 cm",
    prompt: "Which choice best uses the data to support the claim that Fertilizer A produced the greatest growth?",
    choices: [
      choice("Plants receiving Fertilizer A averaged 18 cm, compared with 15 cm for Fertilizer B and 12 cm with no fertilizer.", "The correct choice compares A's 18 cm average with both lower averages."),
      choice("Fertilizer B plants averaged 15 cm, which was shorter than plants with no fertilizer.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("All three groups averaged exactly 18 cm.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Plants with no fertilizer were 6 cm taller than plants receiving Fertilizer A.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "The correct choice compares A's 18 cm average with both lower averages.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-02",
    passage: "A library recorded average daily visits before and after extending weekend hours.\n\nBefore: 240 visits\nAfter: 310 visits",
    prompt: "Which choice best uses the data to support the claim that visits increased after the schedule change?",
    choices: [
      choice("Average daily visits fell by 70.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("The library had 240 more visits after the change.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Visits remained exactly the same.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Average daily visits rose from 240 to 310.", "The data show a direct increase of 70 visits."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Social Science Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "The data show a direct increase of 70 visits.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-03",
    passage: "A shop tracked reusable-cup use after introducing a discount.\n\nWeek 1: 80 uses\nWeek 2: 105 uses\nWeek 3: 130 uses",
    prompt: "Which choice best describes the trend in the data?",
    choices: [
      choice("Week 1 and Week 3 had the same use.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Use increased and then returned to 80.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Reusable-cup use increased each week.", "The values rise from 80 to 105 to 130."),
      choice("Reusable-cup use decreased by 25 each week.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Economics Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "The values rise from 80 to 105 to 130.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-04",
    passage: "A museum counted digitized letters from three decades.\n\n1840s: 120\n1850s: 175\n1860s: 160",
    prompt: "Which statement is best supported by the data?",
    choices: [
      choice("All three decades had equal totals.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("The museum digitized the most letters from the 1850s.", "175 is greater than both 120 and 160."),
      choice("The museum digitized fewer letters from the 1850s than the 1840s.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("The 1860s total was 15 greater than the 1850s total.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Historical Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "175 is greater than both 120 and 160.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-05",
    passage: "Seed germination after ten days:\n\nConstant light: 62%\n12 hours light: 81%\nNo light: 39%",
    prompt: "Which choice best supports the conclusion that the 12-hour light condition was most effective?",
    choices: [
      choice("Its germination rate was 19 percentage points above constant light and 42 points above no light.", "The comparison quantifies how the 81% rate exceeded both alternatives."),
      choice("Its rate was lower than both other conditions.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Constant light exceeded the 12-hour condition by 19 points.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("No light produced a germination rate of 81%.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Experimental Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "The comparison quantifies how the 81% rate exceeded both alternatives.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-06",
    passage: "Average battery capacity remaining after 200 cycles:\n\nDesign X: 84%\nDesign Y: 71%\nDesign Z: 83%",
    prompt: "Which choice most accurately characterizes the results?",
    choices: [
      choice("Design Y retained the most capacity.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Design X and Design Y differed by only 1 percentage point.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Design Z retained no capacity after 200 cycles.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Design X retained slightly more capacity than Design Z and substantially more than Design Y.", "X exceeds Z by 1 point and Y by 13 points."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Science Data",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "X exceeds Z by 1 point and Y by 13 points.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-07",
    passage: "Percentage change in sales after a delivery-fee reduction:\n\nUrban stores: +14%\nSuburban stores: +6%\nRural stores: +1%\n\nBefore the change, urban stores also had the shortest average delivery distance.",
    prompt: "Which choice best explains why the data do not by themselves prove that the fee reduction caused the larger urban increase?",
    choices: [
      choice("The sales changes are expressed as percentages.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Suburban sales increased by less than urban sales.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Urban stores differed in delivery distance as well as in sales growth, so delivery distance could be a contributing factor.", "A preexisting difference correlated with store type prevents clean causal attribution."),
      choice("Rural stores had a positive sales change.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Economics Data",
    module: 2,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "A preexisting difference correlated with store type prevents clean causal attribution.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-quant-08",
    passage: "Mean reaction time after four weeks:\n\nControl group: 510 ms\nTraining group: 465 ms\n\nThe training group was, on average, five years younger than the control group.",
    prompt: "Which choice best evaluates the evidence for the claim that training improved reaction time?",
    choices: [
      choice("The data prove that training has no effect.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("The training group responded faster, but the age difference makes it difficult to attribute the entire difference to training.", "The outcome favors training, but group age is a confounding variable."),
      choice("The control group responded faster because 510 is less than 465.", "This choice misreads the values or makes a causal claim the data do not justify."),
      choice("Age cannot be related to reaction time under any circumstances.", "This choice misreads the values or makes a causal claim the data do not justify."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Quantitative Evidence",
    domain: "Information and Ideas",
    passageType: "Experimental Data",
    module: 2,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "data"],
    walkthrough: [
      "Identify the exact comparison or trend required by the prompt.",
      "The outcome favors training, but group age is a confounding variable.",
      "Check units and distinguish a supported description from an unsupported causal conclusion.",
    ],
  }),
];
