import { choice, createExpansionQuestion } from "./factory";

export const textStructureExpansionQuestions = [
  createExpansionQuestion({
    id: "rexp1-structure-01",
    passage: "The paragraph begins with a crowded market described through noise and motion. It then narrows to one vendor silently folding a letter behind his stall.",
    prompt: "Which choice best describes the function of the second sentence in the text?",
    choices: [
      choice("It proves that the vendor wrote the letter.", "This choice does not match the role or organization described in the text."),
      choice("It summarizes every event that occurred in the market.", "This choice does not match the role or organization described in the text."),
      choice("It shifts attention from the busy setting to a private action.", "The second sentence narrows the focus from the public scene to one individual's quiet behavior."),
      choice("It explains why the market has closed.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The second sentence narrows the focus from the public scene to one individual's quiet behavior.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-02",
    passage: "Scientists first describe how ordinary glass blocks some ultraviolet light. They then introduce a new coating that blocks a wider range of ultraviolet wavelengths.",
    prompt: "Which choice best describes the overall structure of the text?",
    choices: [
      choice("It describes a coating and then denies that the coating exists.", "This choice does not match the role or organization described in the text."),
      choice("It presents a familiar limitation and then introduces an improvement.", "The text moves from the performance of ordinary glass to a coating that improves that performance."),
      choice("It lists two unrelated discoveries in reverse chronological order.", "This choice does not match the role or organization described in the text."),
      choice("It argues that ultraviolet light cannot be measured.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The text moves from the performance of ordinary glass to a coating that improves that performance.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-03",
    passage: "The author recounts the opening of a bridge in 1912 and then notes that the bridge became a symbol on local postcards for decades.",
    prompt: "What is the main purpose of the text?",
    choices: [
      choice("To explain both an event and the bridge's later cultural importance.", "The text connects the bridge's opening with its later role as a local symbol."),
      choice("To provide instructions for constructing a bridge.", "This choice does not match the role or organization described in the text."),
      choice("To argue that postcards caused the bridge to open.", "This choice does not match the role or organization described in the text."),
      choice("To compare two bridges built in different countries.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The text connects the bridge's opening with its later role as a local symbol.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-04",
    passage: "The text gives a common explanation for why people avoid public parks at night: poor lighting. It then adds that limited evening bus service can also reduce park use.",
    prompt: "Which choice best describes the structure of the text?",
    choices: [
      choice("It rejects every explanation for low park use.", "This choice does not match the role or organization described in the text."),
      choice("It describes a bus route before discussing public parks.", "This choice does not match the role or organization described in the text."),
      choice("It compares daytime lighting in two unrelated cities.", "This choice does not match the role or organization described in the text."),
      choice("It presents one explanation and then adds another contributing factor.", "The second idea supplements rather than replaces the first explanation."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The second idea supplements rather than replaces the first explanation.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-05",
    passage: "The author defines a subscription model and then provides an example of a tool company charging customers a monthly fee for equipment access.",
    prompt: "What is the function of the example?",
    choices: [
      choice("It shows that the company gives away equipment permanently.", "This choice does not match the role or organization described in the text."),
      choice("It introduces a historical argument about tool manufacturing.", "This choice does not match the role or organization described in the text."),
      choice("It illustrates the business model that the author has just defined.", "The company example makes the abstract definition concrete."),
      choice("It disproves the definition of a subscription model.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The company example makes the abstract definition concrete.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-06",
    passage: "The passage describes a proposed recycling rule, lists comments from residents, and ends by noting that the council delayed its vote.",
    prompt: "Which choice best describes the organization of the passage?",
    choices: [
      choice("It explains how to manufacture recyclable materials.", "This choice does not match the role or organization described in the text."),
      choice("It presents a proposal, public responses, and the resulting official action.", "The sequence follows proposal, reaction, and consequence."),
      choice("It begins with the council's final vote and then hides the proposal.", "This choice does not match the role or organization described in the text."),
      choice("It compares recycling rates in four countries.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The sequence follows proposal, reaction, and consequence.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-07",
    passage: "A review first praises a novel's vivid setting. The reviewer then criticizes its predictable ending.",
    prompt: "What is the main purpose of the second sentence?",
    choices: [
      choice("To qualify the reviewer's positive assessment with a criticism.", "The second sentence adds a limitation to an initially positive evaluation."),
      choice("To repeat the praise in different words.", "This choice does not match the role or organization described in the text."),
      choice("To reveal that the reviewer did not read the novel.", "This choice does not match the role or organization described in the text."),
      choice("To explain where the novel was printed.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The second sentence adds a limitation to an initially positive evaluation.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-08",
    passage: "The text states that bees can learn the location of a food source. It then describes an experiment in which bees repeatedly returned to a marked platform.",
    prompt: "What is the function of the experiment in the text?",
    choices: [
      choice("It changes the topic from bees to platform design.", "This choice does not match the role or organization described in the text."),
      choice("It proves that all insects learn in the same way.", "This choice does not match the role or organization described in the text."),
      choice("It explains why the food source was removed.", "This choice does not match the role or organization described in the text."),
      choice("It provides evidence for the preceding statement.", "The experiment directly supports the claim about learned location."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The experiment directly supports the claim about learned location.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-09",
    passage: "The passage opens with Elena confidently predicting that the old clock will work. After several failed attempts to repair it, the final sentence repeats her prediction as a question.",
    prompt: "Which choice best describes the effect of repeating the prediction as a question?",
    choices: [
      choice("It introduces a new character who owns the clock.", "This choice does not match the role or organization described in the text."),
      choice("It explains the clock's manufacturing process.", "This choice does not match the role or organization described in the text."),
      choice("It turns Elena's earlier confidence into uncertainty.", "The altered grammatical form changes the repeated statement from certainty to doubt."),
      choice("It confirms that the clock has already been repaired.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The altered grammatical form changes the repeated statement from certainty to doubt.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-10",
    passage: "The author describes a correlation between coastal fog and plant growth, then warns that both may be influenced by elevation. A final sentence proposes comparing sites at the same elevation.",
    prompt: "Which choice best describes the function of the final sentence?",
    choices: [
      choice("It changes the subject from plants to marine animals.", "This choice does not match the role or organization described in the text."),
      choice("It proposes a way to test whether fog itself is associated with growth.", "The proposed controlled comparison responds directly to the confounding variable."),
      choice("It restates the correlation without addressing the limitation.", "This choice does not match the role or organization described in the text."),
      choice("It proves that elevation has no effect on plants.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The proposed controlled comparison responds directly to the confounding variable.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-11",
    passage: "The text first presents an official report claiming that a factory opened in May. It then cites a worker's diary describing production in April, and concludes that trial operations may have begun before the formal opening.",
    prompt: "Which choice best describes the structure of the text?",
    choices: [
      choice("It contrasts two sources and offers an explanation that reconciles them.", "The conclusion interprets the apparent conflict as reflecting two meanings of opening."),
      choice("It rejects both sources as entirely useless.", "This choice does not match the role or organization described in the text."),
      choice("It lists factory products without discussing dates.", "This choice does not match the role or organization described in the text."),
      choice("It argues that diaries are always more accurate than official records.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "History",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The conclusion interprets the apparent conflict as reflecting two meanings of opening.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-12",
    passage: "A researcher notes that neighborhood gardens are associated with stronger social ties. Rather than treating the association as proof of causation, she asks whether already-connected neighborhoods are more likely to create gardens.",
    prompt: "What is the main purpose of the researcher's question?",
    choices: [
      choice("To show that gardens cannot grow in cities.", "This choice does not match the role or organization described in the text."),
      choice("To define the term neighborhood.", "This choice does not match the role or organization described in the text."),
      choice("To claim that social ties are impossible to measure.", "This choice does not match the role or organization described in the text."),
      choice("To identify an alternative explanation for the observed association.", "The question raises reverse causation as a competing explanation."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The question raises reverse causation as a competing explanation.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-13",
    passage: "The passage explains that a tax credit increased purchases of efficient appliances. It then observes that most recipients had planned to replace an appliance anyway, before asking whether the credit changed timing more than total demand.",
    prompt: "Which choice best describes the purpose of the final question?",
    choices: [
      choice("To explain how appliances generate electricity.", "This choice does not match the role or organization described in the text."),
      choice("To show that all recipients bought two appliances.", "This choice does not match the role or organization described in the text."),
      choice("To refine what effect the tax credit may actually have had.", "The question distinguishes accelerating purchases from creating additional purchases."),
      choice("To argue that no one received the tax credit.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The question distinguishes accelerating purchases from creating additional purchases.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-14",
    passage: "The author begins by describing the benefits of publishing public records online. The next paragraph focuses on residents who lack broadband access and discusses library terminals as one response.",
    prompt: "Which choice best describes the relationship between the paragraphs?",
    choices: [
      choice("The second paragraph argues that records should never be public.", "This choice does not match the role or organization described in the text."),
      choice("The second paragraph identifies a limitation of the policy and a possible remedy.", "The shift considers unequal access and then proposes a way to reduce it."),
      choice("The second paragraph repeats the first without adding information.", "This choice does not match the role or organization described in the text."),
      choice("The paragraphs describe two unrelated court cases.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The shift considers unequal access and then proposes a way to reduce it.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-15",
    passage: "An art historian first interprets a portrait's dark background as a sign of mourning. She then notes that similar backgrounds were common in the painter's workshop, regardless of subject.",
    prompt: "What is the function of the second sentence?",
    choices: [
      choice("It introduces evidence that complicates the historian's initial interpretation.", "The workshop convention weakens the claim that darkness uniquely signals mourning."),
      choice("It proves that the portrait has no background.", "This choice does not match the role or organization described in the text."),
      choice("It provides the exact price of the painting.", "This choice does not match the role or organization described in the text."),
      choice("It changes the topic to sculpture.", "This choice does not match the role or organization described in the text."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The workshop convention weakens the claim that darkness uniquely signals mourning.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp1-structure-16",
    passage: "The passage describes a material that is flexible at room temperature but becomes rigid when cooled. The final sentence suggests using it in a device that must be inserted in a flexible state and then stabilized.",
    prompt: "What is the function of the final sentence?",
    choices: [
      choice("It denies that temperature affects the material.", "This choice does not match the role or organization described in the text."),
      choice("It explains how the material was discovered historically.", "This choice does not match the role or organization described in the text."),
      choice("It compares the material with a food product.", "This choice does not match the role or organization described in the text."),
      choice("It identifies a practical application based on the material's changing properties.", "The proposed device uses both flexibility and later rigidity."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Text Structure and Purpose",
    domain: "Craft and Structure",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 75,
    tags: ["coverage-gap", "module-1"],
    walkthrough: [
      "Determine how the relevant sentence or paragraph relates to the rest of the text.",
      "The proposed device uses both flexibility and later rigidity.",
      "Eliminate choices that merely repeat a detail without describing its function.",
    ],
  }),
];
