"use client";
import Link from "next/link";
import { buildAnalytics } from "@/lib/analytics/analyticsEngine";
import { useAdaptiveExamStore } from "@/store/adaptiveExamStore";

const pct=(n:number)=>`${Math.round(n*100)}%`;
function TrendChart({data}:{data:Array<{total:number;rw:number;math:number}>}){if(data.length<2)return <div className="analyticsEmptyMini">Complete another test to unlock a trend line.</div>;const w=720,h=210,p=28,min=400,max=1600;const pts=(key:"total"|"rw"|"math",scale=1,offset=0)=>data.map((d,i)=>`${p+i*(w-2*p)/(data.length-1)},${h-p-(((d[key]*scale+offset)-min)/(max-min))*(h-2*p)}`).join(" ");return <svg className="analyticsChart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="SAT score trend"><line x1={p} y1={h-p} x2={w-p} y2={h-p}/><polyline className="trendTotal" points={pts("total")}/><polyline className="trendRw" points={pts("rw",2)}/><polyline className="trendMath" points={pts("math",2)}/></svg>}
export default function AnalyticsPage(){const attempts=useAdaptiveExamStore(s=>s.attempts);if(!attempts.length)return <main className="pageShell"><section className="pageHero"><div className="container"><p className="eyebrow">Learning analytics</p><h1>Your diagnostic dashboard starts after one test.</h1><p>Complete an adaptive simulation to identify strengths, weak skills, and the best next practice.</p><Link className="button buttonPrimary" href="/adaptive/exam">Take an adaptive test</Link></div></section></main>;const r=buildAnalytics(attempts);return <main className="pageShell"><section className="pageHero adaptiveHero"><div className="container"><p className="eyebrow">Learning analytics</p><h1>Turn test results into a study plan.</h1><p>{attempts.length} completed test{attempts.length===1?"":"s"} · {r.totalQuestions} analyzed questions</p></div></section><div className="container pageContent analyticsDashboard">
<section className="analyticsPanel"><div className="sectionHeader"><p className="sectionKicker">Score trend</p><h2>Performance over time</h2></div><TrendChart data={r.scoreTrend}/><div className="chartLegend"><span>Total</span><span>Reading & Writing ×2</span><span>Math ×2</span></div></section>
<section><div className="sectionHeader"><p className="sectionKicker">Recommended next practice</p><h2>Highest-value priorities</h2></div><div className="analyticsRecommendationGrid">{r.recommendations.length?r.recommendations.map((x,i)=><article key={x.label}><span className="statusPill">Priority {i+1} · {x.section}</span><h3>{x.label}</h3><p>{x.reason}</p><Link href={x.href}>Review targeted mistakes →</Link></article>):<article><h3>Strong balanced performance</h3><p>Complete another test to improve confidence and reveal smaller gaps.</p></article>}</div></section>
<section><div className="sectionHeader"><p className="sectionKicker">Official domains</p><h2>Mastery by reporting area</h2></div><div className="analyticsMasteryGrid">{r.domains.map(x=><article key={`${x.section}-${x.label}`}><div><span>{x.section}</span><strong>{pct(x.accuracy)}</strong></div><h3>{x.label}</h3><div className="masteryTrack"><i style={{width:pct(x.accuracy)}}/></div><p>{x.correct}/{x.total} correct · <b>{x.level}</b>{Math.abs(x.trend)>=.05?` · ${x.trend>0?"↑":"↓"} ${Math.round(Math.abs(x.trend)*100)} recent pts`:""}</p></article>)}</div></section>
<section className="analyticsTwoCol"><div><div className="sectionHeader"><p className="sectionKicker">Skill breakdown</p><h2>Lowest sampled skills</h2></div><div className="analyticsList">{r.skills.slice(0,8).map(x=><Link href={`/review?skill=${encodeURIComponent(x.label)}`} key={`${x.section}-${x.label}`}><span><b>{x.label}</b><small>{x.section} · {x.total} questions</small></span><strong>{pct(x.accuracy)}</strong></Link>)}</div></div><div><div className="sectionHeader"><p className="sectionKicker">Mistake profile</p><h2>What caused lost points</h2></div><div className="analyticsStatGrid"><article><strong>{r.mistakes.wrong}</strong><span>Incorrect</span></article><article><strong>{r.mistakes.unanswered}</strong><span>Unanswered</span></article><article><strong>{r.mistakes.flagged}</strong><span>Flagged</span></article><article><strong>{r.mistakes.studentResponseWrong}</strong><span>Grid-in errors</span></article></div><Link className="button buttonGhost" href="/review">Open mistake review</Link></div></section>
<section><div className="sectionHeader"><p className="sectionKicker">Difficulty profile</p><h2>Foundation versus stretch questions</h2></div><div className="analyticsMasteryGrid compact">{r.difficulties.map(x=><article key={`${x.section}-${x.label}`}><div><span>{x.section}</span><strong>{pct(x.accuracy)}</strong></div><h3>{x.label}</h3><p>{x.correct}/{x.total} correct</p></article>)}</div></section>
<section className="analyticsPanel"><div className="sectionHeader"><p className="sectionKicker">Timing</p><h2>Pacing diagnostics</h2></div>{r.timing.available?<><div className="analyticsStatGrid"><article><strong>{Math.round(r.timing.averageSeconds)}s</strong><span>Average</span></article><article><strong>{Math.round(r.timing.correctAverageSeconds)}s</strong><span>Correct answers</span></article><article><strong>{Math.round(r.timing.incorrectAverageSeconds)}s</strong><span>Incorrect answers</span></article></div><p>Slowest sampled skill: <b>{r.timing.slowest[0]?.label}</b> at {Math.round(r.timing.slowest[0]?.seconds??0)} seconds.</p></>:<p>Per-question timing begins with tests taken in Sprint 40. Complete a new test to unlock pacing analysis.</p>}</section>
</div></main>}
