import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const punctuationExpansion5Questions = [
  createExpansionQuestion({
    id: "rexp5-punctuation-01",
    passage: "The study measured three variables _____ temperature, humidity, and pressure.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "A colon introduces a list that follows a complete clause."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces a list that follows a complete clause.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-02",
    passage: "The diary _____ written in 1912 _____ describes daily life in the port.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" written in 1912", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; written in 1912;", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" written in 1912,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(", written in 1912,", "The nonessential phrase is correctly enclosed by commas."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The nonessential phrase is correctly enclosed by commas.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-03",
    passage: "The artist used wood, glass _____ and steel.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "A comma separates the final item in a series."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma separates the final item in a series.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-04",
    passage: "The company's goal was clear _____ reduce shipping delays.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "A colon introduces an explanation of the preceding complete clause."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces an explanation of the preceding complete clause.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-05",
    passage: "The samples collected from the northern site _____ unlike those from the southern site _____ contained little salt.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", unlike those from the southern site,", "The contrasting phrase is nonessential and should be enclosed by commas."),
      choice(" unlike those from the southern site", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; unlike those from the southern site;", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" unlike those from the southern site,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The contrasting phrase is nonessential and should be enclosed by commas.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-06",
    passage: "The agency published the report on Monday _____ however, several appendices were missing.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "A semicolon is required before a conjunctive adverb joining independent clauses."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon is required before a conjunctive adverb joining independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-07",
    passage: "The narrator's description is vivid _____ unsettling, and unexpectedly humorous.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "A comma separates coordinate adjectives in a series."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma separates coordinate adjectives in a series.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-08",
    passage: "The bridge, completed in 1898 _____ remains in use today.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "The closing comma completes the pair around the nonessential phrase."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The closing comma completes the pair around the nonessential phrase.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-09",
    passage: "Researchers tested two conditions _____ high humidity and low humidity.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "A colon introduces the two conditions after a complete clause."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces the two conditions after a complete clause.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-10",
    passage: "The exhibition included paintings by Li _____ sculptures by Gomez, and photographs by Reed.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "A comma separates items in a straightforward series."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma separates items in a straightforward series.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-11",
    passage: "The device's main advantage _____ its ability to function at low temperatures _____ makes it useful in polar research.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(": its ability to function at low temperatures,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" its ability to function at low temperatures", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("\u2014 its ability to function at low temperatures \u2014", "A pair of dashes correctly sets off the emphatic nonessential appositive."),
      choice(", its ability to function at low temperatures;", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A pair of dashes correctly sets off the emphatic nonessential appositive.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-12",
    passage: "The archive contains one especially valuable item _____ a complete set of the town's earliest maps.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("\u2014 and", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "A colon introduces a specific example after a complete clause."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces a specific example after a complete clause.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-13",
    passage: "The policy had two intended effects _____ to reduce delays and to improve transparency.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "A colon introduces the two effects."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces the two effects.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-14",
    passage: "The participants _____ all of whom had completed the preliminary survey _____ returned for a second session.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" all of whom had completed the preliminary survey", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; all of whom had completed the preliminary survey;", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" all of whom had completed the preliminary survey,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(", all of whom had completed the preliminary survey,", "The nonrestrictive clause must be enclosed by commas."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The nonrestrictive clause must be enclosed by commas.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-15",
    passage: "The novel's final image _____ a door left slightly open _____ echoes an image from the first chapter.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" a door left slightly open,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" : a door left slightly open:", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("\u2014 a door left slightly open \u2014", "A matched pair of dashes cleanly sets off the explanatory appositive."),
      choice(", a door left slightly open;", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A matched pair of dashes cleanly sets off the explanatory appositive.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-punctuation-16",
    passage: "The researchers reached one conclusion _____ the observed association did not establish causation.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "A colon introduces the content of the conclusion."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; although", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A colon introduces the content of the conclusion.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
];