import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const sentenceBoundariesExpansion5Questions = [
  createExpansionQuestion({
    id: "rexp5-boundaries-01",
    passage: "The telescope collected light from the distant galaxy _____ the data were then processed by a computer.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "A semicolon correctly joins two closely related independent clauses."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon correctly joins two closely related independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-02",
    passage: "The archive closed early _____ a power outage affected the building.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("because", "The subordinating conjunction \u201cbecause\u201d links the cause to the main clause without creating a fragment."),
      choice("; because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(", because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(".", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The subordinating conjunction \u201cbecause\u201d links the cause to the main clause without creating a fragment.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-03",
    passage: "The sculpture appears fragile _____ however, it is made of steel.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "A semicolon is needed before the conjunctive adverb joining two independent clauses."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon is needed before the conjunctive adverb joining two independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-04",
    passage: "The survey included residents from four neighborhoods _____ all participants were over eighteen.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("and", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(", and", "A comma plus coordinating conjunction correctly joins two independent clauses."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma plus coordinating conjunction correctly joins two independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-05",
    passage: "The coating reduced heat absorption _____ this effect was strongest at midday.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" which", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "Both sides are independent clauses, so a semicolon is appropriate."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "Both sides are independent clauses, so a semicolon is appropriate.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-06",
    passage: "The city expanded online services _____ residents without reliable internet still faced barriers.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", but", "A comma and coordinating conjunction correctly join contrasting independent clauses."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; but", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" despite", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma and coordinating conjunction correctly join contrasting independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-07",
    passage: "Mara opened the letter _____ although she already knew what it contained.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "A comma separates the independent clause from the following dependent clause."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma separates the independent clause from the following dependent clause.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-08",
    passage: "Demand increased after prices fell _____ the company hired additional workers.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(": as a result", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" as a result", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; as a result,", "A semicolon precedes the conjunctive adverb that links two independent clauses."),
      choice(", as a result,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon precedes the conjunctive adverb that links two independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-09",
    passage: "The bridge survived the flood _____ its wooden approaches were destroyed.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" although", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(", but", "A comma plus \u201cbut\u201d properly joins two contrasting independent clauses."),
      choice("; but", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A comma plus \u201cbut\u201d properly joins two contrasting independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-10",
    passage: "The sample was stored at low temperature _____ preventing chemical changes during transport.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "The participial phrase modifies the preceding clause and is set off with a comma."),
      choice(";", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The participial phrase modifies the preceding clause and is set off with a comma.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-11",
    passage: "The critic praises the novel's structure _____ she argues, nevertheless, that its conclusion is too predictable.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" and", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "The semicolon joins two independent clauses; the parenthetical adverb is punctuated internally."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The semicolon joins two independent clauses; the parenthetical adverb is punctuated internally.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-12",
    passage: "The model performed well in the laboratory _____ in field conditions, however, its accuracy declined.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" because", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "A semicolon correctly separates two independent clauses linked by a contrast."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon correctly separates two independent clauses linked by a contrast.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-13",
    passage: "The policy increased the number of published records _____ whether those records were usable remained uncertain.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "Two complete clauses require a semicolon or period, not a comma alone."),
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" although", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "Two complete clauses require a semicolon or period, not a comma alone.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-14",
    passage: "Participants reported greater flexibility _____ because they selected their own schedules, the study could not rule out self-selection.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("; however,", "A semicolon and conjunctive adverb correctly join the independent clauses."),
      choice(", however,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" however", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(": however", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "A semicolon and conjunctive adverb correctly join the independent clauses.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-15",
    passage: "The census recorded a population decline _____ school records from the following year, by contrast, showed many families returning.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(" although", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(":", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(";", "The contrast is between two independent clauses, so a semicolon is correct."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The contrast is between two independent clauses, so a semicolon is correct.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-boundaries-16",
    passage: "The treatment group improved more than the control group _____ the groups differed at baseline, a limitation the authors acknowledged.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" however", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice(": however,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("; however,", "The semicolon and conjunctive adverb properly connect complete clauses while signaling contrast."),
      choice(", however,", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The semicolon and conjunctive adverb properly connect complete clauses while signaling contrast.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
];