import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const verbAgreementExpansion5Questions = [
  createExpansionQuestion({
    id: "rexp5-agreement-01",
    passage: "The results of the experiment _____ consistent with the original hypothesis.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("is", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "The plural subject \u201cresults\u201d requires the plural verb \u201cwere.\u201d"),
      choice("was", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The plural subject \u201cresults\u201d requires the plural verb \u201cwere.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-02",
    passage: "A collection of letters _____ stored in the city archive.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("have been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("is", "The singular head noun \u201ccollection\u201d requires the singular verb \u201cis.\u201d"),
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The singular head noun \u201ccollection\u201d requires the singular verb \u201cis.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-03",
    passage: "The paintings and the sculptures _____ displayed in separate rooms.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "The compound subject joined by \u201cand\u201d is plural."),
      choice("is", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("was", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The compound subject joined by \u201cand\u201d is plural.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-04",
    passage: "Each of the reports _____ a different estimate.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("provide", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have provided", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were providing", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("provides", "The subject \u201cEach\u201d is singular."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The subject \u201cEach\u201d is singular.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-05",
    passage: "Neither the sensors nor the control unit _____ functioning correctly.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("have been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("was", "With \u201cneither...nor,\u201d the verb agrees with the nearer singular subject \u201cunit.\u201d"),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "With \u201cneither...nor,\u201d the verb agrees with the nearer singular subject \u201cunit.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-06",
    passage: "The number of online applications _____ increased since the portal launched.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has", "The subject is the singular noun \u201cnumber,\u201d not the plural noun \u201capplications.\u201d"),
      choice("have", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The subject is the singular noun \u201cnumber,\u201d not the plural noun \u201capplications.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-07",
    passage: "A series of follow-up interviews _____ planned for next month.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("is", "The singular head noun \u201cseries\u201d takes a singular verb here."),
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The singular head noun \u201cseries\u201d takes a singular verb here.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-08",
    passage: "The diary, along with several maps, _____ evidence of the journey.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("provide", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have provided", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were providing", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("provides", "The parenthetical phrase does not change the singular subject \u201cdiary.\u201d"),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The parenthetical phrase does not change the singular subject \u201cdiary.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-09",
    passage: "There _____ several possible explanations for the unexpected result.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("was", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("are", "The verb agrees with the plural noun phrase \u201cseveral possible explanations.\u201d"),
      choice("is", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The verb agrees with the plural noun phrase \u201cseveral possible explanations.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-10",
    passage: "The use of repeated images _____ the poem's central theme.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("were reinforcing", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("reinforces", "The singular subject is \u201cuse.\u201d"),
      choice("reinforce", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have reinforced", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The singular subject is \u201cuse.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-11",
    passage: "Neither the change in temperature nor the differences in humidity _____ sufficient to explain the result.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("were", "The nearer subject \u201cdifferences\u201d is plural, so the verb is plural."),
      choice("was", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("is", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The nearer subject \u201cdifferences\u201d is plural, so the verb is plural.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-12",
    passage: "The percentage of customers who renew their subscriptions _____ risen steadily.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("have", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has", "The singular subject \u201cpercentage\u201d requires \u201chas.\u201d"),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The singular subject \u201cpercentage\u201d requires \u201chas.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-13",
    passage: "What the committee members considered most important _____ the accessibility of the records.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("have been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("was", "The subject is the singular noun clause beginning with \u201cWhat.\u201d"),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The subject is the singular noun clause beginning with \u201cWhat.\u201d",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-14",
    passage: "More than one participant _____ concerns about the survey's wording.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("were expressing", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("expressed", "The construction \u201cmore than one\u201d takes a singular verb in standard usage."),
      choice("express", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have expressed", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The construction \u201cmore than one\u201d takes a singular verb in standard usage.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-15",
    passage: "The documents that the historian cites _____ in three separate archives.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "The plural subject \u201cdocuments\u201d requires a plural verb; the intervening clause does not change agreement."),
      choice("is", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("has been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("was", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The plural subject \u201cdocuments\u201d requires a plural verb; the intervening clause does not change agreement.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
  createExpansionQuestion({
    id: "rexp5-agreement-16",
    passage: "The extent to which the two methods differ _____ still uncertain.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("are", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("have been", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("were", "This choice creates a grammatical error, misuses punctuation, or does not fit the sentence structure."),
      choice("is", "The singular head noun \u201cextent\u201d controls the verb."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Verb Agreement",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["reading-expansion-pack-5", "standard-english-conventions"],
    walkthrough: [
      "Identify the sentence's grammatical structure before evaluating the choices.",
      "The singular head noun \u201cextent\u201d controls the verb.",
      "Choose the option that creates a complete, correctly punctuated, and grammatically consistent sentence.",
    ],
  }),
];