import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const punctuationReplacementQuestions = [
  createExpansionQuestion({
    id: "repl1-punctuation-01",
    passage: "The experiment measured three variables _____ temperature, humidity, and pressure.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "A colon introduces a list after a complete clause."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "A semicolon cannot introduce a simple list after this clause."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A colon introduces a list after a complete clause.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-02",
    passage: "The journal _____ published in 1908 _____ contains detailed accounts of the expedition.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" published in 1908", "This choice creates a sentence-boundary or punctuation error."),
      choice("; published in 1908;", "This choice creates a sentence-boundary or punctuation error."),
      choice(" published in 1908,", "This choice creates a sentence-boundary or punctuation error."),
      choice(", published in 1908,", "The nonessential phrase must be enclosed by commas."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The nonessential phrase must be enclosed by commas.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-03",
    passage: "The exhibit includes drawings, photographs _____ and sculptures.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "A semicolon cannot separate the final item in a simple series."),
      choice(",", "A comma separates the final item in a series."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma separates the final item in a series.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-04",
    passage: "The committee had one objective _____ make the application process easier to understand.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("—", "A dash is not appropriate for introducing this direct explanation in the sentence."),
      choice(":", "A colon introduces an explanation of the complete clause before it."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A colon introduces an explanation of the complete clause before it.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-05",
    passage: "The samples from the northern site _____ unlike those from the southern site _____ contained almost no salt.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", unlike those from the southern site,", "The nonessential contrast must be enclosed by commas."),
      choice(" unlike those from the southern site", "This choice creates a sentence-boundary or punctuation error."),
      choice("; unlike those from the southern site;", "This choice creates a sentence-boundary or punctuation error."),
      choice(" unlike those from the southern site,", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The nonessential contrast must be enclosed by commas.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-06",
    passage: "The proposal would lower fees _____ simplify forms, and shorten approval times.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", and", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
      choice(" :", "This choice creates a sentence-boundary or punctuation error."),
      choice(",", "A comma separates the first and second items in a three-part series."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma separates the first and second items in a three-part series.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-07",
    passage: "The narrator's tone is calm _____ reflective, and slightly ironic.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "A semicolon cannot separate coordinate adjectives in this series."),
      choice(",", "A comma separates coordinate adjectives in the series."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma separates coordinate adjectives in the series.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-08",
    passage: "The bridge, completed in 1911 _____ still carries traffic across the river.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "A colon cannot close the nonessential phrase after “completed in 1911.”"),
      choice(",", "The comma closes the nonessential phrase beginning after \u201cbridge.\u201d"),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The comma closes the nonessential phrase beginning after \u201cbridge.\u201d",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-09",
    passage: "The device's chief advantage _____ its ability to operate without external power _____ makes it useful in remote locations.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("\u2014 its ability to operate without external power \u2014", "A matched pair of dashes sets off the emphatic appositive."),
      choice(", its ability to operate without external power;", "This choice creates a sentence-boundary or punctuation error."),
      choice(": its ability to operate without external power,", "This choice creates a sentence-boundary or punctuation error."),
      choice(" its ability to operate without external power", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A matched pair of dashes sets off the emphatic appositive.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-10",
    passage: "The policy had two stated goals _____ reducing delays and increasing transparency.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
      choice("—", "A dash is less appropriate than a colon for introducing the two stated goals after a complete clause."),
      choice(":", "A colon introduces the two goals after a complete clause."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A colon introduces the two goals after a complete clause.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-11",
    passage: "The painting's central figure _____ a child holding a lantern _____ appears again in the artist's later work.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" a child holding a lantern,", "This choice creates a sentence-boundary or punctuation error."),
      choice(" : a child holding a lantern:", "This choice creates a sentence-boundary or punctuation error."),
      choice("\u2014 a child holding a lantern \u2014", "The appositive is correctly enclosed by a matched pair of dashes."),
      choice(", a child holding a lantern;", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The appositive is correctly enclosed by a matched pair of dashes.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-punctuation-12",
    passage: "The participants _____ all of whom had completed the first survey _____ returned for a follow-up interview.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" all of whom had completed the first survey,", "This choice creates a sentence-boundary or punctuation error."),
      choice(", all of whom had completed the first survey,", "The nonrestrictive clause must be enclosed by commas."),
      choice(" all of whom had completed the first survey", "This choice creates a sentence-boundary or punctuation error."),
      choice("; all of whom had completed the first survey;", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Punctuation",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The nonrestrictive clause must be enclosed by commas.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
];