import { choice, createExpansionQuestion } from "../readingExpansionPack1/factory";

export const sentenceBoundariesReplacementQuestions = [
  createExpansionQuestion({
    id: "repl1-boundaries-01",
    passage: "The sensor recorded a sudden drop in pressure _____ the research team checked the equipment for leaks.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(": consequently", "This choice creates a sentence-boundary or punctuation error."),
      choice("; consequently,", "A semicolon and conjunctive adverb correctly join two independent clauses."),
      choice(", consequently,", "This choice creates a sentence-boundary or punctuation error."),
      choice(" consequently", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A semicolon and conjunctive adverb correctly join two independent clauses.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-02",
    passage: "The town rebuilt the bridge _____ the flood had damaged its wooden supports.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("because", "\u201cBecause\u201d introduces the dependent clause explaining why the town rebuilt the bridge."),
      choice("; because", "This choice creates a sentence-boundary or punctuation error."),
      choice(", because", "This choice creates a sentence-boundary or punctuation error."),
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 0,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "\u201cBecause\u201d introduces the dependent clause explaining why the town rebuilt the bridge.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-03",
    passage: "The gallery added new lighting _____ visitors could see the paintings more clearly.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice("; so", "This choice creates a sentence-boundary or punctuation error."),
      choice(" because", "This choice creates a sentence-boundary or punctuation error."),
      choice(", so", "A comma plus \u201cso\u201d correctly joins two independent clauses in a cause-and-effect relationship."),
    ],
    answer: 3,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma plus \u201cso\u201d correctly joins two independent clauses in a cause-and-effect relationship.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-04",
    passage: "The survey was available in four languages _____ participation increased among multilingual residents.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" as a result", "This choice creates a sentence-boundary or punctuation error."),
      choice(": as a result", "This choice creates a sentence-boundary or punctuation error."),
      choice("; as a result,", "A semicolon and conjunctive phrase properly connect two complete clauses."),
      choice(", as a result,", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Easy",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A semicolon and conjunctive phrase properly connect two complete clauses.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-05",
    passage: "The coating reduced surface heat _____ it did not prevent damage caused by moisture.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(" although", "This choice creates a sentence-boundary or punctuation error."),
      choice(", but", "A comma with the coordinating conjunction \u201cbut\u201d joins contrasting independent clauses."),
      choice("; but", "This choice creates a sentence-boundary or punctuation error."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma with the coordinating conjunction \u201cbut\u201d joins contrasting independent clauses.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-06",
    passage: "The agency released the report on Friday _____ several appendices remained unavailable until Monday.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice("; however,", "A semicolon is required before \u201chowever\u201d when it joins independent clauses."),
      choice(", however,", "This choice creates a sentence-boundary or punctuation error."),
      choice(" however", "This choice creates a sentence-boundary or punctuation error."),
      choice(": however", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 0,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Government",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A semicolon is required before \u201chowever\u201d when it joins independent clauses.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-07",
    passage: "The narrator recognizes the house immediately _____ although the garden has changed completely.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(";", "This choice creates a sentence-boundary or punctuation error."),
      choice(" because", "This choice creates a sentence-boundary or punctuation error."),
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(",", "A comma correctly separates the main clause from the following dependent clause."),
    ],
    answer: 3,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Literature",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A comma correctly separates the main clause from the following dependent clause.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-08",
    passage: "The company expanded production _____ demand had risen steadily for six months.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", because", "This choice creates a sentence-boundary or punctuation error."),
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice("because", "The dependent clause beginning with \u201cbecause\u201d follows directly without a comma."),
      choice("; because", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Medium",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Economics",
    module: 1,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The dependent clause beginning with \u201cbecause\u201d follows directly without a comma.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-09",
    passage: "The model predicted rapid warming _____ field measurements, by contrast, showed only a slight increase.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "The sentence contains two independent clauses, and the parenthetical contrast does not change that."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice(" although", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 1,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The sentence contains two independent clauses, and the parenthetical contrast does not change that.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-10",
    passage: "The first source describes the migration as permanent _____ the second source suggests, however, that many families later returned.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(";", "A semicolon correctly separates the two complete clauses."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(" although", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 0,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "History",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A semicolon correctly separates the two complete clauses.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-11",
    passage: "The participants reported greater flexibility _____ because they had selected their own schedules, the researchers treated the result cautiously.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(", however,", "This choice creates a sentence-boundary or punctuation error."),
      choice(" however", "This choice creates a sentence-boundary or punctuation error."),
      choice(": however,", "This choice creates a sentence-boundary or punctuation error."),
      choice("; however,", "The conjunctive adverb links two independent clauses and therefore requires a semicolon."),
    ],
    answer: 3,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Social Science",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "The conjunctive adverb links two independent clauses and therefore requires a semicolon.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
  createExpansionQuestion({
    id: "repl1-boundaries-12",
    passage: "The critic admires the novel's structure _____ she argues, nevertheless, that its ending resolves the conflict too neatly.",
    prompt: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    choices: [
      choice(":", "This choice creates a sentence-boundary or punctuation error."),
      choice(" and", "This choice creates a sentence-boundary or punctuation error."),
      choice(";", "A semicolon correctly joins the independent clauses; \u201cnevertheless\u201d is parenthetical within the second clause."),
      choice(",", "This choice creates a sentence-boundary or punctuation error."),
    ],
    answer: 2,
    difficulty: "Hard",
    skill: "Sentence Boundaries",
    domain: "Standard English Conventions",
    passageType: "Humanities",
    module: 2,
    estimatedSeconds: 65,
    tags: ["legacy-replacement", "reading-expansion-pack-8"],
    walkthrough: [
      "Identify whether the sentence contains one clause, two independent clauses, or a nonessential element.",
      "A semicolon correctly joins the independent clauses; \u201cnevertheless\u201d is parenthetical within the second clause.",
      "Select the option that preserves the intended meaning and follows Standard English conventions.",
    ],
  }),
];